### ISSUE TITLE
template type missing

### ISSUE THREAD

**Issue by zhangenming** [johnsoncodehk/volar#4840] opened 2024-09-11 07:47 UTC
### Vue - Official extension or vue-tsc version

lastest

### VSCode version

lastest

### Vue version

lastest

### TypeScript version

lastest

### Steps to reproduce
https://play.vuejs.org/#eNp9UsFOwzAM/RWTy0DausM4oKobArQDHGACjpFQab3SLU2yJG03Vf133FTdJoF2s/2enfccN+xB66AqkYUssonJtQMRy2zOmbOcgUVX6gWXiZLWgTZKW5hDiutc4qrLooZLgN1udx+CdSaXGZft4vqGy6GprmtqGSHiiMto2j9CIylxWGgRO6QMIErzygcATdNNhLbt0+hqMvEFd9AIdS4EfCPE8gCTyanDiwv+9KntwIqm/Qs+tkI5CGVcIFklieR1Slg0PdPExrQEMrHOs2BjlaQdebecJarQuUDzpl1OJjkLwSMdFguh6hdfc6bE8VBPfjDZ/lPf2H1X42xl0KKpkLMj5mKToevh5ccr7ik+goVKS0HsC+A7WiXKTmNPeyxlSrLPeF7tc6GVcfR3n3a5dyjtYKoT2jFbz+eMDuXpgvWT3Flw6/voGGiLXxWabiYtkIBgdsfaX/XCzVU=

### What is expected?

qqq type will be ?string

### What is actually happening?

qqq type will be any

**Comment by KazariEX** [comment] 2024-09-11 07:59
![image](https://github.com/user-attachments/assets/10608a6e-7b5d-4656-90f5-400a4d0f037f)

**Comment by KazariEX** [comment] 2024-09-11 08:04
Can you confirm that your Vue - Official version is 2.1.6?

**Comment by zhangenming** [comment] 2024-09-11 08:46
![image](https://github.com/user-attachments/assets/df2d0a2e-f66a-4649-b342-67ffae2a1ac3)

**Comment by zhangenming** [comment] 2024-09-11 08:50
![image](https://github.com/user-attachments/assets/77b9beca-0056-4b67-919b-54e12614de96)
![image](https://github.com/user-attachments/assets/34433d5a-cee2-4394-b374-807901cb8b10)

**Comment by KazariEX** [comment] 2024-09-11 09:04
我无法复现这个问题，你可以尝试制作一个最小复现来检查问题是否依然存在

**Comment by Arinono** [comment] 2024-09-11 09:37
I can get the playground link to show the error described by changing compilation options to target 3.5:
![image](https://github.com/user-attachments/assets/9e3a48fc-f54d-4bf5-91c7-7dfa9b8c15aa)
![image](https://github.com/user-attachments/assets/6bbe4cc7-c939-4160-af88-82ce7666167e)

**Comment by KazariEX** [comment] 2024-09-11 09:44
Duplicate of #4704

**Closed as not planned by KazariEX** 2024-09-11 09:44 UTC
Labels: duplicate
