### ISSUE TITLE
A request has failed

### ISSUE THREAD

**Issue by zhanglan421** [johnsoncodehk/volar#468] opened 2021-09-08 04:14 UTC
When I click on any place, vscode will pop up a prompt box，
![image](https://user-images.githubusercontent.com/74143700/132445498-1c07ffea-f3f5-46fc-a7b0-daf9aba09f4c.png)

**in output:**
Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Debug Failure. Illegal value: " "
  Code: -32603 
(node:8116) UnhandledPromiseRejectionWarning: Error: Debug Failure. Illegal value: " "
![image](https://user-images.githubusercontent.com/74143700/132445541-ddf1dcda-3a8a-4aa8-98a9-3dd468cffabf.png)

How to solve it

**Comment by johnsoncodehk** [comment] 2021-09-08 08:06
It seem you are using workspace TS module, what are your TS version? Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by zhanglan421** [comment] 2021-09-08 08:12
> 看来您正在使用工作区 TS 模块，您的 TS 版本是什么？你能在[https://github.com/johnsoncodehk/volar-starter 中](https://github.com/johnsoncodehk/volar-starter)重现这个问题吗？

**Comment by zhanglan421** [comment] 2021-09-08 08:40
my TS version : 4.1.5 and when I roll back the volar version to 0.27.9, the pop-up window will not appear

**Comment by beetaa** [comment] 2021-09-09 04:46
@johnsoncodehk @zhanglan421 I think it's a problem of the newest version, when I downgrade to v0.27.15, Volar works properly again. so the issue could be caused by the recently merged pull requests.

**Comment by yaegassy** [comment] 2021-09-09 04:46
@johnsoncodehk @zhanglan421 

I've created repro case. Can be reproduced with typescript `v4.1.x` (Use Workspace Version 4.1.6). There is no problem with `v4.3.x` and `v4.4.x`.

- <https://github.com/yaegassy/issue468-volar>

It seems that my suggestion to add `" "` to "triggerCharacter" is having a negative impact... :(

It may be that some adjustments are needed in the process of sending requests for completion, such as "GetRefCompleteEditsRequest"

As a supplement, `coc-volar` also reproduces the problem.

### DEMO

https://user-images.githubusercontent.com/188642/132623463-bd6ea31f-ed39-4da4-930c-940a9be68a23.mp4

**Comment by yaegassy** [comment] 2021-09-09 05:19
I don't know the correct way to fix it, but when I adjusted `getTsResult()`, the error did not occur anymore.

```diff
diff --git a/packages/vscode-vue-languageservice/src/services/completion.ts b/packages/vscode-vue-languageservice/src/services/completion.ts
index 5e8330c..f55ad8b 100644
--- a/packages/vscode-vue-languageservice/src/services/completion.ts
+++ b/packages/vscode-vue-languageservice/src/services/completion.ts
@@ -177,7 +177,7 @@ export function register(
                }
                async function getTsResult() {
                        let result: vscode.CompletionList | undefined;
-                       if (context?.triggerCharacter && !triggerCharacter.typescript.includes(context.triggerCharacter)) {
+                       if (context?.triggerCharacter) {
                                return result;
                        }
                        for (const tsLoc of sourceFiles.toTsLocations(uri, position)) {
```

**Comment by yaegassy** [comment] 2021-09-09 05:26
@johnsoncodehk It seems that triggerCharacter needs to be changed depending on the typescript version. 

- REF: VSCode's typescript-language-features
  - <https://github.com/microsoft/vscode/blob/main/extensions/typescript-language-features/src/languageFeatures/completions.ts#L811-L833>

```typescript
	private getTsTriggerCharacter(context: vscode.CompletionContext): Proto.CompletionsTriggerCharacter | undefined {
		switch (context.triggerCharacter) {
			case '@': // Workaround for https://github.com/microsoft/TypeScript/issues/27321
				return this.client.apiVersion.gte(API.v310) && this.client.apiVersion.lt(API.v320) ? undefined : '@';

			case '#': // Workaround for https://github.com/microsoft/TypeScript/issues/36367
				return this.client.apiVersion.lt(API.v381) ? undefined : '#';

			case ' ':
				const space: Proto.CompletionsTriggerCharacter = ' ';
				return this.client.apiVersion.gte(API.v430) ? space : undefined;

			case '.':
			case '"':
			case '\'':
			case '`':
			case '/':
			case '<':
				return context.triggerCharacter;
		}

		return undefined;
	}
```

**Comment by yaegassy** [comment] 2021-09-09 06:25
@zhanglan421 You can also use `volar-starter` to provide a repro case.

**Comment by johnsoncodehk** [comment] 2021-09-10 19:12
@yaegassy confirmed, thank you!

**Comment by jiaoshibo** [comment] 2021-09-14 02:37
Enter `\\`，popup this prompt box。

ts version: 4.4.2

![屏幕截图 2021-09-14 103603](https://user-images.githubusercontent.com/30992316/133185354-e281fca8-feb5-44bb-bdb4-d06a7dfca314.png)

```bash
[Error - 上午10:31:21] Request textDocument/codeAction failed.
  Message: Request textDocument/codeAction failed with message: Debug Failure. Illegal value: "\\"
  Code: -32603 

```

**Closed** 2021-09-14 03:24 UTC
Labels: bug

**Comment by pisandelli** [comment] 2022-02-25 18:41
Hello guys! Sorry, but this is very annoying. What I have to do to fix it?
Every time I move the mouse or click, this output is triggered.
I don't know exactly what I'm doing wrong, it seems to be random... I guess. 

```
[Error - 3:37:24 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Range#create called with invalid arguments[[object Object], [object Object], undefined, undefined]
  Code: -32603 
 ```
![volar-anoying](https://user-images.githubusercontent.com/1986634/155770012-c13503f6-97c0-4fc7-b2eb-6486526de493.gif)

**Comment by johnsoncodehk** [comment] 2022-03-01 15:46
@pisandelli please open a new issue, and provide the error message from "Go to output".

**Comment by pisandelli** [comment] 2022-03-07 17:42
> @pisandelli please open a new issue, and provide the error message from "Go to output".

It's on #1012 

Thanks guys!
Cheers!
