### ISSUE TITLE
"Property <property> is private and only accessible within class <classname>" error message should not be present

### ISSUE THREAD

**Issue by mathmul** [johnsoncodehk/volar#1303] opened 2022-05-13 11:51 UTC
If there's something wrong with this code, please let me know. ATM I believe there is no mistake in this code, so I don't think Volar should report any errors from static analysis.

# Code
```vue
<template>
  <Loader :widthPx="40" :heightPx="40" :show="isLoading" color="black" />
</template>

<script lang="ts">
import '@/assets/css/style.css';
import Vue from 'vue';
import { Component } from 'vue-property-decorator';
import Loader from "../components/Loader.vue";

@Component({
  components: {
    Loader,
  },
  filters: {
  },
})
export default class OrderView extends Vue {
  private isLoading = false;
}
</script>
```

# Code image with underlined error and red component
![image](https://user-images.githubusercontent.com/25301301/168276679-a8fc644b-f064-4802-ab9f-1b2b568875c9.png)

# Image of error message
![image](https://user-images.githubusercontent.com/25301301/168276723-015e7e39-8c09-4e60-acdd-3e9b37d4553b.png)

## NOTE

I'm using Vue 2, and have added the necessary lines in both `package.json` as well `tsconfig.json`. I also disabled Vetur.

**Comment by maroon1** [comment] 2022-05-13 12:53
@mathmul use `public` instead of `private`

**Comment by johnsoncodehk** [comment] 2022-05-15 18:44
Duplicate of #997

**Closed by johnsoncodehk** 2022-05-15 18:44 UTC
