### ISSUE TITLE
Vue3 setup script `withDefaults` types check

### ISSUE THREAD

**Issue by DefectingCat** [johnsoncodehk/volar#614] opened 2021-10-19 02:21 UTC
I have a compoent define some props like:

```ts
interface Props {
  placeholder?: string;
  inputValue: string;
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: '作品名称或设计师查询',
});
```

Because the `placeholder` is optional, so i define it like: `placeholder?: string;`.

For typescript, it's optional: `string | undefined`, that's right. But for vue, its has a default value `string`.

When i pass `placeholder` to the child component will be get a error from  ts:

```vue
      <template #default>
        <!-- 搜索 -->
        <ContentSearch
          class="!w-[25%]"
          v-model:inputValue="inputValue"
          :placeholder="placeholder"
          @toSearch="emit('toSearch')"
        />
        <!--  -->
        <slot name="bar"></slot>
      </template>
```

![image](https://user-images.githubusercontent.com/25033493/137832307-ec2c5901-b32b-4516-b439-85c2e3a6f6cd.png)

Child component `ContentSearch` props define like:

```ts
const props = defineProps<{
  inputValue: string;
  placeholder: string;
}>();
```

Complete compoent code :

```vue
<template>
  <template v-if="isMoblie">
    <slot name="moblie"></slot>
  </template>

  <template v-else>
    <ContentBar>
      <template #default>
        <!-- 搜索 -->
        <ContentSearch
          class="!w-[25%]"
          v-model:inputValue="inputValue"
          :placeholder="placeholder"
          @toSearch="emit('toSearch')"
        />
        <!--  -->
        <slot name="bar"></slot>
      </template>
    </ContentBar>

    <div class="mt-20px h-695px overflow-y-auto bg-light-50">
      <slot name="table"></slot>
    </div>
  </template>
</template>

<script lang="ts" setup>
import ContentBar from '@/components/common/ContentBar.vue';
import ContentSearch from '@/components/common/ContentSearch.vue';
import { breakpointsTailwind, useBreakpoints, useVModels } from '@vueuse/core';

const breakpoints = useBreakpoints(breakpointsTailwind);
const isMoblie = breakpoints.smaller('sm');

interface Props {
  placeholder?: string;
  inputValue: string;
}

const props = withDefaults(defineProps<Props>(), {
  placeholder: '作品名称或设计师查询',
});
const emit = defineEmits(['update:inputValue', 'toSearch']);

const { inputValue } = useVModels(props, emit);
</script>

<style scoped lang="scss"></style>
```

It's maybe a vue problem

**Comment by johnsoncodehk** [comment] 2021-10-19 02:23
Fixed in https://github.com/johnsoncodehk/volar/commit/c7b171098bb7f1653e8f670e00903e78fe298e3f, thank you. :)

**Comment by johnsoncodehk** [comment] 2021-10-19 02:23
Duplicate of #611

**Closed by johnsoncodehk** 2021-10-19 02:23 UTC
