### ISSUE TITLE
Syntax highlighting became much slower with 'v0.39.2' and later

### ISSUE THREAD

**Issue by onurusluca** [johnsoncodehk/volar#1663] opened 2022-08-02 06:03 UTC
Related to #1615 also probably to #1600

Creating a more detailed and different issue on @johnsoncodehk request.

After some tests I found that with v0.39.2 Volar got very slow and sluggish. 
 
**v0.39.2 and later:**
![slow](https://user-images.githubusercontent.com/51825926/182302679-979da0ed-9a7f-43c9-aec1-06706c4d4fb5.gif)

**v0.39.1 and before (less than a second):**
![fast](https://user-images.githubusercontent.com/51825926/182302749-091d2953-fb4e-4134-9925-8b73a6769374.gif)

This problem may be caused  by a commit after d27d989355adc2aa3f9c6260226bd3167e3fac97 or later . Because all the commits after that are included in v0.39.2. 

I am looking into it but it would be better if someone with more experience in Volar took a look at it.

Sharing some details for context:

> VsCode: June 2022 (version 1.69)
> 
> Operating System:
> Microsoft Windows 10 Home 64-bit
> CPU:
> Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
> Motherboard:
> Alienware Alienware m17 R3 (U3E1)
> RAM:
> 32.00 GB Unknown form factor Unknown 2667MHz
> GPU:
> Intel(R) UHD Graphics 1024 MB
> NVIDIA GeForce RTX 2070 Super 4095 MB
> 
> System:
> OS: Windows 10 10.0.19044
> CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
> Memory: 18.41 GB / 31.77 GB
> Binaries:
> Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
> npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
> Browsers:
> Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
> Internet Explorer: 11.0.19041.1566

**Comment by johnsoncodehk** [comment] 2022-08-02 06:35
Thank to confirm the commit! `GetDocumentVersionRequest` is completely used for improve performance, it's removed because it don't have effect on my macbook now, maybe it just affect for windows. I will re-add it.

**Comment by onurusluca** [comment] 2022-08-02 06:47
@johnsoncodehk Thanks for the quick reply. To be clear I don't know if GetDocumentVersionRequest causes the problem. It may be that commit or later.

I am more than happy to help testing anything.

**Comment by johnsoncodehk** [comment] 2022-08-03 12:39
I found that https://github.com/johnsoncodehk/volar/commit/d27d989355adc2aa3f9c6260226bd3167e3fac97 is released with 0.39.1, so it should not the reason.

I think https://github.com/johnsoncodehk/volar/commit/8673fa1f9b871ccecb71539d8437d8dae08d8b92 the most possible lead to this problem, please let me know if [volar-0.39.5-alpha.2.vsix.zip](https://github.com/johnsoncodehk/volar/files/9251321/volar-0.39.5-alpha.2.vsix.zip) can resolve the problem or not, which try revert the commit.

**Comment by onurusluca** [comment] 2022-08-03 19:14
@johnsoncodehk Hey! Thanks for the reply. I tried this version and it works fine. Not slow, just good, No problems afaic. 
Took a look at https://github.com/johnsoncodehk/volar/commit/8673fa1f9b871ccecb71539d8437d8dae08d8b92 . I think diagnostics take some time so slows down the syntax highlighting.

**Comment by BryceBarbara** [comment] 2022-08-04 16:55
I'm able to see a performance impact between v0.39.1 and v0.39.2 as well.

v0.39.1 | v0.39.2
--------|-------
![Code_9Fsx1mhVkf](https://user-images.githubusercontent.com/24460210/182907317-1060b88c-d4bd-4b3b-84eb-9d1d3ae15406.gif) | ![Code_HwYCxbFZ7D](https://user-images.githubusercontent.com/24460210/182907339-abf0501e-c8f8-42d6-8f2a-eb853fdb50e2.gif)

**Comment by BryceBarbara** [comment] 2022-08-04 17:00
Looks like v0.39.5-alpha.2 is also faster for me. I've recorded a gif of it just for sake of completeness:

![Code_dpfdxhy7fy](https://user-images.githubusercontent.com/24460210/182908223-9df0b01e-dcfd-4c25-b794-3d71b78575e2.gif)

**Closed** 2022-08-06 07:08 UTC
Labels: bug

**Comment by johnsoncodehk** [comment] 2022-08-06 07:13
Thanks for the information, I'm not sure if https://github.com/johnsoncodehk/volar/commit/18b62d108ba8968ed1d4a663247b48c8aa727531 fixed this problem or not because I can't reproduce this problem on mac, please try [volar-0.39.5-alpha.3.vsix.zip](https://github.com/johnsoncodehk/volar/files/9274559/volar-0.39.5-alpha.3.vsix.zip) and let me know, thank you.
