### ISSUE TITLE
Vue3 using type-based DefineEmits receives incompatible error

### ISSUE THREAD

**Issue by sw-joechen** [johnsoncodehk/volar#1732] opened 2022-08-19 06:17 UTC
// child component
![image](https://user-images.githubusercontent.com/101158194/185555091-2f9e735d-f638-4768-bede-44460bc3458e.png)

// parent component
![image](https://user-images.githubusercontent.com/101158194/185555181-a9c9cff3-d488-4c7c-bcbd-727b4547b855.png)

it works fine in v0.35.0

**Comment by johnsoncodehk** [comment] 2022-08-27 16:49
I can't reproduce this problem in https://github.com/johnsoncodehk/volar-starter, please provide minimal reproduction.

**Comment by sw-joechen** [comment] 2022-08-29 09:55
I created a new project with
`npm init vue@latest`
add the code which is shown above
run build script
`npm run build`
you will receive the error like above
here is the repo 
https://github.com/sw-joechen/demo2
thanks for replying

**Comment by johnsoncodehk** [comment] 2022-09-04 22:33
It seems fixed in v0.40.2.

**Closed by johnsoncodehk** 2022-09-04 22:33 UTC
Labels: need more info / repro
