### ISSUE TITLE
Is Volar compatible with Yarn PnP?

### ISSUE THREAD

**Issue by stecive** [johnsoncodehk/volar#1177] opened 2022-04-12 09:43 UTC
Hi,

Can't make vscode not showing errors on _.vue_ files. If i enable _take over mode_, errors spread to _.ts_ files. Am i doing something wrong?
My application is a default Vue3 one, generated by Vitejs with typescript enabled, Yarn Workspace + PnP.
Errors are (on `App.vue`):
![image](https://user-images.githubusercontent.com/103494982/162931279-bd7807e2-bc46-4610-9fcb-fd2ff2c7d63e.png)
`Cannot find module 'vue' or its corresponding type declarations.ts(2307)`
There are more error on `HelloWorld.vue`, like `Cannot find name 'defineProps'.ts(2304)`.

**Comment by dark-kitt** [comment] 2022-04-16 19:39
I have exactly the same problem. Any solutions for this?

**Comment by dark-kitt** [comment] 2022-04-17 11:04
I'm not so used to TypeScript, there is definitely someone who has better skills than me or can fix the issue with Volar. 

Anyhow, for my issue, my current workaround looks like this.

_**vue-shim.d.ts**_
```javascript
declare module '*.vue' {
  import Vue from 'vue';
  export default Vue;
}

// Cannot find module ts(2307)
declare module 'vue' {
  import Vue, {
    ref,
    withDefaults,
    defineProps,
    defineComponent,
    PropType
  } from 'vue';
  import type { Ref } from 'vue';

  // Module '"vue"' has exported member ts(2305)
  export function ref<Ref>(...args: any[]): any;
  // Namespace '"vue"' has no exported member ts(2694)
  interface PropType {
    type: () => PropType;
  }
  export = PropType;

  // define global assets
  declare global {
    // Cannot find name ts (2304)
    function withDefaults(...args: any[]): any;
    function defineProps<Props>(...args: any[]): any;
    // Property does not exist ts(2339)
    function defineComponent(...args: any[]): any;
  }

  export const Vue = Vue;
}
```

**Comment by rschmied** [comment] 2022-07-14 17:26
I've followed the guidance on [SO here](https://stackoverflow.com/a/69412529) -- it requires to manually install additional modules for ts/vscode support, disable "take over mode" and select the workspace TS SDK. So, this I likely ended up in an environment that prompted the creation of "take over mode" -- but, heck, it does work nicely for me so far.  And unless this is fixed I am happy when VSCode is happy :smile: 

This is basically:
- vite 3.0.0
- yarn 3.2.1 in PnP mode (single root / default workspace)

There's nothing else beyond the default sample project.
```
$ yarn info --name-only
├─ @vitejs/plugin-vue@npm:3.0.0
├─ breakv2@workspace:.
├─ typescript@patch:typescript@npm%3A4.7.4#~builtin<compat/typescript>::version=4.7.4&hash=7ad353
├─ vite@npm:3.0.0
├─ vue-tsc@npm:0.38.5
└─ vue@npm:3.2.37
```

The result is proper type resolution both in the .ts as well as in the .vue files.  And I can build the project as I expect it to build / dev via `yarn build` / `yarn dev`.

**Comment by johnsoncodehk** [comment] 2022-07-16 12:57
Duplicate of #918

**Closed by johnsoncodehk** 2022-07-16 12:57 UTC
