### ISSUE TITLE
Fallthrough attributes not recognized

### ISSUE THREAD

**Issue by DhivinX** [johnsoncodehk/volar#1384] opened 2022-06-03 06:07 UTC
Hi,

after the last update, Fallthrough Attributes are no longer recognizable.
https://vuejs.org/guide/components/attrs.html

Simple example here:

Child component:
```html
<template>
    <q-btn @click="clicks++">{{ clicks }}</q-btn>
    <!-- q-btn has color prop -->
</template>

<script setup lang="ts">
import { ref } from 'vue';

const clicks = ref<number>(0);
</script>
```

Parent component:
```html
<template>
    <CompChild color="red"></CompChild>
</template>

<script setup lang="ts">
import CompChild from './CompChild.vue';
</script>
```

```
Type '{ color: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & 
VNodeProps & AllowedComponentProps & ComponentCustomProps, never>'.
  Property 'color' does not exist on type 'IntrinsicAttributes & Partial<{}> & Omit<Readonly<ExtractPropTypes<{}>> & VNodeProps & 
AllowedComponentProps & ComponentCustomProps, never>'.ts(2322)
```

**Comment by johnsoncodehk** [comment] 2022-06-03 13:22
See https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1145361472.

**Comment by johnsoncodehk** [comment] 2022-06-03 13:22
Duplicate of #1383

**Closed by johnsoncodehk** 2022-06-03 13:22 UTC
