### ISSUE TITLE
TypeScript shows JSX errors even though JSX is not used (Vue 3 composition API)

### ISSUE THREAD

**Issue by jangxx** [johnsoncodehk/volar#1736] opened 2022-08-19 16:48 UTC
Every time I want to do a typecast like `<number>variable`, Volar breaks completely, starts throwing errors `ts(17008)` and `ts(2786)` and underlines essentially every line in the `<template>` section. I'm using Vue 3 and all of my TS code is written in the `<script lang="ts" setup>` part of the SFC, to make use of the Composition API.

**Comment by qgates** [comment] 2022-08-22 14:58
Also #1744 #1706

**Comment by Soviut** [comment] 2022-08-22 15:38
Installing any version before prior to `0.40.0` fixed the problem for me.

On the "Uninstall" button, click the dropdown arrow and choose "Install another version". Then choose `0.39.5`

![image](https://user-images.githubusercontent.com/226882/185961147-0f8986fc-495b-4048-a4a8-7e97e7d3c86f.png)

**Comment by caio-2k** [comment] 2022-08-31 20:13
Same here.

**Comment by xiaoxiangmoe** [comment] 2022-09-01 06:40
duplicate of https://github.com/johnsoncodehk/volar/issues/1706

**Closed by xiaoxiangmoe** 2022-09-01 06:40 UTC
Labels: duplicate
