### ISSUE TITLE
cant recognize .vue file, just treat like js

### ISSUE THREAD

**Issue by guopenghui** [johnsoncodehk/volar#952] opened 2022-02-11 09:57 UTC
![image](https://user-images.githubusercontent.com/13451866/153570517-7167d91d-8027-4121-a6b9-9f075d1de369.png)
![image](https://user-images.githubusercontent.com/13451866/153570671-1a956f94-44be-44d2-a63b-8db8776b8b65.png)

But vetur works normally (before I removed it).
I didnt find same problem on internet

**Comment by johnsoncodehk** [comment] 2022-02-12 18:52
Duplicate of #264, #370

**Closed by johnsoncodehk** 2022-02-12 18:52 UTC
