### ISSUE TITLE
🐛 BUG: False Positive on pug plugin in monorepos

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [johnsoncodehk/volar#2277] opened 2023-01-04 09:08 UTC
volar doctor reports false positive in monorepos
`@volar/vue-language-plugin-pug missing`

**Comment by johnsoncodehk** [comment] 2023-01-04 18:52
Duplicate of #2272 

I still can't reproduce the problem...

**Closed by johnsoncodehk** 2023-01-04 18:52 UTC
