### ISSUE TITLE
if bind scoped slot prop, shorthand attribute report error 

### ISSUE THREAD

**Issue by ghost** [johnsoncodehk/volar#4001] opened 2024-03-06 01:56 UTC
this is example, v-bind shorthand can bind scoped slot props, but vue-tsc report error
[play vue](https://play.vuejs.org/#eNqNUk1PwzAM/SsmHDoktImPU+kmAZoEHAAxJC65VK1XMtIkStIxNPW/46TrxiS+bo7fi/1svzW7NGa4bJClLHOFFcaDQ98YkLmqxpx5x9mEK1EbbT2sweIcWphbXUNC35ItdK1rs8kPR+ERqiYXXHFVaOU81K6Ccfg/SG5QSg0v2sryIDniKht1rakRPTzWRuYe6QWQhVIxorhH4JBKelSeBK5hmcsGoSWdmVCm8ZB2mdEkG+3Xiroo3MuzYxqS6s1FNVw4rWgT68DmrCC2kGgfjBc0AmcpRCRgOU3wfhdz3jZ43OeLVyzevskv3CrkOHu06NAukbMt5nNboe/g6eweVxRvwVqXjST2L+ATOi2boLGjXTWqJNlfeFHtbTyUUNWzm65oe64fKggNzDbyOaPDhUX9NPpO7tnwPP7jqqUt9kf/p5XICftGKnEuFM6k9i6LzTZHHhirjSMB3aVTcN7SFNAepZCrD2o+GZCJep91x9847eT07C+DlWLZ+8tRb1B5jaR205yznZ06D3X8fQu1n9HFGcY=)

![image](https://github.com/vuejs/language-tools/assets/30503937/6045c6a2-4e7f-4a43-bb9c-d5668fe14519)

**Comment by so1ve** [comment] 2024-03-06 04:08
What's your vue-tsc version?

**Comment by liuzw2579** [comment] 2024-03-06 05:37
> What's your vue-tsc version?

2.0.5

**Comment by so1ve** [comment] 2024-03-06 08:50
Duplicate of #3997

**Closed as not planned by so1ve** 2024-03-06 08:50 UTC
Labels: duplicate
