### ISSUE TITLE
no error on wrong emit callback

### ISSUE THREAD

**Issue by andylix** [johnsoncodehk/volar#517] opened 2021-09-22 23:12 UTC
https://github.com/andylix/volar-emit-type-unknown/tree/wrong-callback

```
<script lang="ts" setup>
import MyButton from './components/MyButton.vue'

// right callback
function add(param: number) {
  console.log('add', param)
}

// wrong callback
function foo(str: string) {
  console.log(str)
}

</script>

<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <MyButton
    @add-something="foo"
  ></MyButton>
</template>

```

I remember that it showed the right error in a previous Volar version, but it doesn't show any error anymore.

**Comment by johnsoncodehk** [comment] 2021-09-22 23:13
Emmmm it's fixed. 😅

**Comment by johnsoncodehk** [comment] 2021-09-22 23:14
Duplicate of #516.

**Closed by johnsoncodehk** 2021-09-22 23:14 UTC
Labels: duplicate

**Comment by andylix** [comment] 2021-09-23 02:28
> Duplicate of #516

Hi, when will this be installable in VSCode?

**Comment by johnsoncodehk** [comment] 2021-09-23 03:03
I have to resolve #502, #515, #519 in next version, you can package master branch yourself for now:

```
$ git clone https://github.com/johnsoncodehk/volar.git
$ cd volar
$ yarn && yarn compile
$ cd extensions/vscode-vue-language-features
$ yarn prerelease
```
