### ISSUE TITLE
Very high cpu usage when typing anything

### ISSUE THREAD

**Issue by xxSkyy** [johnsoncodehk/volar#315] opened 2021-07-16 22:12 UTC
I do really enjoy using volar, it's incredible tool for vue3 and typescript.

But I've noticed that when typing anything volar consumes big amount of cpu, even when I type comment. 
after disabling volar highest process using at most 2% cpu

Here's video https://www.youtube.com/watch?v=4kastswNIUs

Is it normal? IMO It shouldn't use that much of resources 

I'm using 
Macbook M1
Latest VSCode insiders
Latest Volar

**Comment by johnsoncodehk** [comment] 2021-07-16 22:15
Can you record again after disable `volar.autoCompleteRefs`?

**Comment by xxSkyy** [comment] 2021-07-16 22:25
changing `volar.autoCompleteRefs` didn't change anything

Can I do profiling with firefox? I don't want to install anything from google

**Comment by xxSkyy** [comment] 2021-07-16 22:34
I disabled every option in volar settings, still same usage

**Comment by xxSkyy** [comment] 2021-07-16 23:28
Profiled record

[CPU-20210717T012645.cpuprofile.zip](https://github.com/johnsoncodehk/volar/files/6833800/CPU-20210717T012645.cpuprofile.zip)

**Comment by johnsoncodehk** [comment] 2021-07-16 23:48
> Can I do profiling with firefox?

Sorry I don't know, maybe you can use Edge but I'm not sure.

> I disabled every option in volar settings, still same usage

Thanks for the profiling record, but this is HTML server profiling, we need API server and Document server profiling.

> I checked on windows pc, there were no problem like that

It may also be just a resource allocation problem for M1. Can you compare the CPU usage of typing in *.ts and typing in *.vue?

**Comment by xxSkyy** [comment] 2021-07-17 00:03
> It may also be just a resource allocation problem for M1. Can you compare the CPU usage of typing in *.ts and typing in *.vue?

It's same usage, also I can't be 100% accurate if it's not existing on windows as I could just not notice on I9 cpu

>Thanks for the profiling record, but this is HTML server profiling, we need API server and Document server profiling.

My bad, here's all of them 
[profiles.zip](https://github.com/johnsoncodehk/volar/files/6833852/profiles.zip)

**Comment by johnsoncodehk** [comment] 2021-07-17 12:32
Profiling record shows that everything is works good.

Since you mentioned the same problem with *.ts typing, this is more likely a vscode / macbook M1 problem, because *.ts is not handled by volar, but by the built-in TS extension of vscode. To confirm this, please try to disable volar, then typing in *.ts again and check the cpu usage.

In addition, please also try the non-insiders version of VSCode.

**Comment by xxSkyy** [comment] 2021-07-17 14:13
>Since you mentioned the same problem with *.ts typing, this is more likely a vscode / macbook M1 problem, because *.ts is not handled by volar, but by the built-in TS extension of vscode. To confirm this, please try to disable volar, then typing in *.ts again and check the cpu usage.

But the volar process gets to 200-300% cpu usage typing even on ts files. As I said , disabled volar and highest cpu usage were round 2-3% process.


I tried normal vscode, same thing.

Here's another screen record with vue and ts files - see that @volar are still using cpu even with ts file https://www.youtube.com/watch?v=oZ1ABtgyaOY

And here's with volar disabled, usage are pretty fine then
https://www.youtube.com/watch?v=Tujra4gM0AM

**Comment by johnsoncodehk** [comment] 2021-07-17 16:48
Thanks for your feedback, I will test this issue on volar-starter + macbook m1.

How to open the cpu usage panel in your video?

**Comment by xxSkyy** [comment] 2021-07-19 08:44
You need to have homebrew, here's instructions-https://brew.sh/
Then you do `brew install htop` and `sudo htop` (Its recommended to use sudo) and click on cpu tab to sort it by usage.

**Comment by johnsoncodehk** [comment] 2021-07-19 11:29
Thanks for the information!

Please try to setup `"editor.semanticHighlighting.enabled": false` and check cpu usage again.

**Comment by xxSkyy** [comment] 2021-07-19 13:39
> Thanks for the information!
> 
> Please try to setup `"editor.semanticHighlighting.enabled": false` and check cpu usage again.

I changed it to false and reloaded vscode, still same thing. I also tried removing my settings.json but it also didn't do anything.

**Comment by johnsoncodehk** [comment] 2021-07-19 13:41
Can you provide Document server profiling record with `"editor.semanticHighlighting.enabled": false`?

**Comment by xxSkyy** [comment] 2021-07-19 14:09
Sure - here [profiles1.zip](https://github.com/johnsoncodehk/volar/files/6841553/profiles1.zip)

I'm starting thinking if it's not an normal behviour, I'll test how it looks on my older windows laptop.
Can you tell me your cpu usage of app while typing anything in vscode with volar on?

**Comment by johnsoncodehk** [comment] 2021-07-19 15:10
Don't know why but setup `"editor.semanticHighlighting.enabled": false` seem no effect for you, semantic tokens is still collect. Please try remove this line https://github.com/johnsoncodehk/volar/blob/master/packages/vscode-client/src/extension.ts#L47. And run debug mode to check cpu usage and profiling again.

In the expected situation, the document server keeps running when typing, because the diagnosis of the document server is very time-consuming, the diagnosis speed does not catch up with the typing speed during continuous typing, and the server continues to abort the old diagnosis and start new ones. Diagnose until you stop typing and wait for the final diagnosis to complete. I can increase the diagnostic delay to alleviate this problem, but I need to strike a balance between performance and UX. On the other hand, I can see if reduce the work of the document server can alleviate the problem, which is why I asked you to turn off `editor.semanticHighlighting.enabled`.

We can't control progress cpu usage. Regarding whether a single process full loading will cause overheating or not, I think it base on how vscode/cpu/macbook handle it. Macbook has Tubro Boost feature to increase power consumption to speed up program execution when progress high loading, but this conflicts with our expectations. We hope use a process to keep it full loading to get the best UX. (btw, software like Turbo Boost Switcher can turn off the Tubro Boost feature.)

Without requiring users to install additional software, I need to consider how to reduce document server loading.

**Comment by xxSkyy** [comment] 2021-07-19 19:46
I removed this line, cleared cache ran debug and still same thing happens with cpu.

>We can't control progress cpu usage. Regarding whether a single process full loading will cause overheating or not, I think it base on how vscode/cpu/macbook handle it. Macbook has Tubro Boost feature to increase power consumption to speed up program execution when progress high loading, but this conflicts with our expectations. We hope use a process to keep it full loading to get the best UX. (btw, software like Turbo Boost Switcher can turn off the Tubro Boost feature.)
I'm not sure if M1 one has this function, they already are very powerfull and at most it throttles a bit when it gets hot. 

I found about M1 

> The M1 is a little different: Apple says it doesn't have turbo boost. It runs at its top clock speed most of the time

And I can agree with it, M1 is blazing fast and even without any fan it most of time stays cold.

I just checked thermals.
While having couple things running in background + twitch stream etc and having connected 3440x1440@144hz monitor it has round 55-60 degrees. But when I start typing anything in vscode it  jumps to 85 degrees in couple seconds. I did test vetur in same way,  it also affects cpu usage but not that much.

Anyway I'd be really happy if somehow it be decreased, because when I work with nodejs+ts+plugins or ruby on rails there are no things like that, if I could help with debugging it dont hestitate to ask!

**Comment by johnsoncodehk** [comment] 2021-07-20 00:39
> I removed this line, cleared cache ran debug and still same thing happens with cpu.

Can you provide profiling record?

**Comment by dongshihao666** [comment] 2021-07-22 02:14
Hello, I also have this problem. When MacBook opens this plug-in, the CPU usage is soaring, and the cooling fan is running all the time. I have tried these methods. Is there a better solution at present

**Comment by dongshihao666** [comment] 2021-07-22 02:16
![Uploading image.png
![WechatIMG15](https://user-images.githubusercontent.com/29971202/126581853-2c4be59c-ff18-48d6-bfbb-db9cdbf11bec.jpeg)
…]()

**Comment by johnsoncodehk** [comment] 2021-07-22 02:19
@dongshihao666 I'm still looking for a way in volar. Have you try Turbo Boost Switcher?

**Comment by dongshihao666** [comment] 2021-07-22 02:27
I'm using
MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
2 GHz  Four core Intel Core i5
6 GB 3733 MHz LPDDR4X
Latest VSCode insiders
Latest Volar

**Comment by jinrongni** [comment] 2021-07-22 12:18
I have the same problem
when i use volar cup goes very high
![image](https://user-images.githubusercontent.com/41502851/126637828-b4f3ea4c-8c6e-49fe-b536-231f8bdef29f.png)

**Comment by xxSkyy** [comment] 2021-07-22 16:00
> > I removed this line, cleared cache ran debug and still same thing happens with cpu.
> 
> Can you provide profiling record (only document server)?

Sure, here
[CPU-20210722T175848.cpuprofile.zip](https://github.com/johnsoncodehk/volar/files/6863656/CPU-20210722T175848.cpuprofile.zip)

**Comment by johnsoncodehk** [comment] 2021-07-23 12:19
> Sure, here
> [CPU-20210722T175848.cpuprofile.zip](https://github.com/johnsoncodehk/volar/files/6863656/CPU-20210722T175848.cpuprofile.zip)

Thanks! It is clearer.

I made performance optimization in 0.26.7 based on your profiling, but I am not sure is it ease cpu usage. Please let me know the result if you try it.

**Comment by dongshihao666** [comment] 2021-07-26 01:43
When I update to 0.26.9, it still takes a lot of time to update the file name

**Comment by johnsoncodehk** [comment] 2021-07-26 02:29
> When I update to 0.26.9, it still takes a lot of time to update the file name

This is a different problem, has not optimized this yet, please open a new issue to track.

**Comment by Jaeiya** [comment] 2021-07-28 21:58
I can confirm there is quite a bit of performance lost when using Volar, even when just editing `.ts` files. To reproduce this, edit a template in a `.vue` file and then edit a `.ts` file anywhere else in the project and you can see how it prompts extra processes to fire. I'm not using a Macbook or laptop; I'm on a desktop computer with an Intel quad core.

Without Volar editing a `.ts` file.
![image](https://user-images.githubusercontent.com/2054218/127401300-28c44e94-3f32-4f2a-9ed5-5424a63ba587.png)


With Volar after editing a `.vue` file and then immediately editing a `.ts` file.
![image](https://user-images.githubusercontent.com/2054218/127401556-7e8a3f03-2334-41a6-b1c8-d32333a8887b.png)

It appears as though volar is running redundant processes unnecessarily, but that's a very ignorant assumption considering I don't know how the internals work.

**Comment by johnsoncodehk** [comment] 2021-07-29 03:06
@Jaeiya When you editing *.ts, volar need to update your opened vue document diagnostics because because there may have references.

Simply look at yours capture, when you editing ts script, TS server using 15% cpu and 401MB memory, volar using 24% cpu and 479MB memory for two TS language service (script and template), this is expected or even ideal.

If you close other vue document when you editing ts script, volar should be stop using cpu because no vue diagnostics need to update.

btw close this issue because already resolved the original performance profiling issue and get some users confirm in Discord, please open a new issue for other performance issues.

**Closed by johnsoncodehk** 2021-07-29 03:06 UTC
Labels: performance

**Comment by xxSkyy** [comment] 2021-07-30 01:53
After some time of testing I can confirm it's better. Thanks
