### ISSUE TITLE
Erroneous imports

### ISSUE THREAD

**Issue by oxk4r01** [johnsoncodehk/volar#671] opened 2021-11-05 13:43 UTC
The autocompletion for onMounted creates incorrect import:
import { onMounted } from 'vue/dist/vue.js'
which throws an error of 'not found module'.

I had to change it this way:
import { onMounted } from 'vue'

Am I missing something or is Volar's fault?

**Comment by johnsoncodehk** [comment] 2021-11-05 23:41
Duplicate of #532

**Closed by johnsoncodehk** 2021-11-05 23:41 UTC
