### ISSUE TITLE
v-for typing error when used with named slot

### ISSUE THREAD

**Issue by Shayan-To** [johnsoncodehk/volar#1010] opened 2022-03-06 03:21 UTC
This template code always gives me an error on the first line:

```
<template v-for="abc in ['str1', 'str2']">
    <slot :name="abc" />
</template>
```

Error message: `'abc' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

**Comment by johnsoncodehk** [comment] 2022-03-07 10:01
Hi @Shayan-To, I can't reproduce this problem, please reproduce complete reproducible vue code.

**Comment by Shayan-To** [comment] 2022-06-06 08:52
@johnsoncodehk 
I managed to create a minimal repro: https://gist.github.com/Shayan-To/0e258ea107942c74123ae53966179cb9

**Comment by johnsoncodehk** [comment] 2022-06-06 12:58
Duplicate of #1392

**Closed by johnsoncodehk** 2022-06-06 12:58 UTC
Labels: bug
