### ISSUE TITLE
Regression: TS casts/generics interpreted as JSX

### ISSUE THREAD

**Issue by jods4** [johnsoncodehk/volar#1805] opened 2022-09-02 16:02 UTC
Release 0.40.5 has not fixed all regressions from the previous 0.40 releases.
TS casts and sometimes generics are treated as JSX syntax in scripts with `lang=ts`, I recall this used to work.

![image](https://user-images.githubusercontent.com/3832820/188193911-57d1579d-ce12-4203-92b9-f4b7f6df3481.png)

**Comment by xiaoxiangmoe** [comment] 2022-09-03 17:25
duplicate of https://github.com/johnsoncodehk/volar/issues/1706

**Closed by xiaoxiangmoe** 2022-09-03 17:25 UTC
Labels: duplicate
