### ISSUE TITLE
Recursive closing of html tag when you paste a closing tab inside an opening tab

### ISSUE THREAD

**Issue by samwillis** [johnsoncodehk/volar#2247] opened 2022-12-22 18:49 UTC
If you (accidentally) paste a closing tag inside an opening tag, or before typing the closing `>`, Volar seems to recursively add the closing tag. It adds them repeatedly until you type something else.

The built in HTML extension does not seem have the same problem, and so I think it's Volar related.

See video below, I type `<div` then `ctrl+v` to paste the `</div>`. 

https://user-images.githubusercontent.com/31130/209205292-02b91e91-1432-4e38-b68a-d56d2b3a670b.mov

**Comment by johnsoncodehk** [comment] 2022-12-25 17:32
Duplicate of #2238

**Closed by johnsoncodehk** 2022-12-25 17:32 UTC
Labels: bug
