### ISSUE TITLE
Template type checking for vue not work after upgrade v1.0.14

### ISSUE THREAD

**Issue by oceans-pro** [johnsoncodehk/volar#2230] opened 2022-12-19 10:23 UTC
Vue doctor md show no errors.

**Comment by oceans-pro** [comment] 2022-12-19 10:25
Or how can i install another version?

**Comment by charliem17** [comment] 2022-12-19 19:16
v1.0.14 isn't working properly for me either.
E.g.
![image](https://user-images.githubusercontent.com/60069264/208501502-2ed218b3-7a31-4b84-9873-cf0228a1d465.png)

For builds to compile successfully right now you can install a previous version like so:
`yarn add -D vue-tsc@1.0.13`

You can also change the installed version of volar:
![image](https://user-images.githubusercontent.com/60069264/208502569-b4df0074-5ba5-4f3f-8450-3a3d25dab171.png)

**Comment by johnsoncodehk** [comment] 2022-12-19 23:05
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by johnsoncodehk** [comment] 2022-12-20 02:06
Duplicate of #2225

**Closed by johnsoncodehk** 2022-12-20 02:06 UTC
