### ISSUE TITLE
Angle bracket typecasts cause many unrelated errors (since 0.40.0)

### ISSUE THREAD

**Issue by qgates** [johnsoncodehk/volar#1744] opened 2022-08-20 16:58 UTC
Since Volar 0.40.0 I see hundreds of errors across all my .vue component files, a selection including:

Code images...

![image](https://user-images.githubusercontent.com/4213509/185757996-c386d669-ded1-45ed-9ee5-2c67024a14d5.png)
![image](https://user-images.githubusercontent.com/4213509/185758027-7fc0e558-7ca7-43f4-bb9d-7632928d0748.png)
![image](https://user-images.githubusercontent.com/4213509/185758107-694966b3-8c60-4e62-a7c0-b7737a62c6f3.png)
![image](https://user-images.githubusercontent.com/4213509/185758110-e7a94892-e8b4-4fa7-8371-9e4f74b16df3.png)

Corresponding errors...

![image](https://user-images.githubusercontent.com/4213509/185758147-634214d1-fb06-4ccb-bc05-bc8fd76647b1.png)

Have had to roll back to 0.39.5 for now, where everything is fine (ie. no errors).

**Comment by timcodesdotnet** [comment] 2022-08-21 09:14
I also have this issue, and found it may be related to syntax that uses angled brackets such as a typecast:

(<any>Difficulty)[difficulty]

Removing the angled brackets stopped a lot of these errors showing.

**Comment by qgates** [comment] 2022-08-21 13:25
Thanks @timcodesdotnet that seems to have narrowed down to a specific issue. Removing angle bracket typecasts does seem to ripple through and fix all the other (seemingly unrelated) issues.

That's a workaround but this is still an issue as angle bracket casts are supported in TS and haven't been deprecated afaik. Running vue-tsc shows no error with casts so Volar shouldn't either.

**Comment by timcodesdotnet** [comment] 2022-08-21 15:11
#1706 same issue

**Comment by Soviut** [comment] 2022-08-22 15:38
Installing any version before prior to `0.40.0` fixed the problem for me.

On the "Uninstall" button, click the dropdown arrow and choose "Install another version". Then choose `0.39.5`

![image](https://user-images.githubusercontent.com/226882/185961147-0f8986fc-495b-4048-a4a8-7e97e7d3c86f.png)

**Comment by xiaoxiangmoe** [comment] 2022-09-01 06:36
duplicate of https://github.com/johnsoncodehk/volar/issues/1706

**Closed by xiaoxiangmoe** 2022-09-01 06:36 UTC
Labels: duplicate
