### ISSUE TITLE
html tags turn green except <template></template>

### ISSUE THREAD

**Issue by leindfraust** [johnsoncodehk/volar#1166] opened 2022-04-11 09:38 UTC
HTML tags such as <section>, <div>, <p> etc., turn all to green instead of blue. I think the extension treats it like a component or something. The problem exists in version 0.34 up. I am currently using Volar 0.33.10 and all HTML tags are blue.

I am currently using Vue 3, with Options API and Composition API mixed together in the project.
I have attached below the screenshot comparison of 0.33.4 and 0.33.10 versions of Volar.

![0 33 4 VOLAR](https://user-images.githubusercontent.com/29818178/162710876-98437852-fdf3-4bbc-9df8-db48a7b922f9.png)
![0 33 10 VOLAR](https://user-images.githubusercontent.com/29818178/162710888-34509ab7-037b-4e81-aef6-46481c0ca4c7.png)

**Comment by yaegassy** [comment] 2022-04-11 09:40
Duplicate of #1158

**Closed by yaegassy** 2022-04-11 09:40 UTC
