### ISSUE TITLE
Type highlighting of node_modules is broken in takeover mode.

### ISSUE THREAD

**Issue by Tanimodori** [johnsoncodehk/volar#1641] opened 2022-07-27 02:12 UTC
## Step to reproduce

1. `git clone https://github.com/cawa-93/vite-electron-builder.git`
2. `cd vite-electron-builder`
3. `git checkout 1daa1d55c69423ba515045c1f4763c462a0914fd`
4. `npm i`
5. Open `.\packages\main\tests\unit.spec.ts`
6. Control click `vi.fn()` to jump to `vitest` lib (`node_modules\vitest\dist\index.d.ts`)
7. Inspect the return type `Mock<TArgs, R>`
8. The type highlight is correct in non-takeover mode as shown below. The "show definition" in right click menu (or F12) is working.

![JFSXboU7w7](https://user-images.githubusercontent.com/29478770/181145238-9a7241f6-0485-4d9f-b071-f267e04773a3.png)

9. Disable the built-in TS server and reload window to enter takeover mode.
10. Now the `Mock<TArgs, R>` shows no type highlight (though it showed "loading..." and then quickly disappears). The "show definition" does not work as shown below.

![rKdomhdPIr](https://user-images.githubusercontent.com/29478770/181145243-e7829f78-108a-4779-8541-8140a7329520.png)

## Note
* Other `node_modules` libs tested out not working too.
* `no tsconfig` is not affecting this bug. Include `unit.spec.ts` into nearest `tsconfig.json` does not help.
* Fix the `MaybeMocked` type in `unit.spec.ts` does not help. The correct fix for its type is `MockedObject` fyi.

## Environment

* Volar 0.39.1
* VSCode 1.69.2
* Windows 11

**Comment by johnsoncodehk** [comment] 2022-08-06 11:01
Can you reproduce this problem in v0.39.5?

**Comment by Tanimodori** [comment] 2022-08-06 15:12
@johnsoncodehk The bug seems identical to me with v0.39.5 and VSCode v1.70.0

**Comment by levidavidmurray** [comment] 2022-08-10 03:36
I'm using WSL, and was having issues with both Volar (takeover mode) and Vetur (Volar disabled) picking up my tsconfig for resolving absolute paths in `.vue` files. I then noticed—

> 3. Install the [Remote Development extension pack](https://aka.ms/vscode-remote/download/extension).

—on the [VSCode WSL installation guide](https://code.visualstudio.com/docs/remote/wsl#_installation).

I figured there were some issues with resolving paths due to VSCode running locally on Windows while the code exists in WSL land—so I was hopeful about this resolving the issue. It however, did not.

I then read about the `No tsconfig` message that I was getting at the bottom of VSCode, and how this can occur in the event of version mismatches[[1]](https://stackoverflow.com/a/38862621). And this was when I realized that the issue may now be due to the fact that I'm using [Nuxt](https://typescript.nuxtjs.org/) with Nuxt specific typescript support.

I couldn't figure out how to get Volar to work with this. I did try setting `typescript.tsdk`, but I figured it wouldn't work seeing as how I'm using takeover mode, so Volar itself is handling all the typescript stuff (?).

All my issues were resolved once I switched back to Vetur and reenabled built in **TypeScript and Javascript Language Features** after installing [Remote Development extension pack](https://aka.ms/vscode-remote/download/extension) and reopening my project from WSL (`code .`)

I'm not sure why it works with Vetur and not Volar. Maybe Volar is making more assumptions about the typescript sdk than Vetur is? Not sure. In any case, I hope this somewhat helps you guys (@johnsoncodehk) figure out these issues with Volar in Windows!

**Closed** 2022-08-27 13:25 UTC
Labels: bug
