### ISSUE TITLE
Package is empty in "v0.33.3" of "@volar/shared"

### ISSUE THREAD

**Issue by yaegassy** [johnsoncodehk/volar#1087] opened 2022-03-21 03:21 UTC
## [NG] @volar/shared@0.33.3

**Prepare**:

```
mkdir -p /tmp/check-volar-shared-new
cd /tmp/check-volar-shared-new
npm init -y
npm i -D @volar/shared@0.33.3
```

**Check**:

> out directory missing...

```
$ ls -1 node_modules/@volar/shared/
LICENSE
package.json
```

## [OK] @volar/shared@0.33.2

**Prepare**:

```
mkdir -p /tmp/check-volar-shared-old
cd /tmp/check-volar-shared-old
npm init -y
npm i -D @volar/shared@0.33.2
```

**Check**:

```
check-volar-shared-old$ ls -1 node_modules/@volar/shared/
LICENSE
out
package.json
```

**Comment by johnsoncodehk** [comment] 2022-03-21 03:24
Duplicate of #1086

Obviously the release process passed the test, I'm worried about future releases. 🤦‍♂️

**Closed by johnsoncodehk** 2022-03-21 03:24 UTC
