### ISSUE TITLE
`~~ as any` inside template seems to break the syntax highlighting colors

### ISSUE THREAD

**Issue by mesqueeb** [johnsoncodehk/volar#843] opened 2022-01-06 09:28 UTC
Here is an example:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/3253920/148360711-1dde7446-a65d-4960-9e32-d6b3869fb094.png">

**Comment by johnsoncodehk** [comment] 2022-01-08 18:09
Duplicate of #520

**Closed by johnsoncodehk** 2022-01-08 18:09 UTC
