### ISSUE TITLE
Typescript Template Intellisense error on Global injected properties

### ISSUE THREAD

**Issue by Brunnn** [johnsoncodehk/volar#1214] opened 2022-04-18 13:28 UTC
Volar Version: 0.34.7
Typescript Version: 4.6.3
Vue Version: 3.2.31
IDE: Visual Studio Code

#### Problem:
I have globlally injected properties/functions on my vue app that are avaliable to all components loaded into the application, but volar is complaining they do not exist. I've also typed them into `@types/global.d.ts` to make sure typescript compiler know they exist at a global scope. Here are my files and the Volar error.
The problem started after i updated volar from `0.34.5` to `0.34.6` and had to add `"jsx": "preserve"` to `tsconfig.json`, i tried to rollback  to the old version but it doesn't seem to work anymore...

`mycomponent.vue`
![image](https://user-images.githubusercontent.com/42523274/163814022-de4cbaa8-d9c1-42c8-8cab-5f46d21d2976.png)

`tsconfig.json`
![image](https://user-images.githubusercontent.com/42523274/163813249-10f2cb37-ef15-4f1f-bbc5-453ccd11b504.png)

`@types/global.d.ts`
![image](https://user-images.githubusercontent.com/42523274/163813468-e32f1450-03ea-440a-aba6-98edc4f1d858.png)

Injected properties: `main.ts`
![image](https://user-images.githubusercontent.com/42523274/163813590-57b3e630-ae5b-413f-b366-5f768dadfa7d.png)

**Comment by xiaoxiangmoe** [comment] 2022-04-19 06:59
see https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties

**Comment by johnsoncodehk** [comment] 2022-04-20 01:57
Duplicate of #1197

**Closed by johnsoncodehk** 2022-04-20 01:57 UTC
