### ISSUE TITLE
volar.action.splitEditors splits only in two

### ISSUE THREAD

**Issue by crystalfp** [johnsoncodehk/volar#1293] opened 2022-05-11 12:45 UTC
Despite the definition "Split \<script>,\<template>,\<style> Editors" `volar.action.splitEditors` creates only two windows:

- One with `template` collapsed
- One with `script` and `style` collapsed

I was expecting three views with only one section not collapsed each.
Wrong expectation or I'm missing something?

Thanks!\
mario

**Comment by johnsoncodehk** [comment] 2022-05-29 06:19
Duplicate of #755

**Closed by johnsoncodehk** 2022-05-29 06:19 UTC
