### ISSUE TITLE
Volar errors in latest version (0.40.4)

### ISSUE THREAD

**Issue by m-ghaoui** [johnsoncodehk/volar#1790] opened 2022-08-30 05:54 UTC
I get these errors:

```
> vue-tsc --noEmit -p tsconfig.vitest.json --composite false

- error TS17001: JSX elements cannot have multiple attributes with the same name.

4   <input class="custom-control-input" type="radio" :id="view.guid" :value="view.guid" v-model="selectedViewGuid"
                                                                                        ~~~~~~~

- error TS1196: Catch clause variable type annotation must be 'any' or 'unknown' if specified.

287     } catch (e: Error) {
                    ~~~~~


Found 2 errors in 2 files.
```

Reverting to `0.40.1` makes those errors go away.

**Comment by m-ghaoui** [comment] 2022-08-30 07:28
Oh wait, no sorry the first error is a mistake in my own code. You can ignore this. 

I removed `:value`

**Comment by m-ghaoui** [comment] 2022-08-30 07:43
The first error remains after reverting to `0.40.1`. This looks like a problem with another module.

**Comment by m-ghaoui** [comment] 2022-08-30 08:57
Ah upon further investigation I have found out that the errors are indeed from `0.40.4`

That's because I had this in my `package.json`:

```
"vue-tsc": "^0.40.1"
```

Which installs the lastest minor version, which is `0.40.4`.

I changed it to:

```
"vue-tsc": "0.40.1"
```

And now the errors are gone.

**Comment by johnsoncodehk** [comment] 2022-08-30 17:54
Duplicate of #1775

**Closed by johnsoncodehk** 2022-08-30 17:54 UTC
