### ISSUE TITLE
No intellisense for mts or file of which filename start with '.'

### ISSUE THREAD

**Issue by kingyue737** [johnsoncodehk/volar#1645] opened 2022-07-28 12:51 UTC
System: Windows

For example

`.postcssrc.ts` or `postcssrc.mts` does not have typecheck or intellisense, but `postcssrc.ts` does have.

**Comment by johnsoncodehk** [comment] 2022-09-21 21:37
Duplicate of #1147

**Closed by johnsoncodehk** 2022-09-21 21:37 UTC
