### ISSUE TITLE
整个项目箭头变红 

### ISSUE THREAD

**Issue by mingjiexiong** [johnsoncodehk/volar#1683] opened 2022-08-09 09:59 UTC
语法高亮显示错误 大小箭头都会变红  < >
![1.jpg](https://dmt.silkroadcg.com/morty/1.jpg)

**Comment by xiaoxiangmoe** [comment] 2022-08-09 10:38
Duplicate of https://github.com/johnsoncodehk/volar/issues/1677

**Closed by xiaoxiangmoe** 2022-08-09 10:38 UTC
