### ISSUE TITLE
Go to definition in VS Code doesn't working

### ISSUE THREAD

**Issue by Aetet** [johnsoncodehk/volar#2174] opened 2022-12-07 07:02 UTC
Go to the definition doesn't work for me.
![image](https://user-images.githubusercontent.com/3372058/206109291-3ec6e852-59f7-463b-8e5a-2e5bc850b98c.png)

I setup default project using 
```
npm create vue@3
```

with typescript support. 

I've got vs code 1.73 version. 
I use it with takeover mode
![image](https://user-images.githubusercontent.com/3372058/206110199-c712633d-a439-4843-b332-1bc74139d852.png)
I use 1.0.11 version of volar.

Imports are resolved and autocomplete correctly, but I cannot go to the definition. 
If I install vetur - it works correctly.

**Comment by johnsoncodehk** [comment] 2022-12-08 12:51
Duplicate of #2052

**Closed by johnsoncodehk** 2022-12-08 12:51 UTC
