### ISSUE TITLE
component intellisense for props is breaking

### ISSUE THREAD

**Issue by Half-A-Turnip** [johnsoncodehk/volar#490] opened 2021-09-14 15:07 UTC
it doesn't work in 0.27.19 and 0.27.20
![image](https://user-images.githubusercontent.com/24860389/133282082-b58a8ee7-1042-490e-bfc6-bc5017d61bb1.png)
![image](https://user-images.githubusercontent.com/24860389/133281993-a3f01ec9-8922-4381-996d-66400d2b33d1.png)
back to 0.27.18,it work well.
also i tried reproduce this problem in https://github.com/johnsoncodehk/volar-starter, but volar work  well .

**Comment by johnsoncodehk** [comment] 2021-09-15 16:48
Duplicate of #487

**Closed by johnsoncodehk** 2021-09-15 16:48 UTC

**Comment by Half-A-Turnip** [comment] 2021-09-16 01:00
@johnsoncodehk thanks
