### ISSUE TITLE
TS doesn't recognize usage when inside a template slot with a v-if

### ISSUE THREAD

**Issue by AlexandreBonaventure** [johnsoncodehk/volar#1374] opened 2022-06-01 12:35 UTC
Hello, 
We have an issue that we believe comes from Volar:

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/4596409/171403768-4fe5f6aa-da51-4d47-a1c0-524751057e9d.png">

## What's happening ? 
In VSCode, TS is throwing the following error:
`'MyComponent' is declared but its value is never read.`
despite MyComponent is used in the template below.

## What's expected ? 
It should recognize the usage of `MyComponent` and not throw any error.

## Repro
This is a valid component compiled by vue sfc compiler: 
https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cCBsYW5nPVwidHNcIj5cbmltcG9ydCB7IGggfSBmcm9tICd2dWUnXG5jb25zdCBQYXJlbnRDb21wb25lbnQgPSAocCwgeyBzbG90cyB9KSA9PiBoKCdkaXYnLCBzbG90cy5kZWZhdWx0KCkpO1xuY29uc3QgTXlDb21wb25lbnQgPSAoKSA9PiAnYnV0dG9uJztcblxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPFBhcmVudENvbXBvbmVudD5cbiAgICA8dGVtcGxhdGVcbiAgICAgIHYtaWY9XCJ0cnVlXCJcbiAgICAgICNkZWZhdWx0XG4gICAgPlxuICAgICAgdGVzdFxuICAgIDwvdGVtcGxhdGU+XG4gICAgPHRlbXBsYXRlXG4gICAgICB2LWVsc2VcbiAgICAgICNkZWZhdWx0XG4gICAgPlxuICAgICAgPE15Q29tcG9uZW50PjwvTXlDb21wb25lbnQ+XG4gICAgPC90ZW1wbGF0ZT5cbiAgPC9QYXJlbnRDb21wb25lbnQ+XG48L3RlbXBsYXRlPlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly91bnBrZy5jb20vQHZ1ZS9ydW50aW1lLWRvbUAzLjIuMzYvZGlzdC9ydW50aW1lLWRvbS5lc20tYnJvd3Nlci5qc1wiLFxuICAgIFwidnVlL3NlcnZlci1yZW5kZXJlclwiOiBcImh0dHBzOi8vdW5wa2cuY29tL0B2dWUvc2VydmVyLXJlbmRlcmVyQDMuMi4zNi9kaXN0L3NlcnZlci1yZW5kZXJlci5lc20tYnJvd3Nlci5qc1wiXG4gIH1cbn0ifQ==

NB: It doesn't matter if `v-if` condition is true or something else

<img width="1279" alt="Screen Shot 2022-06-01 at 8 30 45 AM" src="https://user-images.githubusercontent.com/4596409/171405277-50d73c0e-8212-42b6-8ccd-50b2d2e7b716.png">

## Info
VSCode: 1.67.2
Volar: 0.35.2
using workspace TS: 4.7.2

There is no guidelines for issue reporting so I hope the repro above should be enough for you to replicate the issue, otherwise feel free to ask some more information, I'll be glad to help and provide more logs/debug output

**Comment by johnsoncodehk** [comment] 2022-06-01 19:13
Hi @AlexandreBonaventure, this is intentional behavior because `() => string` is not valid JSX element type. You can specify `MyComponent` type to avoid this problem.

```ts
import type { FunctionalComponent } from 'vue'

const MyComponent: FunctionalComponent = () => 'button'
```

**Comment by AlexandreBonaventure** [comment] 2022-06-01 19:19
Thanks for replying @johnsoncodehk but I don't think that is really the issue. 
Because I have the error when importing `MyComponent`  from a .vue SFC file like:
`import MyComponent from './MyComponent.vue'` I just dumbed it down for the sake of providing a minimal reproduction.

Otherwise if I define the component as a regular object component I also get the same issue:
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/4596409/171484768-74942500-6772-4aa7-80c9-bd7e0ec39c41.png">
with 
```vue
const MyComponent = {
  setup () {
    return () => 'Hello';
  },
};
```

**Comment by johnsoncodehk** [comment] 2022-06-01 19:48
This is an other upstream issue, you can't use use expression in v-if / v-for + slot, please track #625.

**Comment by AlexandreBonaventure** [comment] 2022-06-01 19:54
Sounds good, feel free to close as a duplicate then

**Comment by johnsoncodehk** [comment] 2022-06-04 10:53
Duplicate of #625

**Closed by johnsoncodehk** 2022-06-04 10:53 UTC
Labels: question
