### ISSUE TITLE
Intellisense breaks when you import a component.

### ISSUE THREAD

**Issue by boid-com** [johnsoncodehk/volar#1766] opened 2022-08-26 03:08 UTC
##  Repro
```sh
yarn global add @quasar/cli
yarn create quasar
```
After creating the new quasar project and install dependencies, open `src/layouts/MainLayout.vue` in vscode with Volar `0.40.0+` and you will see that component data is `any` type in this file.

![image](https://user-images.githubusercontent.com/30223943/186809076-a09a83e9-85cd-4410-8b85-3be897387334.png)

Inspect the `src/components/EssentialLink.vue`and see it's working properly there. 

![image](https://user-images.githubusercontent.com/30223943/186809099-01ee6fcf-b48e-48bb-a496-db858a554065.png)

**In `MainLayout.vue` I found that if I removed the imported component then intellisense starts working again in that file.**

## Workaround
If you downgrade to `0.39.5` the problem is resolved. 

![image](https://user-images.githubusercontent.com/30223943/186809183-6db8d781-03c0-4ee3-9380-e7e8d86caf89.png)

## Note
It took me a few hours to track this issue down, and looking at previous issues in this repo, I see many comments about Intellisense breaking in edge cases. Maybe it would be good to add some more information to the docs around Intellisense debugging or common issues.

**Comment by johnsoncodehk** [comment] 2022-08-27 18:16
Duplicate of #1731

**Closed by johnsoncodehk** 2022-08-27 18:16 UTC
