### ISSUE TITLE
Syntax highlight and TS support doesn't work on the same HTML tag

### ISSUE THREAD

**Issue by yangdanping** [johnsoncodehk/volar#1328] opened 2022-05-22 10:22 UTC
![Snipaste_2022-05-22_18-21-10](https://user-images.githubusercontent.com/42269873/169690724-94a2d143-46cb-4669-91ab-79c8d4532e45.png)

**Comment by johnsoncodehk** [comment] 2022-05-22 10:28
Duplicate of #329

**Closed by johnsoncodehk** 2022-05-22 10:28 UTC
