### ISSUE TITLE
Significant lag and performance degradation in VSCode with Volar on

### ISSUE THREAD

**Issue by LittleSound** [johnsoncodehk/volar#1615] opened 2022-07-21 09:15 UTC
Issue Type: <b>Bug</b>

This issue is a recent one, perhaps related to the recent update?

Extension version: 0.38.9
VS Code version: Code 1.69.1 (b06ae3b2d2dbfe28bca3134cc6be65935cdfea6a, 2022-07-12T08:22:10.822Z)
OS version: Darwin arm64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 10, 10|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|--crash-reporter-id 2999e9bf-ef35-4154-bed3-74f44259cdaf|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdf:30486550
841h4636:30531698

```

</details>

**Comment by brys0** [comment] 2022-07-22 19:57
I can confirm this on my system as well. It's quite ridiculous waiting for insights take +5-10s and makes it impossible to get insights with any sort of speed.

**Comment by johnsoncodehk** [comment] 2022-07-23 12:05
- (If this is a recent issue) Which version did this issue start appearing?
- Do you have update typescript version? And what's is your typescript version? (See status bar when opened .vue file)
- Can this problem alleviate by setting `"javascript.suggest.autoImports": false` and `"typescript.suggest.autoImports": false` in VSCode?

**Comment by LittleSound** [comment] 2022-07-23 13:58
> * (If this is a recent issue) Which version did this issue start appearing?
> * Do you have update typescript version? And what's is your typescript version? (See status bar when opened .vue file)
> * Can this problem alleviate by setting `"javascript.suggest.autoImports": false` and `"typescript.suggest.autoImports": false` in VSCode?

Okay, I'll try to change these settings to test when I get back to work next week; I suspect the lag may be related to some of the `node` processes not being closed properly, which may take some time to occur with use, so it's not immediately reproducible.

**Comment by brys0** [comment] 2022-07-23 15:39
> * (If this is a recent issue) Which version did this issue start appearing?
> 
>     * Do you have update typescript version? And what's is your typescript version? (See status bar when opened .vue file)
> 
>     * Can this problem alleviate by setting `"javascript.suggest.autoImports": false` and `"typescript.suggest.autoImports": false` in VSCode?

If I had to pinpoint a release it would probably be the last 3, notably the worst being `0.39.0` 

Doing what you suggested plus the update you released yesterday and today seemed to have make it a bit quicker as well. As for my TS version I am running `4.7.3`

**Comment by brys0** [comment] 2022-07-23 16:56
So it seems when importing items it goes by each char rather than waiting for a word or something to appear. There's no delay. This could def cause issues with the performance.

**Comment by johnsoncodehk** [comment] 2022-07-23 17:44
@brys0 Maybe you're looking for `volar.diagnostics.delay` setting.

**Comment by johnsoncodehk** [comment] 2022-07-23 18:44
Please let me know if this version can alleviate the problem or not: [volar-0.39.2-alpha.1.vsix.zip](https://github.com/johnsoncodehk/volar/files/9174431/volar-0.39.2-alpha.1.vsix.zip)

**Comment by brys0** [comment] 2022-07-23 21:57
There appears to be no difference. Apologies for the wait.

**Comment by yanbowe** [comment] 2022-07-25 02:54
It's too slow to use

**Comment by brys0** [comment] 2022-07-25 03:11
I've removed every extension did a fresh install of vscode and just installed Volar and it's still just as slow. I have no idea what might be happening, based on what you said it could be related to certain node modules? Such as @vicons libraries causing Volar to scan the entire module which has upwards of 300+ vue files. Any advice for other people is I would consider somehow removing intelisense on large node modules like naive-ui and any icon library that directly uses `.vue` files.

**Comment by johnsoncodehk** [comment] 2022-07-25 04:46
@brys0 Could you provide profile record? (See #413)

**Comment by brys0** [comment] 2022-07-25 05:39
Yes. For debugging it used around 1.5gb of memory for the project (Is that alot?). Below is a zip of the entire cpu profile as well as a screenshot
[CPU-20220725T003725.zip](https://github.com/johnsoncodehk/volar/files/9178293/CPU-20220725T003725.zip)
![image](https://user-images.githubusercontent.com/35676267/180705755-e10519b0-e936-4df0-a2cf-63d81b5f937e.png)

**Comment by johnsoncodehk** [comment] 2022-07-25 06:29
> For debugging it used around 1.5gb of memory for the project

It depends on tsconfig count and node_modules size, if `volar.vueserver.useSecondServer` is enabled also uses more memory.

Please try [volar-0.39.2-alpha.2.vsix.zip](https://github.com/johnsoncodehk/volar/files/9178543/volar-0.39.2-alpha.2.vsix.zip), which try to cache stat(fileExists, directoryExists) result.

**Comment by hyhan** [comment] 2022-07-25 09:56
> Please try [volar-0.39.2-alpha.2.vsix.zip](https://github.com/johnsoncodehk/volar/files/9178543/volar-0.39.2-alpha.2.vsix.zip), which try to cache statSync(fileExists, directoryExists) result.

@johnsoncodehk  I just tried this version, which is much better than before, but there is still a little delay. Thank you for doing this.

**Comment by yanbowe** [comment] 2022-07-26 00:59
delete lang="ts" and prompt quickly

**Comment by yanbowe** [comment] 2022-07-28 03:28
> delete lang="ts" and prompt quickly

Version 0.39.2 is a little faster after setting lang="ts", but does the second prompt as if lang="ts" had not been set,

**Comment by JiangBingLong** [comment] 2022-07-29 02:14
再现个鬼， 你开个2000行左右的vue文件，插件提示直接歇菜，慢得一批~！换回vuter后，一切正常

**Comment by CharlotteFallices** [comment] 2022-07-29 14:13
> 再现个鬼， 你开个2000行左右的vue文件，插件提示直接歇菜，慢得一批~！换回vuter后，一切正常~！

Okay, this looks like your first issue, how about to take a look at what others did?
I think we all know disabling extension to avoid it couldn't help anything, so why not do something more meaningful, like try and see if something like this happens to you? :)

**Comment by johnsoncodehk** [comment] 2022-08-01 07:04
@brys0 Please let me know if this version have difference or not: [volar-0.39.5-alpha.1.vsix.zip](https://github.com/johnsoncodehk/volar/files/9231661/volar-0.39.5-alpha.1.vsix.zip)

**Comment by johnsoncodehk** [comment] 2022-08-01 09:43
I found that latest VSCode built-in TS v4.7.3 has performance issue with `defineComponent`, please also try install typescript v4.6.4 in workspace, and change VSCode tsdk to workspace TS version.

**Comment by brys0** [comment] 2022-08-01 12:52
I figured it may have been an issue with typescript trying to work with 2 different versions. Lovely you found the issue, thanks for taking your personal time to fix it. Much love 🤍

**Comment by onurusluca** [comment] 2022-08-02 01:03
I cal also confirm this. It suddenly got slow. I uninstalled VsCode and it's settings, cleaned cached, did general cleaning but still slow.

**Comment by johnsoncodehk** [comment] 2022-08-02 03:47
@onurusluca Thank for the information, is this problem begin in v0.38.6?

v0.38.5 ~ v0.38.6 only have one commit and it should be unrelated, so I'm out of ideas for now.
- https://github.com/johnsoncodehk/volar/commit/d8559b4c66c1c96e2ca2d4c98f3e2a901e39a067

I still can't reproduce this performance issue, I may need someone try with each commit after v0.38.5 and let me know which commit cause the problem.

**Comment by onurusluca** [comment] 2022-08-02 03:53
@johnsoncodehk Thanks a lot for the reply. Sorry for not specifying the problem. I chose v0.38.5 because the next update from that has a longer gap. 

I am testing all the versions now. It is taking a bit of a time. I will write here as soon as I am done testing. 

Also great job with the extension. I love Volar!

**Comment by onurusluca** [comment] 2022-08-02 04:08
@johnsoncodehk  Got it!

The problem starts from `v0.39.2`. 

Previous versions take 1 second or less to highlight a syntax problem but v0.39.2 and later takes 3 seconds or more.

I am more than happy to provide any details you need, just ask.

For now I am providing the default details:

VsCode: June 2022 (version 1.69)

Operating System:
	Microsoft Windows 10 Home 64-bit
CPU:
	Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
Motherboard:
	Alienware Alienware m17 R3 (U3E1)
RAM:
	32.00 GB Unknown form factor Unknown 2667MHz
GPU:
	Intel(R) UHD Graphics 1024 MB
	NVIDIA GeForce RTX 2070 Super 4095 MB
	
  System:
    OS: Windows 10 10.0.19044
    CPU: (16) x64 Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz
    Memory: 18.41 GB / 31.77 GB
  Binaries:
    Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (103.0.1264.77)
    Internet Explorer: 11.0.19041.1566

**Comment by johnsoncodehk** [comment] 2022-08-02 05:24
@onurusluca Thanks to confirm this, v0.39.2 is latter than this issue, it should be a different problem, could you open a new issue for this?

**Comment by onurusluca** [comment] 2022-08-02 05:53
@johnsoncodehk Hey. 
What do you mean by 'latter than this'? 
Alright, let me open one.

**Comment by onurusluca** [comment] 2022-08-02 06:07
Created a new issue on this: https://github.com/johnsoncodehk/volar/issues/1663

**Comment by johnsoncodehk** [comment] 2022-08-02 06:32
@onurusluca Sorry just typo, I mean v0.39.2 released later than this issue open.

**Comment by AlotOfBlahaj** [comment] 2022-08-04 04:27
same problem.



<html>
<body>


CPUs | AMD Ryzen 7 PRO 2700 Eight-Core Processor (16 x 3194)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.91GB (22.40GB free)
Process Argv | --crash-reporter-id 25c7f289-8e5d-4614-90ff-f88a062f3d82
Screen Reader | no
VM | 0%


</body>
</html>
volar 0.39.4

**Comment by Noxdor** [comment] 2022-08-11 18:09
Since a while, I am also having memory issues and finally I am quite sure it is coming from volar. Only difference is, I am not running volar in VS Code but in Neovim. Maybe that helps pinpoint it down. Neovim and volar are running in two separate processes, but still the nvim process is hogging more and more memory
![screenshot_memory_nvim](https://user-images.githubusercontent.com/64439978/184207582-f1553373-24ba-46c1-a782-6e6d8654ed45.png)

In this example it took 6.8GB of RAM. It can't be Neovim itself, because opening and using a Rust project for longer with its lsp, the memory stays constant and low, same with a pure js/ts project with eslint-lsp.

For me it is no instant lag or problem. The memory keeps growing and growing during the usage. Also, when I pause for a long time neither stop the application, the memory doesn't go down or increase but stays at one level. If I continue using it, the memory usage continues to go up. Seems like a memory leak to me?

Why the memory accumulates in the nvim process could be that the Neovim LSP is caching too much stuff from the volar lsp, as suggested by @Mehalter in AstroNvim/AstroNvim#797.

Hope this is helpful!

**Comment by mbadr2200** [comment] 2022-08-11 22:55
My Vs Code volar process keep increasing in ram usage then it`s restart and start again from the beginning 
My Ts version : 4.7.4
My volar version : v0.40.1
![image](https://user-images.githubusercontent.com/33435019/184255850-bcba41d4-8b44-48ca-92c7-8e2bdbbb4819.png)

**Comment by Noxdor** [comment] 2022-08-17 14:55
> Since a while, I am also having memory issues and finally I am quite sure it is coming from volar. Only difference is, I am not running volar in VS Code but in Neovim. Maybe that helps pinpoint it down. Neovim and volar are running in two separate processes, but still the nvim process is hogging more and more memory ![screenshot_memory_nvim](https://user-images.githubusercontent.com/64439978/184207582-f1553373-24ba-46c1-a782-6e6d8654ed45.png)
> 
> In this example it took 6.8GB of RAM. It can't be Neovim itself, because opening and using a Rust project for longer with its lsp, the memory stays constant and low, same with a pure js/ts project with eslint-lsp.
> 
> For me it is no instant lag or problem. The memory keeps growing and growing during the usage. Also, when I pause for a long time neither stop the application, the memory doesn't go down or increase but stays at one level. If I continue using it, the memory usage continues to go up. Seems like a memory leak to me?
> 
> Why the memory accumulates in the nvim process could be that the Neovim LSP is caching too much stuff from the volar lsp, as suggested by @mehalter in [AstroNvim/AstroNvim#797](https://github.com/AstroNvim/AstroNvim/issues/797).
> 
> Hope this is helpful!

For me it is resolves somehow. I just worked for a few hours on a vue project and no performance decrease, neither high memory usage.

**Comment by hariprasadiit** [comment] 2022-08-27 11:51
Had the same issue. I confirm that, disabling `Auto Import Component` showed significant performance improvement.

TS: 4.8.2
Volar: 0.40.1

**Comment by johnsoncodehk** [comment] 2022-08-27 21:08
Please open a new issue for memory usage. I have no reproduction that reproduces the problem so can't check it, I'd appreciate if someone provide a reproduction.

I made some performance optimizations in v0.40.2, please try the new version works for you or not.

**Comment by johnsoncodehk** [comment] 2022-08-28 18:04
@Noxdor I try mitigate memory leak by https://github.com/johnsoncodehk/volar/commit/7337d1c1fef9f51c70387e9352e7e4914800ea2d, please try v0.40.3.

**Comment by Noxdor** [comment] 2022-08-28 18:23
> @Noxdor I try mitigate memory leak by https://github.com/johnsoncodehk/volar/commit/7337d1c1fef9f51c70387e9352e7e4914800ea2d, please try v0.40.3.

Thanks for the reply! As I wrote above, for me the issue was already resolved and I am right now on 0.40.1. So it can't have been the changes in 0.40.3. Unfortunately I can't pinpoint it any more precisely.

**Comment by C1oudust** [comment] 2022-08-30 05:51
I am using the latest version 0.40.4,but it also slowly and cost lots of memory

**Comment by johnsoncodehk** [comment] 2022-09-05 11:03
For peoples who still has performance issue with latest version, you can try:

1. Disable `javascript.suggest.autoImports` and `typescript.suggest.autoImports` in workspace settings.
2. Enable `volar.vueserver.useSecondServer` in workspace VSCode settings.
3. Delete node_modules and check did problems gone or not. If so, delete package.json dependencies / devDependencies one by one to see which package lead to problems. (If this is the reason, the package usually has lot of .d.ts files.)
4. (Advanced) Investigate (Performance Tracing)[https://github.com/microsoft/TypeScript-wiki/blob/main/Performance-Tracing.md] use vue-tsc.

Close this issue because do not have anymore helpful information, if you can confirm the performance from plugin, please open a new issue with append repro case or [profiling record](#413).

**Closed by johnsoncodehk** 2022-09-05 11:03 UTC
Labels: need more info / repro

**Comment by Miguel-Bento-Github** [comment] 2022-11-07 11:14
Removing 
```
"editor.codeActionsOnSave": ["source.organizeImports"]
```

from my global settings, did the trick. Hope it helps.

**Comment by lachlanmcdonald** [comment] 2023-04-06 21:32
It is disappointing that this issue was closed as, being the only development tooling for VSCode, the continued performance issues of Volar effectively make VSCode + Vue an incompatible pairing.

**Comment by johnsoncodehk** [comment] 2023-04-15 02:07
The current version of Volar does not have much overhead, but its performance is limited by TypeScript. If your project itself is a huge TypeScript project, TypeScript LanguageService will analyze it slowly anyway. If you can provide a repro case, I might be able to help find out the performance hotspots in your project. It may come from a certain dependency, or some recursive type. At least the performance problems I have checked recently are all from the project itself.

If you need help please provide a repro case and open a new issue, I'll find time to check it, otherwise I can't help, I'm not a magician.

**Comment by Juraj-Masiar** [comment] 2023-08-16 09:09
WebStorm now also uses Volar and it takes almost 9 seconds for the error to disappear.
Deleting node_modules and package-lock.json didn't fixed the issue.

https://github.com/vuejs/language-tools/assets/6358971/e8bb548b-2cc5-44f5-b3bd-37792adfc794

What helps is switching Volar with the TypeScript Service.
I could try to create some repository where you could reproduce it, but I don't want to share it publicly here. Also I can't guarantee it will reproduce in VSCode.

**Comment by so1ve** [comment] 2023-08-16 10:41
You may open a new issue, and then provide some logs. Commenting here won't solve this issue...

**Comment by vzhikness** [comment] 2024-04-03 09:59
I had a similar issue: very slow snippet suggestions. Setting `"vue.server.hybridMode": true` in settings resolved my issue.

**Comment by kshksdrt** [comment] 2024-09-24 02:23
> For peoples who still has performance issue with latest version, you can try:
> 
> 1. Disable `javascript.suggest.autoImports` and `typescript.suggest.autoImports` in workspace settings.
> 2. Try enable `volar.vueserver.useSecondServer` in workspace settings for better performance, or disable it for less memory usage.
> 3. Delete node_modules and check did problems gone or not. If yes, delete package.json dependencies / devDependencies one by one to see which package lead to problems. (If this is the reason, the package usually has lot of .d.ts files.)
> 4. Try [Takeover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode).
> 5. (Advanced) Investigate (Performance Tracing)[https://github.com/microsoft/TypeScript-wiki/blob/main/Performance-Tracing.md] use vue-tsc.
> 
> Close this issue because do not have anymore helpful information, if you can confirm the performance from plugin, please open a new issue with append repro case or [profiling record](#413).

How can I set these settings in a neovim/nvim-lspconfig?

[Here](https://github.com/kshksdrt/nvim) is my Nvim config
