### ISSUE TITLE
Generic props: ESLint warning that type was used before it was defined + wrong syntax highlighting

### ISSUE THREAD

**Issue by 0x00A1FA** [johnsoncodehk/volar#3149] opened 2023-05-09 11:48 UTC
Hello Sir,

Take into consideration the following code:
```vue
<script setup lang="ts" generic="TModel extends App.Models.Model">
type RequiredModel = Required<TModel>

const props = defineProps<
	{
		modelValue: TModel | TModel[]
		items: TModel[]
		itemTitle: keyof RequiredModel extends infer TKeyofModel
			? TKeyofModel extends keyof RequiredModel
				? TKeyofModel extends keyof any
					? RequiredModel[TKeyofModel] extends string | number
						? TKeyofModel
						: never
					: never
				: never
			: never
	} & App.Helpers.Components.Props<'VChipGroup'>
>()
```

![image](https://github.com/vuejs/language-tools/assets/110613761/81526d8d-9830-4ebc-9f5e-c4efc3f8cc62)

`App.Models.Model` is an union type with all the data types in my app (basically an union of interfaces).

As you can see, `TKeyofModel` is erroring. The error is:
```log
'TKeyofModel' was used before it was defined.eslint[no-use-before-define](https://eslint.org/docs/rules/no-use-before-define)
```

Also, the syntax highlighting is wrong (notice `keyof RequiredModel extends infer TKeyofModel`).

Is there a problem with ESLint or something else?

Thanks!

**Comment by so1ve** [comment] 2023-06-17 23:45
It seemed this issue has been fixed in eslint-plugin-vue

**Comment by so1ve** [comment] 2023-06-26 10:14
Closed because this issue has been fixed in eslint-plugin-vue.

**Comment by so1ve** [comment] 2023-06-26 10:15
Oops, I'm not sure if the syntax highlighting issue still exists.

**Comment by johnsoncodehk** [comment] 2024-05-13 17:06
The syntax highlighting issue can be reproduced in the .ts file using the same code.

**Closed as not planned by johnsoncodehk** 2024-05-13 17:06 UTC
Labels: upstream
