### ISSUE TITLE
Auto Formatting introduces spaces in tailwind class, breaks Nuxt 3 App

### ISSUE THREAD

**Issue by shba007** [johnsoncodehk/volar#1727] opened 2022-08-17 15:46 UTC
Auto Formatting a class in style tag causes Nuxt 3 App to break

Before Formatting

![image](https://user-images.githubusercontent.com/48382105/185183283-b9ce851a-1976-492b-ac52-10b00e48c868.png)

After Formatting

![image](https://user-images.githubusercontent.com/48382105/185183452-29112be7-c0ad-4d2c-a81a-71039ea0dac9.png)

Spaces are introduced in RGBA which breaks the customs tailwind class

**Comment by johnsoncodehk** [comment] 2022-09-21 22:49
Duplicate of #1448

**Closed by johnsoncodehk** 2022-09-21 22:49 UTC
