### ISSUE TITLE
Problems loading reference "johnsoncodehk.volar-0.30.5\schemas\tsconfig.schema.json"

### ISSUE THREAD

**Issue by thisVioletHydra** [johnsoncodehk/volar#873] opened 2022-01-18 15:52 UTC
```q
Problems loading reference 'file:///c%3A/Users/Mirajana/.vscode/extensions/johnsoncodehk.volar-0.30.5/schemas/tsconfig.schema.json': Unable to load schema from 'c:\Users\Mirajana\.vscode\extensions\johnsoncodehk.volar-0.30.5\schemas\tsconfig.schema.json': ENOENT: no such file or directory, open 'c:\Users\Mirajana\.vscode\extensions\johnsoncodehk.volar-0.30.5\schemas\tsconfig.schema.json'.
```
my hard disk 
![image](https://user-images.githubusercontent.com/11839238/149971470-c3493e32-42ff-4bd6-8fff-31cc4bd77db0.png)

reinstall extension not helped me =\

**Comment by yaegassy** [comment] 2022-01-18 16:01
Duplicate of #869

**Closed** 2022-01-18 16:37 UTC
Labels: duplicate
