### ISSUE TITLE
Wrong syntax color with angle brackets

### ISSUE THREAD

**Issue by kingyue737** [johnsoncodehk/volar#1678] opened 2022-08-07 07:47 UTC
Brackets in comparison and arrow function become red.

![image](https://user-images.githubusercontent.com/40021217/183280750-e5b921c4-bdef-4280-80dd-f64b7fc04799.png)

![image](https://user-images.githubusercontent.com/40021217/183280809-f7e94121-40ac-44dd-b7e9-f25de76f804a.png)

v0.39.5 and VSCode v1.70.0

**Comment by Shinigami92** [comment] 2022-08-07 08:01
I am affected by this as well
Until now I just didn't reported it, because I just assumes it will be fixed anyway :slightly_smiling_face:

**Comment by yuyinws** [comment] 2022-08-08 13:16
Same here.
By the way, It's only appear when set `lang=ts` in <script>

**Comment by johnsoncodehk** [comment] 2022-08-08 14:19
Duplicate of #1677

**Closed by johnsoncodehk** 2022-08-08 14:19 UTC
Labels: bug
