### ISSUE TITLE
Syntax highlighting seems different from the previous version

### ISSUE THREAD

**Issue by misbahansori** [johnsoncodehk/volar#1158] opened 2022-04-10 10:51 UTC
Not sure if this is a bug or a desired interface, the newer version looks odd

Theme: Andromeda Bordered

The old version : 0.33.10
<img width="853" alt="Screen Shot 2022-04-10 at 17 46 10" src="https://user-images.githubusercontent.com/20674057/162614565-8968c406-4669-4540-aab2-8a595e6a27ea.png">

The new version : 0.34.2
<img width="920" alt="Screen Shot 2022-04-10 at 17 46 24" src="https://user-images.githubusercontent.com/20674057/162614567-6af8588e-5d9a-4926-986f-f9c062820660.png">

**Comment by joepbuhre** [comment] 2022-04-10 13:10
Agreed. With my every component is interpreted as a Vue Component > It is green instead of the usual blue with me. Very annoying so I downgraded to 0.33

**Comment by johnsoncodehk** [comment] 2022-04-10 13:25
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by braincomb** [comment] 2022-04-11 05:38
Not only that but the auto-formatter seems to be behaving oddly, leaving the indention of tags broken.
After downgrading to v0.33.10 the issue is not  there.

**Comment by johnsoncodehk** [comment] 2022-04-11 05:48
@braincomb html formatting issue should be fixed in 0.34.4.

**Comment by mxp131011** [comment] 2022-04-11 06:30
I have the same problem

**Comment by Lovercz** [comment] 2022-04-11 06:31
标签的配色，我需要做些什么才能改回去 ？降级？

**Comment by chrislee973** [comment] 2022-04-11 06:58
I'm having syntax highlighting issues too on 0.34.4. HTML tags and component names are all colored green instead of the usual blue for html and green for components. To reproduce, create a project with `npm init vue@latest` and choose "No" for all the options.

**Comment by MaxIV20** [comment] 2022-04-11 07:37
I confirm that html tags are highlighted in green as components. The backlight is incorrect in the project on vue 3 and nuxt 2.

**Closed** 2022-04-11 07:56 UTC
Labels: bug

**Comment by LoiLock** [comment] 2022-04-11 10:08
So why is this issue closed? Given that several people are still having this issue on the latest version?

**Comment by yaegassy** [comment] 2022-04-11 10:09
@LoiLock This fix will be reflected in the next version (v0.34.5). There may be other fixes or adjustments, so until they are released, please downgrade to a version that is not problematic and use it.

**Comment by yaegassy** [comment] 2022-04-11 10:19
This is the **next** release version of the volar extension (`v0.34.5`). I built and tested the new version in my environment.

<img width="815" alt="volar-extension-next-js-proj" src="https://user-images.githubusercontent.com/188642/162720023-780f11bb-b84c-4cd6-ab17-8095eda717c2.png">

The syntax problem in the case of JavaScript projects seems to be fixed.

**Comment by yaegassy** [comment] 2022-04-11 10:27
It appears that a new version has been released. Try it!

<img width="747" alt="volar-v0-34-5" src="https://user-images.githubusercontent.com/188642/162721653-f36a943a-60de-4a9a-88ba-a95531d348fb.png">

**Comment by LoiLock** [comment] 2022-04-12 09:32
Yup, seems to be fixed now! Thanks a lot!

**Comment by cmcleese** [comment] 2022-11-02 14:14
Once I update to Volar v1.x.x or greater, the syntax highlighting seems to be lost for all components.
They are all green except for HTML tag

![image](https://user-images.githubusercontent.com/2061466/199512222-ff7e69a1-5ae2-429e-9d27-d284a325ee29.png)

**Comment by rayasabari** [comment] 2022-11-09 03:46
I fix the component highlight issue with the Vue Voler extentions Pack

<img width="567" alt="image" src="https://user-images.githubusercontent.com/57746279/200733239-0de34194-2364-4294-bfa9-92118941be0f.png">

**Comment by cmcleese** [comment] 2022-11-09 07:33
I already had basically all the extensions listed in there, regardless I tried it and it did not solve the issue for me. Still no highlighting.
