### ISSUE TITLE
Type error for intrinsic attribute

### ISSUE THREAD

**Issue by NoahStahl** [johnsoncodehk/volar#1387] opened 2022-06-03 13:58 UTC
After upgrading from `0.35.2` to `0.36.0`, Volar now incorrectly complains about the spellcheck attribute on this component:

![image](https://user-images.githubusercontent.com/7528994/171866643-743b455a-e75d-4361-bcf7-793c399e5231.png)

(from https://headlessui.dev/vue/combobox)

Reverting to previous extension version resolves the error. Message:

```
Type '{ ref: string; class: string; spellcheck: string; placeholder: string; displayValue: (option?: unknown) => string; "display-value": (option?: unknown) => string; }' is not assignable to type 'IntrinsicAttributes & Partial<{ as: string | Record<string, any>; unmount: boolean; static: boolean; }> & Omit<Readonly<ExtractPropTypes<{ as: { type: (ObjectConstructor | StringConstructor)[]; default: string; }; static: { ...; }; unmount: { ...; }; displayValue: { ...; }; }>> & { ...; } & VNodeProps & AllowedCompo...'.
  Property 'spellcheck' does not exist on type 'IntrinsicAttributes & Partial<{ as: string | Record<string, any>; unmount: boolean; static: boolean; }> & Omit<Readonly<ExtractPropTypes<{ as: { type: (ObjectConstructor | StringConstructor)[]; default: string; }; static: { ...; }; unmount: { ...; }; displayValue: { ...; }; }>> & { ...; } & VNodeProps & AllowedCompo...'.
```

**Comment by boris-sbizzera** [comment] 2022-06-03 15:03
Noticed the same error in same configuration !

**Comment by D4RKAR117** [comment] 2022-06-03 15:23
Same Error here, maybe related with #1383 ?, even `id` as attr in custom components stopped working.

**Comment by weicheng2138** [comment] 2022-06-03 15:36
Same problem as above with svg attrs
<img width="1004" alt="截圖 2022-06-03 23 20 29" src="https://user-images.githubusercontent.com/13548635/171884549-e5e4ff45-58e6-4222-8aaa-18ed02dce34b.png">
```
Type '{ strokeLinecap: string; "stroke-linecap": "round"; strokeLinejoin: string; "stroke-linejoin": "round"; d: string; }' is not assignable to type 'ElementAttrs<SVGAttributes>'.
  Property 'strokeLinecap' does not exist on type 'ElementAttrs<SVGAttributes>'. Did you mean ''stroke-linecap''?
```

**Temperary that I switch back to 0.35.2 to solve the problem.** Hopeful it can be solved soon.

**Comment by myknbani** [comment] 2022-06-03 18:04
I can confirm I can confirm https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1145361472 works. It actually mimics React+TS type safety, where unknown props are red.

**Comment by braincomb** [comment] 2022-06-03 18:51
Same issue! Reverting back until fixed.

**Comment by OjGrooms** [comment] 2022-06-03 19:13
You'll have to update your `package.json` to use `vue-tsc` with a version older. I rolled back to `^0.34.2` from `^0.34.7`, fetched my depends, and restarted vscode. Everything appears to be happy again. 
```
// package.json

"devDependencies": {
    "vue-tsc": "^0.34.2"
 }
 ```

**Comment by lucas-labs** [comment] 2022-06-04 00:20
I'm getting the same error shown by @weicheng2138 on any kebab-case html attribute. For example those from ARIA:

```xml
<template>
    <input aria-describedby="emailHelp">
    <p id="emailHelp">aria help...</p>
</template>
```

Error:
```console
Type '{ ariaDescribedby: string; "aria-describedby": string; }' is not assignable to type 'ElementAttrs<InputHTMLAttributes>'.
  Property 'ariaDescribedby' does not exist on type 'ElementAttrs<InputHTMLAttributes>'. Did you mean ''aria-describedby''?ts(2322)
```

![image](https://user-images.githubusercontent.com/12949236/171968926-74e83224-8169-4da3-b200-9b7528d3a1f3.png)

**Comment by myknbani** [comment] 2022-06-04 01:19
Comment on https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1145361472 works

**Comment by johnsoncodehk** [comment] 2022-06-04 10:49
Duplicate of #1383

**Closed by johnsoncodehk** 2022-06-04 10:49 UTC
