### ISSUE TITLE
Couldn't start client Volar - Document

### ISSUE THREAD

**Issue by soulsam480** [johnsoncodehk/volar#7] opened 2020-10-27 02:44 UTC
Hii,
This is a great project. Vue 3 is good with Ts but it could be better. I installed this extension but it throws some errors.

- Couldn't start client Volar - Document
- A request has failed. See the output for more information.
- Request initialize failed with message: host.useCaseSensitiveFileNames is not a function

Hope you'll look into these errors. Thank you.

**Comment by johnsoncodehk** [comment] 2020-10-27 02:50
Will check it out! What is your operating system?
It will be useful if you can provide a reproducible project

**Comment by soulsam480** [comment] 2020-10-27 06:58
yeah sure.

OS: Windows 10 Home
Vue: 3.0.0
Vue-router: 4.0.0-0
Vuex: 4.0.0-0
Vue-CLI: 4.x

**Comment by johnsoncodehk** [comment] 2020-10-27 13:49
After many attempts I cannot reproduce the problem, I need more help...
1. What is your VSCode version?
2. Will the error still occur when you disable all other extensions?
3. Can you reproduce the problem in this project?
https://github.com/vuejs/vue-next-webpack-preview

**Comment by soulsam480** [comment] 2020-10-27 14:52
1. Vs code details:
Version: 1.50.1 (user setup)
Commit: d2e414d9e4239a252d1ab117bd7067f125afd80a
Date: 2020-10-13T15:06:15.712Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

2. No I haven't tested while all extensions disabled. Will check and let you know.
3. I will try to reproduce the errors

Here is a screenshot of the errors I got in vscode
![Screenshot (556)](https://user-images.githubusercontent.com/35460828/97318563-026e3180-1892-11eb-871f-d629ea4946cd.png)

**Comment by johnsoncodehk** [comment] 2020-10-28 01:12
This is where I think the problem may occur, but there is not enough information to check further:
https://github.com/microsoft/TypeScript/blob/292b778204ad2ce071f12ab872243b7e404aad90/src/services/services.ts#L1216

**Comment by soulsam480** [comment] 2020-10-28 03:29
> After many attempts I cannot reproduce the problem, I need more help...
> 
> 1. What is your VSCode version?
> 2. Will the error still occur when you disable all other extensions?
> 3. Can you reproduce the problem in this project?
>    https://github.com/vuejs/vue-next-webpack-preview

Hey I just checked with all extensions disabled. But it didn't work and the same errors occurred.

**Comment by johnsoncodehk** [comment] 2020-10-28 07:23
Thank you for your work~ please let me know if you tried point 3.
In addition, do you use typescript plugin?

**Comment by soulsam480** [comment] 2020-10-29 03:26
> Thank you for your work~ please let me know if you tried point 3.
> In addition, do you use typescript plugin?

Yes I use Vue cli-plugin-typescript

Here is the error from vscode output after volar crashes

internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'entities/lib/maps/entities.json'
Require stack:
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js:7:39)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js'
  ]
}
[Info  - 8:49:25 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'entities/lib/maps/entities.json'
Require stack:
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js:7:39)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js'
  ]
}
[Info  - 8:49:26 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'entities/lib/maps/entities.json'
Require stack:
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js:7:39)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js'
  ]
}
[Info  - 8:49:27 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'entities/lib/maps/entities.json'
Require stack:
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js:7:39)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js'
  ]
}
[Info  - 8:49:28 AM] Connection to server got closed. Server will restart.
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'entities/lib/maps/entities.json'
Require stack:
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js
- /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js:7:39)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js',
    '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js'
  ]
}
[Error - 8:49:29 AM] Connection to server got closed. Server will not be restarted.

**Comment by johnsoncodehk** [comment] 2020-10-29 10:21
> > Thank you for your work~ please let me know if you tried point 3.
> > In addition, do you use typescript plugin?
> 
> Yes I use Vue cli-plugin-typescript
> 
> Here is the error from vscode output after volar crashes
> 
> internal/modules/cjs/loader.js:796
> throw err;
> ^
> 
> Error: Cannot find module 'entities/lib/maps/entities.json'
> Require stack:
> 
> * /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js
> * /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js
> * /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js
> * /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js
> * /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js
> * /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js
> * /home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
>   at Function.Module._load (internal/modules/cjs/loader.js:686:27)
>   at Module.require (internal/modules/cjs/loader.js:848:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js:7:39)
>   at Module._compile (internal/modules/cjs/loader.js:955:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
>   at Module.load (internal/modules/cjs/loader.js:811:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:723:14)
>   at Module.require (internal/modules/cjs/loader.js:848:19) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Tokenizer.js',
>   '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/Parser.js',
>   '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/htmlparser2/lib/index.js',
>   '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/pug/out/index.js',
>   '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/node_modules/@volar/vscode-vue-languageservice/out/index.js',
>   '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/languageServiceHost.js',
>   '/home/sooulsam480/.vscode-server/extensions/johnsoncodehk.volar-0.14.5/packages/server/out/server.js'
>   ]
>   }
>   [Info  - 8:49:25 AM] Connection to server got closed. Server will restart.
>   internal/modules/cjs/loader.js:796
>   throw err;
>   ^
> 
> This error comes 5 times before volar stops working. I thought this was some problem with the environment i.e. WSL Ubuntu. But I tried this on windows 10 and this also throws error.

This is a new bug in 0.14.5... It has been fixed in 0.14.6

**Comment by johnsoncodehk** [comment] 2020-10-30 04:18
@soulsam480 I finally found the reason, please try 0.14.8 and let me know if it has been resolved.

**Comment by soulsam480** [comment] 2020-10-30 04:32
@johnsoncodehk hii I just tested it. It didn't crash. That awesome.

Is there any way to check that if its working or not. I mean to check if this is running or not. 

An also should I disable vetur to see the features of volar in action?

**Comment by johnsoncodehk** [comment] 2020-10-30 04:39
Yes, you need to turn off vetur and reload vscode, and your project needs to have tsconfig.json.
You can click <template> to try to execute `Convert to Pug`, if it succeeds, it means volar is working.

**Comment by soulsam480** [comment] 2020-10-30 04:47
Sure Man. Thanks again for this amazing project and all those help. ✌🏼🤯

**Closed** 2020-10-30 04:47 UTC
Labels: help wanted
