### ISSUE TITLE
new bug

### ISSUE THREAD

**Issue by zwfengineer** [johnsoncodehk/volar#1930] opened 2022-10-05 10:46 UTC
when i use Vue Language Features (Volar) plugin,vscode will have two identical code hints
should be one code hints

![image](https://user-images.githubusercontent.com/33892516/194042812-0e33e4bb-794a-4582-a450-c3ebd1738b12.png)

**Comment by zwfengineer** [comment] 2022-10-05 10:57
vscode version August 2022 (version 1.71)

**Comment by zwfengineer** [comment] 2022-10-05 10:58
volar version v0.40.13

**Comment by johnsoncodehk** [comment] 2022-10-08 15:31
Duplicate of #1852

**Closed by johnsoncodehk** 2022-10-08 15:31 UTC
