### ISSUE TITLE
“__VLS_61” can't be used by JSX components

### ISSUE THREAD

**Issue by PhoenixJane** [johnsoncodehk/volar#1267] opened 2022-05-06 06:53 UTC
![image](https://user-images.githubusercontent.com/76688284/167080880-937d6cda-2169-4ff5-8733-7c21e7cda8cb.png)
When I use v0.27.25, it's running well.this new version-0.34 can't back old version.The red warning problem is perplexing me now.

**Comment by PhoenixJane** [comment] 2022-05-06 06:59
![image](https://user-images.githubusercontent.com/76688284/167082376-8a7ec997-6742-4bed-ab70-7c3e110b566c.png)
I have imported it correctly.

**Comment by johnsoncodehk** [comment] 2022-05-06 07:11
Hi @PhoenixJane, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? If it can't please provide a repro case.

**Comment by PhoenixJane** [comment] 2022-05-06 07:18
> Hi @PhoenixJane, can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter? If it can't please provide a repro case.

`"vueCompilerOptions": {
    "experimentalDisableTemplateSupport": true
  },`

I have configured it in 'tsconfig.json'.'volar-starter' can resolve this problem?

**Comment by johnsoncodehk** [comment] 2022-06-16 03:16
Duplicate of #1405

**Closed by johnsoncodehk** 2022-06-16 03:16 UTC
Labels: need more info / repro
