### ISSUE TITLE
v-on directives causes error on typescript

### ISSUE THREAD

**Issue by jerryc05** [johnsoncodehk/volar#2024] opened 2022-10-15 20:17 UTC
Not sure if this is related to volar but I recently came across this problem.

I haven't coded in Vue for a few months, but I am pretty sure these errors did not appear the last time I use volar (~ a few months ago).

![image](https://user-images.githubusercontent.com/8305074/196005835-ba0bc660-c001-4884-8f3a-1ccdcc624344.png)

```
$ npx tsc -v
Version 4.8.4
```
`vue lang features v1.0.8`
`ts vue plugin v1.0.8`

BTW, can't reproduce on stackblitz, but my `tsconfig.json` is identical to the `vue-ts` on vitejs.dev

**Comment by johnsoncodehk** [comment] 2022-10-15 20:21
Duplicate of #1985

**Closed by johnsoncodehk** 2022-10-15 20:21 UTC
