### ISSUE TITLE
Bug: VSCode Wrong highlight in `<script>` section by ending with typescript `type` declaration without semicolon

### ISSUE THREAD

**Issue by MaikoTan** [johnsoncodehk/volar#1666] opened 2022-08-03 01:02 UTC
## Summary

As the title says, TypeScript and Vite supports no-semicolon style natively, but the highlight broken on this case, including every section after that.

See the screenshot below.

## Screenshot

![image](https://user-images.githubusercontent.com/19927330/182501647-6d84a06a-d127-4da7-bca0-76aff6643300.png)

#### VSCode
```
Version: 1.70.0-insider
Commit: e9bda7aa4ff76648cfccc1a7bde465443803da71
Date: 2022-08-02T16:59:59.451Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Linux x64 5.15.0-43-generic snap
```

#### Volar
```
Volar: v0.39.4 (takeover mode)
```

**Comment by johnsoncodehk** [comment] 2022-08-26 11:27
Duplicate of #986

**Closed by johnsoncodehk** 2022-08-26 11:27 UTC
