### ISSUE TITLE
Volar let Better Comments lost highlighted

### ISSUE THREAD

**Issue by lengyibai** [johnsoncodehk/volar#1446] opened 2022-06-13 06:40 UTC
Volar enabled before
![image](https://user-images.githubusercontent.com/74140255/173293436-f9791c45-d7ab-41f7-94c4-58b8c8e18f29.png)

After the commissioning of the volar
![image](https://user-images.githubusercontent.com/74140255/173293487-ab1d5a35-b846-4944-85d8-2d36264bd417.png)

Enabled, you can see highlighted effective within the js file, but in the vue file fail

**Comment by johnsoncodehk** [comment] 2022-06-13 06:42
Duplicate of #1179

**Closed by johnsoncodehk** 2022-06-13 06:42 UTC
