### ISSUE TITLE
Use annotations to ignore check failures

### ISSUE THREAD

**Issue by wushijiang13** [johnsoncodehk/volar#133] opened 2021-04-10 05:45 UTC
import {ElButton} from 'element-plus';
import {app} from '../vue/app'

// @vue-ignore
app.component(ElButton.name,ElButton);

carried out:
vue-tsc --noEmit && vite build

Get the error:

src/config/lazy_ui/element_lazy.ts:5:15 - error TS1131: Property or signature expected.

5 app.component(ElButton.name,ElButton);

Desired result :
not error

**Comment by wushijiang13** [comment] 2021-04-10 05:46
Current environment : mac 10.15.2 vue3+ vite + ts

**Comment by wushijiang13** [comment] 2021-04-10 05:47
vue-tsc version : 0.0.15

**Comment by johnsoncodehk** [comment] 2021-04-10 05:51
@wushijiang13 this problem fixed in vue-tsc 0.0.16, but please use the latest version 0.0.21.

**Closed by johnsoncodehk** 2021-04-10 05:51 UTC

**Comment by johnsoncodehk** [comment] 2021-04-10 05:53
Duplicate of https://github.com/johnsoncodehk/vue-tsc/issues/7

**Comment by wushijiang13** [comment] 2021-04-10 06:43
Ok thanks

**Comment by wushijiang13** [comment] 2021-04-10 06:51
> [johnsoncodehk / vue-tsc＃7的](https://github.com/johnsoncodehk/vue-tsc/issues/7)副本[](https://github.com/johnsoncodehk/vue-tsc/issues/7)

Has been upgraded to 0.0.21! How to ignore file directory check?

**Comment by wushijiang13** [comment] 2021-04-10 06:51
node_modules should not be checked

**Comment by johnsoncodehk** [comment] 2021-04-10 06:54
@wushijiang13 you may want `vue-tsc --noEmit --skipLibCheck`, see https://stackoverflow.com/questions/51634361/how-to-force-tsc-to-ignore-node-modules-folder.

btw I just publish 0.0.22 to fix a few problems.

**Comment by wushijiang13** [comment] 2021-04-10 06:58
> 您可能需要@ wushijiang13`vue-tsc --noEmit --skipLibCheck`，请参阅https://stackoverflow.com/questions/51634361/how-to-force-tsc-to-ignore-node-modules-folder。
> 
> 顺便说一句，我只是发布了0.0.22来解决一些问题。

thank you for your reply😁
