### ISSUE TITLE
How to ignore errors in template

### ISSUE THREAD

**Issue by gas0324** [johnsoncodehk/volar#775] opened 2021-12-11 04:40 UTC
An error occurred in my template, but I don’t know how to deal with it, it doesn’t affect the running or packaging, but an error occurred in vue-tsc --noEmit, how should I go like //@ts-ignore Ignore this error as well
![QQ截图20211211123918](https://user-images.githubusercontent.com/14065807/145663988-692bf423-58c3-4e63-aab0-6cae13fcfc2f.jpg)
![QQ截图20211211123926](https://user-images.githubusercontent.com/14065807/145663989-b2fbeb5b-4e00-401e-919a-2ee9c8e87284.jpg)
![QQ截图20211211124013](https://user-images.githubusercontent.com/14065807/145664001-a1c40428-dbe9-4c43-95fc-8cfb9217f838.jpg)

**Comment by gas0324** [comment] 2021-12-11 04:41
src/components/table/tr.vue:53:8 - error TS2502: 'default' is referenced directly or indirectly in its own type annotation.

53       <slot :row="rowData" :col="col" :colIndex="colIndex"></slot>
          ~~~~

**Comment by robyedlin** [comment] 2021-12-13 06:29
@gas0324 Do you have a repo we can check?

**Comment by gas0324** [comment] 2021-12-13 06:29
来信已收到。

**Comment by gas0324** [comment] 2021-12-13 07:17
> @gas0324 Do you have a repo we can check?
[vite-project.zip](https://github.com/johnsoncodehk/volar/files/7701718/vite-project.zip)

This is my demo

**Comment by gas0324** [comment] 2021-12-15 05:36
can you help me? @robyedlin

**Comment by johnsoncodehk** [comment] 2021-12-15 07:29
See https://github.com/johnsoncodehk/volar/issues/683#issuecomment-965630660.

**Comment by johnsoncodehk** [comment] 2021-12-15 07:29
Duplicate of #683

**Closed by johnsoncodehk** 2021-12-15 07:29 UTC

**Comment by gas0324** [comment] 2021-12-15 07:58
Thank you. It solves my problem
