### ISSUE TITLE
Emmet Abbreviation conflict with vue Directives

### ISSUE THREAD

**Issue by fyeeme** [johnsoncodehk/volar#2352] opened 2023-02-01 07:03 UTC
examples: v-if in <div> should be:

```vue
<div v-if=""></div>
```
but now the first option is 

```vue 
<div <v-if></v-if>></div>
```

videos:

https://user-images.githubusercontent.com/6078758/215973748-1743fa74-f4aa-4fe1-b669-37474f5c3d7f.mov

**Comment by johnsoncodehk** [comment] 2023-02-01 07:04
Duplicate of #1329

**Closed by johnsoncodehk** 2023-02-01 07:04 UTC
