### ISSUE TITLE
Using defineProps in <script setup> breaks inspection and jump to definition in vscode

### ISSUE THREAD

**Issue by vhflat** [johnsoncodehk/volar#1297] opened 2022-05-12 11:47 UTC
https://v.usetapes.com/1liEwyS79l

The video illustrates it. If I use `defineProps` in my setup, I cant inspect vscode doesn't detect the components anymore.

**Comment by johnsoncodehk** [comment] 2022-05-12 11:50
Duplicate of #1192

**Closed by johnsoncodehk** 2022-05-12 11:50 UTC
