### ISSUE TITLE
No autocompletion in .eslintrc.js in a subdirectory with tsconfig.json in take over mode

### ISSUE THREAD

**Issue by segevfiner** [johnsoncodehk/volar#1283] opened 2022-05-10 07:37 UTC
I have an `.eslintrc.js` with the following:
```js
//@ts-check
/* eslint-env node */
require("@rushstack/eslint-patch/modern-module-resolution");

/** @type {import("eslint").Linter.Config} */
module.exports = {
  root: true,
  extends: [
    "plugin:vue/vue3-essential",
    "eslint:recommended",
    "@vue/eslint-config-typescript/recommended",
    "@vue/eslint-config-prettier",
  ],
  env: {
    "vue/setup-compiler-macros": true,
  },
  ignorePatterns: ["dist/**/*"],
  
};
```

In a subdirectory with its own `tsconfig.json`. I get no autocomplete for this file in take over mode, only when using the default TypeScript plugin.

**Comment by johnsoncodehk** [comment] 2022-10-17 21:30
Duplicate of #1147

**Closed by johnsoncodehk** 2022-10-17 21:30 UTC
