### ISSUE TITLE
Split Editors unfolding when deleting a line in the `<script>` area

### ISSUE THREAD

**Issue by huzaifahj** [johnsoncodehk/volar#2121] opened 2022-11-16 13:39 UTC
## Reproduction

1. Create a `Test.vue` file with this content

```vue
<script setup lang="ts">
console.log("hello")
console.log("hello")
console.log("hello")
</script>

<template>
  <div></div>
</template>
```

2. Press the "Split Editors" icon in VSCode.

3. On the left, `<script>` side, delete a line of code

Outcome: The folded `<script>` on the right, `<template>` side unfolds!

## Comments

This has been really bugging me in development and the constant unfolding of code doesn't lead to great separation of concerns. Not sure if anyone else can reproduce this or is noticing this in normal development.

**Comment by johnsoncodehk** [comment] 2022-11-29 07:13
Duplicate of #https://github.com/microsoft/vscode/issues/161647

**Closed by johnsoncodehk** 2022-11-29 07:13 UTC
