### ISSUE TITLE
'xxx' is assigned a value but never used

### ISSUE THREAD

**Issue by fengxinming** [johnsoncodehk/volar#1357] opened 2022-05-27 07:12 UTC
Vscode shows eslint warning when using pug template in a vue file

```vue
<template>
<div>{{msg}}</div>
</template>
<script setup lang="ts">
const msg = 'hello';
</script>
```

> nothing

```vue
<template lang="pug">
div {{msg}}
</template>
<script setup lang="ts">
const msg = 'hello';
</script>
```

> 'msg' is assigned a value but never used.eslint[@typescript-eslint/no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars)

**Comment by johnsoncodehk** [comment] 2022-05-28 14:33
Duplicate of #604

**Closed by johnsoncodehk** 2022-05-28 14:33 UTC
