### ISSUE TITLE
Wrong highlight of :global() element

### ISSUE THREAD

**Issue by danielgroen** [johnsoncodehk/volar#1899] opened 2022-09-23 11:21 UTC
See uploaded picture, the first one is white and the second one is blue.
![afbeelding](https://user-images.githubusercontent.com/6578052/191949966-1411a8be-ad3b-4b0d-b321-7e9950e767ff.png)

**Comment by johnsoncodehk** [comment] 2022-09-26 20:01
Duplicate of #789

**Closed by johnsoncodehk** 2022-09-26 20:01 UTC
