### ISSUE TITLE
`<svg />` in `<template>` breaks syntax highlting in entire file

### ISSUE THREAD

**Issue by zardoy** [johnsoncodehk/volar#1049] opened 2022-03-15 11:48 UTC
Steps to reproduce:

create some `.vue` file with following contents:

```vue
<template>
  <svg />
</template>
<script>
/**
 * @returns {string}
 */
 const getSomeData = (arg) => "str";
</script>
```

In Vetur and on GitHub (you can see above) syntax is not broken.

<img width="451" alt="Screenshot 2022-03-15 at 14 47 51" src="https://user-images.githubusercontent.com/46503702/158371575-eff67172-67f5-4008-87c6-6021df86aba7.png">

**Comment by johnsoncodehk** [comment] 2022-03-15 12:27
Duplicate of #192

**Closed by johnsoncodehk** 2022-03-15 12:27 UTC
