### ISSUE TITLE
what's wrong with volar?

### ISSUE THREAD

**Issue by mRcongzi** [johnsoncodehk/volar#1848] opened 2022-09-09 02:25 UTC
All of a sudden, the Vue component in my project appeared a bunch of unexplained error messages, and disappeared after closing Volar. Why does it also contain JSX error information? I tried to comment out the **JSX: "preserve"** option in **tsconfig.js** and the error disappeared, but there was no way to jump between components. Is that why Volar's parsing is wrong? I don't know how to fix it

![image](https://user-images.githubusercontent.com/22736400/189258881-c3c26945-ff8e-4eb6-aa94-52d315e43465.png)

![image](https://user-images.githubusercontent.com/22736400/189258795-66eb5075-654c-49b1-ab3c-96bcfae7849d.png)

**Comment by caio-2k** [comment] 2022-09-09 18:53
Are you using Typescript? If so you need refer to this https://github.com/johnsoncodehk/volar/issues/1706#issuecomment-1233819252

In my case changing the type assertion using "as" fix my problems with JSX in components.

**Comment by mRcongzi** [comment] 2022-09-13 06:33
> Are you using Typescript? If so you need refer to this [#1706 (comment)](https://github.com/johnsoncodehk/volar/issues/1706#issuecomment-1233819252)
> 
> In my case changing the type assertion using "as" fix my problems with JSX in components. Check my issue #1795

I know what the reason is. It was the version problem of Volar, but now it has been dealt with and no more errors will be reported, thanks!

**Comment by johnsoncodehk** [comment] 2022-09-13 09:18
Hi @mRcongzi, should I close this if the problem is gone?

**Comment by mRcongzi** [comment] 2022-09-13 09:25
> Hi @mRcongzi, should I close this if the problem is gone?

of cause, please

**Comment by mRcongzi** [comment] 2022-09-13 09:27
> Hi @mRcongzi, should I close this if the problem is gone?

Sure, but aren't you going to fix that in the new version?

**Comment by johnsoncodehk** [comment] 2022-09-13 09:36
If you mean #1706, it is planed to resolve in new version.

**Closed** 2022-09-13 09:50 UTC
