### ISSUE TITLE
Automatically introduce module exceptions

### ISSUE THREAD

**Issue by TuiMao233** [johnsoncodehk/volar#86] opened 2021-03-05 09:11 UTC
![image](https://user-images.githubusercontent.com/49724027/110093353-95d1e900-7dd5-11eb-8a12-7b160d952c3d.png)

![image](https://user-images.githubusercontent.com/49724027/110093505-c023a680-7dd5-11eb-9c5a-ae46c367d42d.png)

**Comment by johnsoncodehk** [comment] 2021-03-05 09:27
Thanks for report, but I can't reproduce your problem, can you give me a repro?

<img width="745" alt="螢幕截圖 2021-03-05 下午5 25 10" src="https://user-images.githubusercontent.com/16279759/110095322-c4e95a00-7dd7-11eb-9ae7-e3ef06e668e3.png">

**Comment by johnsoncodehk** [comment] 2021-03-05 10:03
It seem VSCode 1.54 problem with Windows, you may need to downgrade to 1.53.

**Comment by TuiMao233** [comment] 2021-03-05 10:20
I also guessed it, I am looking for a way to fall back to VSCode

**Comment by TuiMao233** [comment] 2021-03-05 10:37
I am thinking this is not a long-term move. I tried Vetur and there is no such problem. Will this problem be fixed?

**Comment by johnsoncodehk** [comment] 2021-03-05 16:01
Fixed in 0.22.2.

**Closed by johnsoncodehk** 2021-03-05 16:01 UTC
