### ISSUE TITLE
An object in an array in the class attribute breaks syntax highlighting

### ISSUE THREAD

**Issue by szulcus** [johnsoncodehk/volar#1572] opened 2022-07-13 11:18 UTC
An object in an array in the `class` attribute breaks syntax highlighting:

![image](https://user-images.githubusercontent.com/48328739/178721558-df2b8f64-0ea9-4bd0-b439-58afa926538e.png)

**Comment by provinzkraut** [comment] 2022-07-13 11:49
I'm experiencing the same issue. Looks like this was introduced in `0.38.4`. As a temporary workaround, you can downgrade to `0.38.3`.

**Comment by LoiLock** [comment] 2022-07-13 12:08
This is a duplicate of https://github.com/johnsoncodehk/volar/issues/1553
It happens with classes and style bindings, and doesn't just have to be an array. Any object will do.

**Closed** 2022-07-16 17:16 UTC
