### ISSUE TITLE
[Error] <script> / <script setup> block not found.

### ISSUE THREAD

**Issue by shakil-muntasir** [johnsoncodehk/volar#347] opened 2021-08-08 02:32 UTC
Step to produce:  Trying to auto import the <HelloWorld  /> component as a fragment on the <App /> component.

Using a freshly installed vite vue3 js app.

App component code: 
```
<template>
    <div>
        <img alt="Vue logo" src="./assets/logo.png" />
    </div>

    <!--- will try to insert HelloWorld component below as a fragment --->
    <HelloWorld />
</template>

<script setup>
</script>
```

When type <H... to auto import the, this error shows up in Valor extension `[Error] <script> / <script setup> block not found.`

Attaching the screenshot here. Hope it helps.

![image](https://user-images.githubusercontent.com/30091488/128618780-bbc380ea-c510-4868-bd6a-ec21a148bf50.png)

Edit: Attaching my jsconfig.json

```
{
    "compilerOptions": {
        "target": "esnext",
        "module": "esnext",
        "moduleResolution": "node",
        "strict": true,
        "jsx": "preserve",
        "sourceMap": true,
        "resolveJsonModule": true,
        "esModuleInterop": true,
        "lib": ["esnext", "dom"]
    },
    "include": ["src/**/*.js", "src/**/*.ts", "src/**/*.d.ts", "src/**/*.tsx", "src/**/*.vue"],
    "exclude": ["node_modules", "public"]
}
```

**Comment by johnsoncodehk** [comment] 2021-08-08 09:30
Duplicate of #299

**Closed by johnsoncodehk** 2021-08-08 09:30 UTC
