### ISSUE TITLE
volar inlay hints

### ISSUE THREAD

**Issue by Kabuda-czh** [johnsoncodehk/volar#2086] opened 2022-11-02 09:58 UTC
### Discussed in https://github.com/johnsoncodehk/volar/discussions/2066

<div type='discussions-op-text'>

<sup>Originally posted by **Kabuda-czh** October 27, 2022</sup>
when i open vscode's typescript > inlay hints and use volar.
![1](https://user-images.githubusercontent.com/62021214/198211572-e9bef551-3085-45e2-8f12-17c090d36d96.png)

After some times, there will be repeated.
![2](https://user-images.githubusercontent.com/62021214/198211657-78627dc1-3571-4d1e-861a-873cdc2d3d4a.png)

if `restart Vue Server` it will fixed , is this volar's bug?</div>

**Comment by johnsoncodehk** [comment] 2022-11-29 07:58
Duplicate of #1807

**Closed by johnsoncodehk** 2022-11-29 07:58 UTC
