### ISSUE TITLE
Fix CSS emmet

### ISSUE THREAD

**Issue by Pero122** [johnsoncodehk/volar#1367] opened 2022-05-30 12:54 UTC
This is my first Github issue, if I forgot to add something relevant I am sorry. 

I am programing with Vue in VS Code, I want to enabled Emmet in <template> part of .vue file, but want to turn disable emmet in <style> part because of this annoying suggestion that can be seen it the following image:
![image](https://user-images.githubusercontent.com/24699984/170996253-6008500e-8872-4b7a-8021-fa4f26f9c95c.png)

Can this useless suggestion be fixed or removed?

**Comment by johnsoncodehk** [comment] 2022-05-30 15:49
Duplicate of #1358

**Closed by johnsoncodehk** 2022-05-30 15:49 UTC
