### ISSUE TITLE
Typescript casting is now being treated as JSX

### ISSUE THREAD

**Issue by schehlmj** [johnsoncodehk/volar#1761] opened 2022-08-25 02:25 UTC
In 0.40.0 and 0.40.1, type casting is now being treated as jsx.

```
<script setup lang="ts">
interface Example {
    number: number;
}
const foo = <Example[]>[];  // this has invalid error: 'Example' only refers to a type, but is being used as a value here.ts(2693)
</script>
```

Reverting back to 0.39.5 fixes the issue.

The reason I think it is related to JSX is because I went to https://www.typescriptlang.org/play  to test, and it had an extremely similar error, and then I clicked the TS Config button and changed "JSX Setting" to "None" (it was "React" before).

**Comment by johnbendi** [comment] 2022-08-26 06:43
> In 0.40.0 and 0.40.1, type casting is now being treated as jsx.
> 
> ```
> <script setup lang="ts">
> interface Example {
>     number: number;
> }
> const foo = <Example[]>[];  // this has invalid error: 'Example' only refers to a type, but is being used as a value here.ts(2693)
> </script>
> ```
> 
> Reverting back to 0.39.5 fixes the issue.
> 
> The reason I think it is related to JSX is because I went to https://www.typescriptlang.org/play to test, and it had an extremely similar error, and then I clicked the TS Config button and changed "JSX Setting" to "None" (it was "React" before).

You can also try wrapping the value being casted in parenthesis. I think it helps.

**Comment by johnsoncodehk** [comment] 2022-09-21 23:13
Duplicate of #1706

**Closed by johnsoncodehk** 2022-09-21 23:13 UTC
