### ISSUE TITLE
0.36.0 breaks Vue SFC's and tests with @vue/test-utils

### ISSUE THREAD

**Issue by TheDutchCoder** [johnsoncodehk/volar#1386] opened 2022-06-03 13:44 UTC
Since the new version (0.36.0), TS will throw errors for things like `data-` attributes and `aria-` attributes in Vue SFC files, ~~as well as throw errors when mounting components in tests with `@vue/test-utils`.~~

Installing 0.35.2 fixes the issue

0.35.2:
![image](https://user-images.githubusercontent.com/1668207/171866306-5c0a5433-0f17-40b8-aff9-5a95802e2cbb.png)

0.36.0:
![image](https://user-images.githubusercontent.com/1668207/171866371-e51562da-35f5-4d39-a263-a7b9f26d34d4.png)

**Comment by dnet-o** [comment] 2022-06-03 17:17
Not only the data-test-id attribute, but all non-natives attributes, such as windicss attributify

**Comment by myknbani** [comment] 2022-06-03 18:01
I can confirm this bug as well.  All my `data-testid` attributes started becoming red.

**Comment by myknbani** [comment] 2022-06-03 18:04
I can confirm https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1145361472 works.

**Comment by myknbani** [comment] 2022-06-04 01:21
Comment on https://github.com/johnsoncodehk/volar/issues/1077#issuecomment-1145361472 works
![Screenshot from 2022-06-04 09-20-40](https://user-images.githubusercontent.com/5841268/171971092-2d0005ae-6089-44ee-9ebc-4fef0581d2b5.png)

**Comment by TheDutchCoder** [comment] 2022-06-04 01:32
Why would you have to explicitly declare the already valid attributes?

This change makes no sense to me, any `data-*` attribute is already according to spec and TS is well aware of it.

I don't understand why this has to be whitelisted. This seems like an unwelcome regression.

**Comment by jzs11** [comment] 2022-06-04 02:19
Please take a look...

**Comment by johnsoncodehk** [comment] 2022-06-04 10:50
Duplicate of #1383

**Closed by johnsoncodehk** 2022-06-04 10:50 UTC
