### ISSUE TITLE
Nuxt 3: Variable X is declared but its value is never read.ts(6133)

### ISSUE THREAD

**Issue by phillipmohr** [johnsoncodehk/volar#1735] opened 2022-08-19 14:30 UTC
Hello, 

I'm using Nuxt 3 + VS Code + Vue Language Features (Volar) + TypeScript Vue Plugin (Volar). 
When I define variables within my script, Volar doesn't seem to recognize that I'm using those in my template. 

Here is an Example. `Menus.vue`
```vue
<template>
    <AdminFormBuilder
        @isLoading="setIsLoading"
    >
        <template #form:before>
            <AdminCrudHeader
                :isLoading="isLoading"
            />
        </template>
    </AdminFormBuilder>
</template>


<script lang="ts" setup>
const isLoading = ref(false)
const setIsLoading = (value: boolean) => {
    isLoading.value = value
}
</script>

```

Hovering over `setIsLoading` tells me `'setIsLoading' is declared but its value is never read.ts(6133)`

**Comment by johnsoncodehk** [comment] 2022-08-27 16:52
Duplicate of #1729

**Closed by johnsoncodehk** 2022-08-27 16:52 UTC

**Comment by RSS1102** [comment] 2022-09-01 09:51
I met this too in Nuxt3.
After I refer to[ 1168#](https://github.com/johnsoncodehk/volar/issues/1168#issuecomment-1229214249).
do:

![image](https://user-images.githubusercontent.com/81673017/187885779-bea7d305-c8ae-4926-9cb8-02d09fd29d5d.png)

then:
(In nuxt3 methods that do not need to import "Vue")
![image](https://user-images.githubusercontent.com/81673017/187885638-4a03ec5a-a398-4c6f-9b04-84f02e0de803.png)
![image](https://user-images.githubusercontent.com/81673017/187885688-f3b1c688-69ea-44b1-b354-4849a3255f2c.png)
