### ISSUE TITLE
Cannot find module "./App.vue" or its corresponding type declarations

### ISSUE THREAD

**Issue by ashgo-x** [johnsoncodehk/volar#1409] opened 2022-06-07 07:31 UTC
### Environments

- Operating System: `macOS`
- VSCode Version: `1.67.2`
- Volar Version: `0.37.1`

### Description

VSCode prompts the error "Cannot find module "./App.vue" or its corresponding type declarations" in `src/main.ts` when Take Over Mode is turned on.

The problem could be solved when `TypeScript Vue Plugin (Volar)` is installed, but it's recommended to use Take Over Mode instead of this plugin.

**Comment by ashgo-x** [comment] 2022-06-08 08:25
I created the project with `pnpm create vite`. It ran successfully on the dev server and it didn't produce any declaration files throughout the process.

**Comment by johnsoncodehk** [comment] 2022-06-08 12:24
Duplicate of #664

**Closed by johnsoncodehk** 2022-06-08 12:24 UTC

**Comment by Leon0402** [comment] 2022-06-16 12:36
@johnsoncodehk Same Problem here, takeover mode is activated. In general it doesn't find any imports typescript / javascript files. It does find the imports in .vue files. 

I tested with the volar starter project. 

![image](https://user-images.githubusercontent.com/33933142/174071026-aa67aa57-c656-40c0-ade6-7b59b7d62fed.png)
![image](https://user-images.githubusercontent.com/33933142/174071050-e38b9357-dc96-48e6-ad7e-5a1bff566cb1.png)

**Comment by johnsoncodehk** [comment] 2022-09-21 17:18
@Leon0402 Please make sure reload VSCode after disable built-in TS extension.
