### ISSUE TITLE
dynamic component not recognized

### ISSUE THREAD

**Issue by baojd42** [johnsoncodehk/volar#682] opened 2021-11-09 11:10 UTC
I would like to use `<component :is="name" />` .

The editor labels it with red color and the intellisense infers the type as any. No error messages prompted.
![image](https://user-images.githubusercontent.com/33564834/140911677-44ca7539-1e6f-4d93-ad75-04549895fb63.png)

The code works fine. It seems this tag is not recognized by volar.

vue: 2.6.14
volar: 0.29.2
vscode: 1.62.0

**Comment by IWANABETHATGUY** [comment] 2021-11-09 11:39
this is expected, because component type is runtime determined, there is no way to infer component props before runtime.

**Comment by sethidden** [comment] 2021-11-09 12:28
@IWANABETHATGUY Should theoretically be possible if `name` has an explicit type
```html
<template>
  <component :is="name" prop-that-only-exists-on-the-somecomponent="hello"/> <!-- should throw error since prop-that-only-exists-on-the-somecomponent cannot be found on OtherComponent -->
  <button>Render Some Component</button>
  <button>Render Other Component</button>
</template>
<script setup lang="ts">
import SomeComponent from './SomeComponent.vue'
import OtherComponent from './OtherComponent.vue'
const setSome = () => { name.value = SomeComponent }
const setOther = () => { name.value = OtherComponent }

const name = ref<typeof SomeComponent | typeof OtherComponent>(SomeComponent)
</script>
```

**Comment by baojd42** [comment] 2021-11-10 10:37
@IWANABETHATGUY Thanks for your reply. If `<component>` being any is expected, then I can live with that. But it is highlighted the same as a not imported component. That is a bit annoying. 
![image](https://user-images.githubusercontent.com/33564834/141096116-f1edc0ab-332e-4bec-90f6-85a495d935a1.png)
I noticed in the docs, `<component>` and `<slot>` are both component-like feature of [template syntax](https://v3.vuejs.org/api/built-in-components.html#built-in-components). Should they be highlighted the same way?

**Comment by baojd42** [comment] 2021-11-10 10:38
> @IWANABETHATGUY Should theoretically be possible if `name` has an explicit type
> 
> ```
> <template>
>   <component :is="name" prop-that-only-exists-on-the-somecomponent="hello"/> 
>   <button @click="setSome()">Render Some Component</button>
>   <button @click="setOther()" >Render Other Component</button>
> </template>
> <script setup lang="ts">
> import SomeComponent from './SomeComponent.vue'
> import OtherComponent from './OtherComponent.vue'
> const setSome = () => { name.value = SomeComponent }
> const setOther = () => { name.value = OtherComponent }
> 
> const name = ref<typeof SomeComponent | typeof OtherComponent>(SomeComponent)
> </script>
> ```

It would be great if this could be implemented.

**Comment by johnsoncodehk** [comment] 2021-11-10 18:15
You can already define it yourself.

```ts
declare module '@vue/runtime-dom' {
	export interface GlobalComponents {
		component: <T>(props: { is: T } & ExtractComponentProps<T>) => JSX.Element
	}
}

type ExtractComponentProps<T> = T extends new (...args: any) => { $props: infer P } ? P : {};

export { }
```

<img width="747" alt="螢幕截圖 2021-11-11 上午2 15 08" src="https://user-images.githubusercontent.com/16279759/141170096-f00ce562-cb70-42ca-b255-0a82d1c62e94.png">

**Comment by johnsoncodehk** [comment] 2021-11-10 18:15
Duplicate of #482

**Closed by johnsoncodehk** 2021-11-10 18:15 UTC
