### ISSUE TITLE
Does not see the components in the components folder 0.40.1

### ISSUE THREAD

**Issue by Flashantik** [johnsoncodehk/volar#1746] opened 2022-08-21 14:52 UTC
in last version of volar 0.40.1 intellisense does not see other components in the components folder. You can use components only on Pages
in 0.39.5 all is fine

**Comment by Flashantik** [comment] 2022-08-21 14:55
In 0.40.1 i have
<img width="542" alt="Screen Shot 2022-08-21 at 19 53 35" src="https://user-images.githubusercontent.com/25429994/185797131-c7be0499-8a42-4781-bb79-f354aa4c807c.png">

in 0.39.5 
<img width="673" alt="Screen Shot 2022-08-21 at 19 55 07" src="https://user-images.githubusercontent.com/25429994/185797167-ddb80996-fc5d-490d-b09c-b5b9c4f3620b.png">

**Comment by xafxafxaf** [comment] 2022-08-21 20:57
Fix for me `jsconfig.json`:
```json
"compilerOptions": {
    "jsx": "preserve"
}
```

**Comment by colinblaise** [comment] 2022-08-23 14:46
> I fixed it by adding line to `jsconfig.json`:
> 
> ```json
> "compilerOptions": {
>     "jsx": "preserve"
> }
> ```

I'm having the same issue and I already had this in my tsconfig.json

**Comment by xafxafxaf** [comment] 2022-08-23 20:31
> > I fixed it by adding line to `jsconfig.json`:
> > ```json
> > "compilerOptions": {
> >     "jsx": "preserve"
> > }
> > ```
> 
> No good for me. I'm having the same issue and I already had this in my tsconfig.json

magic.

**Comment by johnsoncodehk** [comment] 2022-08-27 17:33
Duplicate of #1731

**Closed by johnsoncodehk** 2022-08-27 17:33 UTC

**Comment by Flashantik** [comment] 2022-09-08 09:57
@johnsoncodehk Yes now you can see it is a component, but type always is any
<img width="268" alt="Screen Shot 2022-09-08 at 14 56 44" src="https://user-images.githubusercontent.com/25429994/189093475-58f84684-5a7a-4818-977b-7ac13573a2ca.png">


Volar v0.40.13
Vscode: 1.71.0
nuxt@2.15.8
vue@2.6.14
typescript@4.7.3
