### ISSUE TITLE
Error ts(2322) in v-on 'void' is not assignable to type 'undefined'

### ISSUE THREAD

**Issue by drocha87** [johnsoncodehk/volar#479] opened 2021-09-10 19:24 UTC
Hey guys, I don't know if this problem is related to `volar` or `vue3`, but I realized that after my `volar` upgraded to version `0.27.17` I started to receive error messages when using my components. 

![Screenshot from 2021-09-10 16-16-11](https://user-images.githubusercontent.com/31552590/132905823-6c498e74-91c9-407c-b850-c7240af3c03a.png)

Maybe the way I'm typing the emit event was wrong? I'm typing it inside the component like this like this. 

```html

<script lang="ts">
import { defineComponent, ref } from 'vue'
import { Question } from '../types'

...

interface Answer {
 ...
}

export default defineComponent({
  components: {
    ResourceQuestion,
  },

  props: {
    ...
  },

  setup(props) {
    ...
    const emit = defineEmits<{
      (event: 'answer', data: Answer): void
    }>()

    ...
    return {
    ...
    }
  },
})
</script>

}>()
```

volar version: `0.27.17` 
vscode version: `1.60.0`
typescript version: `4.4.2`

**Comment by johnsoncodehk** [comment] 2021-09-10 19:26
This is known vue type issue, please try update your vue version to latest.

**Comment by johnsoncodehk** [comment] 2021-09-10 19:27
Duplicate of #460

**Closed by johnsoncodehk** 2021-09-10 19:27 UTC
Labels: upstream

**Comment by drocha87** [comment] 2021-09-10 19:32
Thank you, updating the deps indeed fixed the problem!!
