### ISSUE TITLE
aria attributes no longer recognized

### ISSUE THREAD

**Issue by henribru** [johnsoncodehk/volar#1383] opened 2022-06-03 05:48 UTC
https://github.com/henribru/volar-html-attribute-bug

```
<button @click="count++" aria-label="foo">count is: {{ count }}</button>
```

> Type '{ ariaLabel: string; "aria-label": string; }' is not assignable to type 'ElementAttrs<ButtonHTMLAttributes>'.
>  Property 'ariaLabel' does not exist on type 'ElementAttrs<ButtonHTMLAttributes>'. Did you mean ''aria-label''?

**Comment by hongquan** [comment] 2022-06-03 05:49
Appear in volar v0.36.

**Comment by adenvt** [comment] 2022-06-03 07:40
I got something weird, `aria-label` work perfectly. But attribute `data-testid` have an error.

It happen in `0.36.0`.

![image](https://user-images.githubusercontent.com/10667160/171809848-71636a9e-adf6-4b95-a3b8-f0021f5ed88b.png)

**Comment by cawa-93** [comment] 2022-06-03 08:32
Additionals: `loading` attr in images and iframes
```node
TS2322: Type '{ src: string; alt: string; loading: string; }' is not assignable to type 'ElementAttrs<ImgHTMLAttributes>'.       
  Property 'loading' does not exist on type 'ElementAttrs<ImgHTMLAttributes>'.

20     <img v-if="layoutProperties.src" :src="layoutProperties.src" :alt="layoutProperties.url" loading="eager" >
                                                                                                ~~~~~~~
```

`fill-rule` in `<path>`
```node
Type '{ fillRule: string; "fill-rule": "evenodd"; d: string; }' is not assignable to type 'ElementAttrs<SVGAttributes>'.
  Property 'fillRule' does not exist on type 'ElementAttrs<SVGAttributes>'. Did you mean ''fill-rule''?

29             <path fill-rule="evenodd" d=""/>
                     ~~~~~~~~~
```

Attributes in custom inputs
```node
 TS2322: Type '{ required: boolean; placeholder: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{ i
d: string; }> & Omit<Readonly<ExtractPropTypes<__VLS_WithDefaults<__VLS_TypePropsToRuntimeProps<Props>, { ...; }>>> & { ...; } & VNodeProps & AllowedComponentProps & ComponentCustomP
rops, "id">'.
  Property 'required' does not exist on type 'IntrinsicAttributes & Partial<{ id: string; }> & Omit<Readonly<ExtractPropTypes<__VLS_WithDefaults<__VLS_TypePropsToRuntimeProps<Props>,
 { ...; }>>> & { ...; } & VNodeProps & AllowedComponentProps & ComponentCustomProps, "id">'.

25   <bs-textarea required placeholder="asd"/>
                  ~~~~~~~~
```
```node
 TS2322: Type '{ placeholder: string; }' is not assignable to type 'IntrinsicAttributes & Partial<{ id: string; }> & Omi
t<Readonly<ExtractPropTypes<__VLS_WithDefaults<__VLS_TypePropsToRuntimeProps<Props>, { ...; }>>> & { ...; } & VNodeProps & AllowedComponentProps & ComponentCustomProps, "id">'.      
  Property 'placeholder' does not exist on type 'IntrinsicAttributes & Partial<{ id: string; }> & Omit<Readonly<ExtractPropTypes<__VLS_WithDefaults<__VLS_TypePropsToRuntimeProps<Prop
s>, { ...; }>>> & { ...; } & VNodeProps & AllowedComponentProps & ComponentCustomProps, "id">'.

26   <bs-textarea placeholder="asd"/>
                  ~~~~~~~~~~~

```
```node
TS2322: Type '{ disabled: boolean; }' is not assignable to type 'IntrinsicAttributes & Partial<{ id: string; }> & Omit<
Readonly<ExtractPropTypes<__VLS_WithDefaults<__VLS_TypePropsToRuntimeProps<Props>, { ...; }>>> & { ...; } & VNodeProps & AllowedComponentProps & ComponentCustomProps, "id">'.        
  Property 'disabled' does not exist on type 'IntrinsicAttributes & Partial<{ id: string; }> & Omit<Readonly<ExtractPropTypes<__VLS_WithDefaults<__VLS_TypePropsToRuntimeProps<Props>,
 { ...; }>>> & { ...; } & VNodeProps & AllowedComponentProps & ComponentCustomProps, "id">'.

27   <bs-textarea :disabled="true" />
                   ~~~~~~~~
```

**Comment by kk256vv** [comment] 2022-06-03 11:15
adding some more (v0.36.0)

svg fill-rule
<img width="510" alt="image" src="https://user-images.githubusercontent.com/106813280/171843227-89a4d63d-bead-4c30-8299-dad443bf2dd4.png">

svg use xlink:href ( its deprecated but still needed for ios < 12 )
<img width="561" alt="image" src="https://user-images.githubusercontent.com/106813280/171843317-7db60795-8303-435e-9e65-8d403ff9186a.png">

**Comment by johnsoncodehk** [comment] 2022-06-03 13:22
Duplicate of #1383

**Closed** 2022-06-03 13:22 UTC
Labels: question
