### ISSUE TITLE
Syntax highlighting break after defining a Type

### ISSUE THREAD

**Issue by ssshooter** [johnsoncodehk/volar#1334] opened 2022-05-23 10:41 UTC
Name: Vue Language Features (Volar)
Id: Vue.volar
Description: Language support for Vue 3
Version: 0.34.16
Publisher: Vue
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Vue.volar

![image](https://user-images.githubusercontent.com/13051472/169801674-b68d9dc8-9892-482a-8ddf-afabfcba3152.png)

working normally while use interface

![image](https://user-images.githubusercontent.com/13051472/169801807-be4fd96b-cd89-4c5a-87ac-ee3e401bcdd3.png)

**Comment by johnsoncodehk** [comment] 2022-05-28 16:14
Duplicate of #986

**Closed by johnsoncodehk** 2022-05-28 16:14 UTC
