### ISSUE TITLE
attributes/props not being validated after update to > Volar v0.39.5

### ISSUE THREAD

**Issue by JarvisH** [johnsoncodehk/volar#1758] opened 2022-08-24 13:50 UTC
After updating to Volar 0.40.1 from 0.39.5, component prop-bindings are no longer validated.

```
// prop-binding should be marked as wrong in vscode, but is not.
<some-component :some-prop-expects-object="123" />
```

This occurs on Windows 10 while running Vscode from WSL2 Ubuntu.
On macOS the same issue could not be reproduced.

```
// output from "npx envinfo --system --binaries --browsers" if relevant:

  System:
    OS: Linux 4.19 Ubuntu 20.04.1 LTS (Focal Fossa)
    CPU: (3) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
    Memory: 28.78 GB / 31.36 GB
    Container: Yes
    Shell: 5.8 - /usr/bin/zsh
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
```

- Vscode is version 1.70.2
- Takeovermode is enabled.
- builtin Typescript is disabled.

**Comment by Xu-doudou** [comment] 2022-08-26 01:46
Me too, no code hint when I updating to Volar v0.40.1
Now I reinstalled back to v0.39.5

**Comment by johnsoncodehk** [comment] 2022-08-27 18:15
Duplicate of #1731

**Closed by johnsoncodehk** 2022-08-27 18:15 UTC
