### ISSUE TITLE
TypeScript throw  error when a vue component has cyclic dependencies

### ISSUE THREAD

**Issue by beliefgp** [johnsoncodehk/volar#951] opened 2022-02-10 09:26 UTC
TypeScript throw  error when a vue component has cyclic dependencies。

```vue
// test1.vue
<template>
  <section>
    <h2>test1</h2>
    <test v-if="isShowTest" />
  </section>
</template>

<script lang="ts" setup>
import Test from '@/components/test2.vue';

const isShowTest = false;
</script>
```

```vue 
// test2.vue
<template>
  <section>
    <h2>test2</h2>
    <test v-if="isShowTest" />
  </section>
</template>

<script lang="ts" setup>
import Test from '@/components/test1.vue';

const isShowTest = false;
</script>
```

![image](https://user-images.githubusercontent.com/12657964/153375578-66d110b5-3176-458c-a25f-e86526ae3d2b.png)
![image](https://user-images.githubusercontent.com/12657964/153375662-2d2b3589-b92a-476c-b157-b0e4a403b9f3.png)

**Comment by beliefgp** [comment] 2022-02-11 02:24
The problem remains

![image](https://user-images.githubusercontent.com/12657964/153528443-971fb381-1908-4117-9766-e53e8ab0f43e.png)

**Comment by IIFelix** [comment] 2022-02-11 13:38
Mhh unfortunately i can't fix it ... But the error goes away if you use the Options api instead of Composition api.
So you could use that for the time being.

**Comment by johnsoncodehk** [comment] 2022-02-12 18:49
Duplicate of #677

**Closed by johnsoncodehk** 2022-02-12 18:49 UTC
