### ISSUE TITLE
How to correctly check if a variable is null

### ISSUE THREAD

**Issue by Razi91** [johnsoncodehk/volar#2152] opened 2022-11-28 05:23 UTC
What is the correct way to check if ref/shallowRef is null? It 
```html
<template>
  <div>
    <div v-if="foo?.id">{{ callMe(foo.id) }}</div>
    <div v-if="byRef != null">
      {{ byRef.id }}
      <button @click="show(byRef)">B</button>
    </div>
    <div v-if="byShallowRef != null">
      {{ byShallowRef.id }}
      <button @click="show(byShallowRef)">B</button>
    </div>
    <div v-if="byReactive.byShallowRef != null">
      {{ byReactive.byShallowRef.id }}
      <button @click="show(byReactive.byShallowRef)">B</button>
    </div>
  </div>
</template>
<script setup lang="ts">
import { reactive, ref, shallowRef, unref } from "vue";

type Item = { id: number };
const byRef = ref<Item | null>(null);
const byShallowRef = shallowRef<Item | null>(null);

const byReactive = reactive({
  byRef,
  byShallowRef,
});

const foo = ref<Item | null>(null);
function callMe(id: number[]) {
  console.log(id);
}
function show(item: Item) {
  console.log(item);
}
</script>
```
in VSCode shows:
![image](https://user-images.githubusercontent.com/5995454/204199972-72ab64ec-6627-4f75-a058-a644a5198f9f.png)
`vue-tsc` also reports problems there. Is there a correct way to check if a variable is null, so it won't show false positive problems?

**Comment by troy351** [comment] 2022-11-28 07:05
This a pure TypeScript problem.
```ts
let foo: number | null = null
foo = 1
if (foo !== null) {
  setTimeout(() => {
    foo.toFixed()
  })
}
```
<img width="265" alt="image" src="https://user-images.githubusercontent.com/8372385/204213724-070e5e19-e8d0-4251-839f-5743b803266d.png">

The `@click` handler is just like `setTimeout` which is async, so the outer type guard can't ensure the inner callback was valid.
Workaround was check `foo` inside `setTimeout`, or just use a type assertion `foo!.toFixed()` if you can make sure it's valid.
In your case `@click="byRef && show(byRef)"` or `show(byRef!)`

**Comment by Razi91** [comment] 2022-11-28 08:19
`const` here would fix it. I've noticed that under the hood template compiler makes a giant tri-argument statement on `v-if`.

While original template compiler generates really optimized code, the typechecking compiler could make less optimized, more react-like templates with local variables to keep type guards, caching the `v-if` results locally. Taking the source: https://sfc.vuejs.org/#eNqVU0FugzAQ/MrWp0RK4E4hanvrNb36QsiSODW2ZRuiiPL3LoYI1KZRekGj3dmZ9WC37NWYqKmRJSz1WBmZe9xwBZDuRRPAAKFZizLjbHfZYglPGahaSs5GBkDbQmhFYg9dd62mu9p7reClkKL4pHF31OdFIC5p+C2NB8LVKP7L9OOYS6nPd7wnxmMrTPz/bbLFvPCiweiRpW6SH43oxuj9Va8ojWd/MnWFFcaDQ18bkLk6kId3YVNRGW09tGBHsxWhcgVuOlgHpdUVcEZ3hLNnrrjyF4PwThaQ0ajYJ3T0aocWOmoXWjk/XAVqk1oamF8hns2i/y5ntFmE2cz29tBcfdg3WAxw0fYRBOPVgCZtKnRzgT5iGl0IcknCUZaQbaBvaomR1IfQ6kfSeMiP0mIrNgS2rnITnZxW9GiCKx8blGoCodLXQmIJgaP3xiVx7Mqif2onF2l7iAlFtlZeVBihq9Y7q88OLQlzFk4wasRUbNCuLao9WrT3NH9Qf+n2snTzOtZ9A0BQV9w=

```ts
    (byRef.value != null)
      ? (_openBlock(), _createElementBlock("div", _hoisted_1, [
          _createTextVNode(_toDisplayString(byRef.value.id) + " ", 1 /* TEXT */),
          _createElementVNode("button", {
            onClick: _cache[0] || (_cache[0] = ($event) => (show(byRef.value)))
          }, "B")
        ]))
      : _createCommentVNode("v-if", true),
```
Sure, there is no way TS should know that `byRef.value` will not be null ever there... But if it would store `byRef.value` as local `const`, it could ensure it won't be null there. Of course, in a runtime environment, it would mean losing reactivity, but it doesn't matter here, it's fake code anyway.

In TS code it's easy to write local guards, templates don't allow to declare local variables, but they would be helpful here too.

But damn, that will be a lot of code changes here... It needs to write a completely separate template compiler that just ignores reactivity.

After all, during rendering, no state should be changed, if it does, the code is just bad and no type checking would help.

**Comment by troy351** [comment] 2022-11-28 08:29
`const` can be narrow down due to it was unchangeable
<img width="229" alt="image" src="https://user-images.githubusercontent.com/8372385/204229182-e5894e1a-f072-4f51-9785-d06abcb613c2.png">

How about this one?
<img width="272" alt="image" src="https://user-images.githubusercontent.com/8372385/204229767-4d15daf2-7dcb-4d4e-aaa3-b05a6b161b4d.png">

**Comment by Razi91** [comment] 2022-11-28 08:30
`foo.bar` could be stored in local variable `const foo$bar` in template compiled code

**Comment by troy351** [comment] 2022-11-28 08:47
As you said, reactivity will be lost which is unacceptable.
Why not just using `@click="show(byRef!)"` (note: there is a `!`)?

**Comment by Razi91** [comment] 2022-11-28 08:51
Because it's forced and makes TS useless here, you have to check if the variable is null yourself manually, if someone removes the condition, TS won't inform about the error.

**Comment by troy351** [comment] 2022-11-28 09:42
So you do want a `black boxed` local variable to make type guard work (which should be invalid by design),
meanwhile feels `!` type assertion makes TS useless?

What do you expect this one?
<img width="276" alt="image" src="https://user-images.githubusercontent.com/8372385/204244239-3ea60f07-a783-4d23-a667-a7deebc7142d.png">

Maybe you should allow `show` to receive `null` and check inside it.

**Comment by Razi91** [comment] 2022-11-28 09:53
the `{{ byRef.id }}` won't show if `byRef` is null, therefore, we can assume that `byRef` inside is not null, same with calling `show`.

It would look like this:
```ts
(() => {
  const _byRef = byRef.value;
  if (_byRef) {
    return /* create nodes using `_byRef` instead of `byRef.value` */
  } else {
    return _createCommentVNode("v-if", true),
  }
})();
```

**Comment by troy351** [comment] 2022-11-28 10:10
> ![image](https://user-images.githubusercontent.com/8372385/204251082-6be18028-580d-4e93-abaf-d396698c7cd2.png)

But the `show` invoke here did receive a `null` value

**Comment by Razi91** [comment] 2022-11-28 10:29
Right, it's a quite edge case...

**Comment by troy351** [comment] 2022-11-28 10:49
These is only one `byRef`, according to event flow, the inner click was executed first, then follows the `show`. I don't see any intuitive

**Comment by Razi91** [comment] 2022-11-28 10:53
The order of calls, the template would say that it shouldn't be null, because of `v-if`, but the `@click` inside will set `byRef` null before the `@click` outside will be called, but it will be called using reference, not the current (while rendering) value.

**Comment by Razi91** [comment] 2022-11-28 11:50
I know there isn't, but not looking into compiled code, it's something I would expect, that it would be called by value, not dereferencing at the moment of calling, which might happen after some other events would be called

**Comment by troy351** [comment] 2022-11-28 11:54
It seems you can't achieve what you expected without local variables.

**Comment by johnsoncodehk** [comment] 2022-11-29 12:55
Duplicate of #2144

**Closed by johnsoncodehk** 2022-11-29 12:55 UTC
