### ISSUE TITLE
Formant Document With Volar something happens seem wrong!

### ISSUE THREAD

**Issue by shiwanjun1995** [johnsoncodehk/volar#1217] opened 2022-04-20 12:33 UTC
1、Volar formats an HTML tag with many attributes in as few lines as possible. Look at bellow:

<img width="1366" alt="截屏2022-04-20 下午8 20 06" src="https://user-images.githubusercontent.com/38515714/164229521-fa76933d-7f39-410e-96e6-a14631eb3d13.png">

the code left(prettier) looks better, the code right(volar) looks bad.
大白话：左边的看起来更好，右边的看起来有点糟。

2、When enter some enters or spaces, then format with volar, it seems not come into force?

<img width="1374" alt="截屏2022-04-20 下午8 30 41" src="https://user-images.githubusercontent.com/38515714/164230795-901f5648-1546-420c-b1bd-2946c421a36a.png">

大白话：键入几个enter键，也就是换行，发现这几个换行经过volar的格式化之后，竟然没有去掉？

**Comment by johnsoncodehk** [comment] 2022-04-20 12:36
Duplicate of #1174

**Closed by johnsoncodehk** 2022-04-20 12:36 UTC
