### ISSUE TITLE
Strange typing issue trying to create a wrapper component

### ISSUE THREAD

**Issue by Shayan-To** [johnsoncodehk/volar#1433] opened 2022-06-09 15:55 UTC
I'm trying to create a wrapper component, so that everything is passed to the child element. This code is giving me errors:

```
<template>
    <component is="some-component">
        <template v-for="slot in Object.keys($slots)" #[slot]="slotProps">
            <slot :name="slot" v-bind="{ ...slotProps }" />
        </template>
    </component>
</template>

<script setup lang="ts"></script>
```

The error is that it does not recognize `slotProps`, and says `Property 'slotProps' does not exist on type ....`.

When I don't use `<component is="...">`, the problem goes away. From what I'm seeing from the syntax coloring, the identifier `slot` in `#[slot]="slotProps"` is red when the error occurs, but is black when it doesn't. So there might be a problem with typing of `component` component, that I couldn't figure out how to fix.

Version: 0.37.3
Repro link: https://gist.github.com/Shayan-To/d7046b159232b09d7eafd1e88cea3aaa

**Comment by johnsoncodehk** [comment] 2022-06-12 20:34
Duplicate of #1425

**Closed by johnsoncodehk** 2022-06-12 20:34 UTC
