### ISSUE TITLE
when using <script lang="ts" src="./index">,  it reports error with "can't find name "XXX"

### ISSUE THREAD

**Issue by xxx-runj** [johnsoncodehk/volar#1019] opened 2022-03-09 10:54 UTC
I installed Volar in VsCode, and when I using  <script lang="ts" src="./index">, It keeps getting an error here ： can't find name "XXX".  This will not  disappear unless I reload VsCode, but once I write a new variable，it comes again.
<img width="535" alt="image" src="https://user-images.githubusercontent.com/56994279/157427652-8d36aa5b-7cde-41d5-b8c9-247ccbaff557.png">

<img width="517" alt="image" src="https://user-images.githubusercontent.com/56994279/157427715-673ca56f-1e4c-4685-ad3d-09b6504869e7.png">

**Comment by johnsoncodehk** [comment] 2022-03-09 11:24
Duplicate of #565

**Closed by johnsoncodehk** 2022-03-09 11:24 UTC
