### ISSUE TITLE
v-for="type in ..." breaks syntax highlighting

### ISSUE THREAD

**Issue by lackneets** [johnsoncodehk/volar#1290] opened 2022-05-11 05:58 UTC
Related to https://github.com/johnsoncodehk/volar/issues/1281

When `type` as a iterator variable, it breaks everything below, includes `<style>` but `<script>` tag

![2022-05-11 13 50 25](https://user-images.githubusercontent.com/3694058/167778571-80a94bff-cf2f-417c-99df-dadd735ff40c.gif)
<img width="351" alt="CleanShot 2022-05-11 at 13 55 42@2x" src="https://user-images.githubusercontent.com/3694058/167778641-eb484713-7581-4d5c-8e59-d8be4d634970.png">

**Comment by johnsoncodehk** [comment] 2022-05-29 06:27
Hi @lackneets, this is typescript syntax highlight issue, you can use `v-for="(type in mainMenu"` instead of to avoid.

**Comment by johnsoncodehk** [comment] 2022-05-29 06:27
Duplicate of #520

**Closed by johnsoncodehk** 2022-05-29 06:27 UTC
