### ISSUE TITLE
cpu is very high

### ISSUE THREAD

**Issue by lwp001** [johnsoncodehk/volar#399] opened 2021-08-21 05:38 UTC
use @vicons/ionicons5 or other @vicons/xxx package cpu is very high ;

**Comment by felismargarita** [comment] 2021-08-23 05:25
I have also face this problem for several days,seems,it will not be fixed in short time,I just use @vicons/ionicons4 instead for a temporary solution. :)

**Comment by johnsoncodehk** [comment] 2021-08-24 09:31
I can't reproduce this problem by install `@vicons/ionicons5` to https://github.com/johnsoncodehk/volar-starter.

Please provide reproduce case and description of reproduce steps.

**Comment by neohan666** [comment] 2021-08-25 11:16
so am I

**Comment by johnsoncodehk** [comment] 2021-08-28 22:37
Please let me know if 0.27.8 still the problem.

**Comment by kikyous** [comment] 2021-08-29 02:38
> Please let me know if 0.27.8 still the problem.

seems the problem has been solved in my project
😄

**Comment by johnsoncodehk** [comment] 2021-08-30 06:19
Close because the problem may have been resolved. If not, please open a new issue and provide a reproduce case.

**Closed by johnsoncodehk** 2021-08-30 06:19 UTC
Labels: need more info / repro

**Comment by lwp001** [comment] 2021-09-05 05:36
reinstall  no problem  thanks.

**Comment by yaolunmao** [comment] 2021-09-18 05:59
I reinstalled vscode and volar, but the CPU was still 100%. Only when volar was disabled can it return to normal

**Comment by felismargarita** [comment] 2021-09-19 02:36
> I reinstalled vscode and volar, but the CPU was still 100%. Only when volar was disabled can it return to normal

have you installed naive-ui and its recommended icon lib vicons? If yes ,I guess the problem is caused by this. :)
