### ISSUE TITLE
TsConfig missing for Vue 2

### ISSUE THREAD

**Issue by anyclub** [johnsoncodehk/volar#1953] opened 2022-10-08 12:47 UTC
![image](https://user-images.githubusercontent.com/19922265/194708288-bde55208-51e0-42d1-b04b-85c52f4f3a55.png)

Click on the link but don't see how to fix this tip

how can i fix it?

Vue Language Features (Volar): v1.0.0
Vetur Extended: v0.0.20
vscode: v1.72.0
win11
wsl1

**Comment by johnsoncodehk** [comment] 2022-10-08 12:49
This report message incorrect and fixed in https://github.com/johnsoncodehk/volar/commit/17c50caacb0802462965b5998b12d703c77edff0, you can fix by install `@vue/runtime-dom` to `devDependencies `.

**Comment by anyclub** [comment] 2022-10-08 12:54
![image](https://user-images.githubusercontent.com/19922265/194708546-a46f3ed2-7e0d-4b3e-a9fb-ffa0ec118a96.png)

It doesn't look fixed

**Comment by xiaoxiangmoe** [comment] 2022-10-08 13:03
Can you provide me a reproduction demo repo?

**Comment by johnsoncodehk** [comment] 2022-10-08 18:01
Please open new issue if still not working on v1.0.1.

**Closed by johnsoncodehk** 2022-10-08 18:01 UTC

**Comment by yaohuiwu** [comment] 2024-01-30 02:08
> ![image](https://user-images.githubusercontent.com/19922265/194708546-a46f3ed2-7e0d-4b3e-a9fb-ffa0ec118a96.png)
> 
> It doesn't look fixed

Please check your node_modules directory to ensure the @vue/runtime-dom package was installed successfully.

For me, the issue is caused by the taobao registry which no longer worked.

I changed the registry to https://registry.npmmirror.com/ and installed the package finally. Then the issue was solved.
