### ISSUE TITLE
No intellisense in template when using src imports

### ISSUE THREAD

**Issue by danielcollazo** [johnsoncodehk/volar#1651] opened 2022-07-29 05:16 UTC
Intellisense works when using SFC but not when splitting script/style/template and using [src imports ](https://vuejs.org/api/sfc-spec.html#src-imports).

Using Volar `v0.39.2`

![Screen Shot 2022-07-28 at 10 12 39 PM](https://user-images.githubusercontent.com/91868475/181687339-4ade1de1-9e68-4621-bc8e-49051c0cfaad.png)

![image1](https://user-images.githubusercontent.com/91868475/181686717-8302b1b7-48f2-41b7-893d-0c66c9036f65.png)
![image2](https://user-images.githubusercontent.com/91868475/181686727-91194110-1af7-4576-b611-e9f4ce9fe40a.png)

**App.vue**
```vue
<script lang="ts" setup>
import ComponentA from "./components/ComponentA/ComponentA.vue";
</script>

<template>
  <ComponentA option="Option1" />
</template>
```

**ComponentA.vue**
```vue
<script lang="ts" src="./ComponentA.ts"></script>

<template>
  <div>{{ option }}</div>
  <ComponentB message="blahhhh" />
</template>
```

**ComponentA.ts**
```typescript
import { defineComponent, type PropType } from "vue";
import ComponentB from "../ComponentB/ComponentB.vue";

type Options = "Option1" | "Option2" | "Option3";

export default defineComponent({
  components: {
    ComponentB,
  },
  props: {
    option: {
      type: String as PropType<Options>,
    },
  },
  setup(props) {
    return {
      props,
    };
  },
});

```

**ComponentB.vue**
```vue
<script lang="ts" src="./ComponentB"></script>

<template>
  <div>{{ message }}</div>
</template>

```

**ComponentB.ts**
```typescript
import { defineComponent, type PropType } from "vue";

type Messages = "Hello" | "Goodbye";

export default defineComponent({
  props: {
    message: {
      type: String as PropType<Messages>,
    },
  },
  setup(props) {
    return {
      props,
    };
  },
});

```

**Comment by johnsoncodehk** [comment] 2022-07-29 09:41
Duplicate of #80

**Closed by johnsoncodehk** 2022-07-29 09:41 UTC
