### ISSUE TITLE
TypeScript Vue Plugin (Volar) breaks VSCode

### ISSUE THREAD

**Issue by MaximFedarau** [johnsoncodehk/volar#1956] opened 2022-10-08 18:01 UTC
TypeScript Vue Plugin (Volar) breaks VSCode:
- breaks syntax highlighting: <img align="center" width="83" alt="syntax_highlighting_break_demo" src="https://user-images.githubusercontent.com/87207122/194720946-6c9923c1-90fa-41d1-9209-a0374af36a52.png">
- breaks autocompletion for imports, object fields and etc. <img align="center" width="494" alt="autocompletion_break_demo" src="https://user-images.githubusercontent.com/87207122/194721076-3fccb042-1d4a-4e12-9515-75c508f68d22.png">

My Environment:

| app & software                      | version
| --------------------- | -------
| vscode | 1.72.0
| volar             | 1.0.0

**Comment by johnsoncodehk** [comment] 2022-10-08 18:03
Duplicate of #1946

**Comment by johnsoncodehk** [comment] 2022-10-08 18:03
Please try v1.0.1.

**Comment by MaximFedarau** [comment] 2022-10-08 18:06
> #1946
Updated, but this doesn't work either.

**Comment by johnsoncodehk** [comment] 2022-10-08 18:08
Can you reproduce this problem in https://github.com/johnsoncodehk/volar-starter?

**Comment by MaximFedarau** [comment] 2022-10-08 18:09
Sorry, what do you mean?

**Comment by johnsoncodehk** [comment] 2022-10-08 18:12
Could you try clone https://github.com/johnsoncodehk/volar-starter and than install depends, and see is there some way to reproduce the problem you mentioned in a certain repo file.

**Comment by MaximFedarau** [comment] 2022-10-08 18:27
## Yeah, everything works in `.vue` files.

https://user-images.githubusercontent.com/87207122/194722139-290a28b1-6298-4f38-aaf3-a2be459c7093.mov

<img width="1192" alt="website_demo" src="https://user-images.githubusercontent.com/87207122/194722144-4be91e24-b550-4579-a55e-cd80cf87ca71.png">

## But everything breaks with, for example, `.ts` files:

https://user-images.githubusercontent.com/87207122/194722163-763fbdb7-1827-4168-aa7e-407fd4db12c3.mov

**Comment by MaximFedarau** [comment] 2022-10-08 18:29
<img width="852" alt="version_demo" src="https://user-images.githubusercontent.com/87207122/194722271-ccdc9e55-9bcc-450c-8700-74f769d3ce4d.png">

**Comment by johnsoncodehk** [comment] 2022-10-08 19:14
@MaximFedarau thanks, will check it later, you can try use [takerover mode](https://vuejs.org/guide/typescript/overview.html#volar-takeover-mode) instead of TS plugin for now.

**Closed** 2022-10-08 20:11 UTC
Labels: bug

**Comment by johnsoncodehk** [comment] 2022-10-08 20:13
Please try v1.0.2.

**Comment by MaximFedarau** [comment] 2022-10-08 20:16
YES.
1.0.2 solves the issue!

**Comment by gustavotoyota** [comment] 2022-10-08 20:28
1.0.2 solved the issue!
I only don't use Take Over mode because it makes Go To Definition stop working in monorepos with Project References (https://github.com/johnsoncodehk/volar/issues/1344), else I would use it without problems.
