### ISSUE TITLE
Unexpected errors regarding to "v-if" in vue-tsc

### ISSUE THREAD

**Issue by tsekka** [johnsoncodehk/volar#1205] opened 2022-04-16 05:49 UTC
Here's an example:

```ts
<script setup lang='ts'>
class ExampleClass {
  doSomething() {
    // ..
  }
}

const shouldBeNull = Math.round(Math.random()) === 0
const exampleObject: null | ExampleClass = shouldBeNull ? null : new ExampleClass

// As expected, this is fine and will not give any error
if (exampleObject !== null) {
  exampleObject.doSomething()
}

</script>

<template>
  <!-- 
    Everything OK on vscode, but on console I see:
      "src/ExampleComponent.vue:22:49 - error TS2531: Object is possibly 'null'." 
    -->
  <button v-if="exampleObject !== null" @click="exampleObject.doSomething()">Do it</button>
</template>
```
What can cause this?

**Comment by johnsoncodehk** [comment] 2022-04-20 01:53
Duplicate of #1134

**Comment by tsekka** [comment] 2022-04-21 15:11
So, it's intentional that it shows error in console but not in editor?

**Comment by tsekka** [comment] 2022-04-21 15:36
@johnsoncodehk Both vue-tsc npm package and volar VSCode extension are 0.34.9.

**Comment by tsekka** [comment] 2022-04-21 15:40
> @johnsoncodehk Both vue-tsc npm package and volar VSCode extension are 0.34.9.

Actually I've just updated vue-tsc to 0.34.9. It was 0.33 before. And it's not showing error on console anymore.

**Comment by johnsoncodehk** [comment] 2022-04-21 15:42
It should report an error, will fix in next version. You should change you code to `@click="exampleObject!.doSomething()"`.

**Comment by tsekka** [comment] 2022-04-21 15:43
@johnsoncodehk  Thanks.

**Closed** 2022-04-21 18:17 UTC
Labels: bug
