### ISSUE TITLE
Count ":global()" class names as references in CSS module

### ISSUE THREAD

**Issue by Ky6uk** [johnsoncodehk/volar#1313] opened 2022-05-18 13:04 UTC
I'm not sure is it a bug or a feature request. Just found references counter in styles doesn't handle global class names using `:global()`

```vue
<template>
  <div
    :class="[$style.component, { active: isActive }]"
  />
</template>

<script lang="ts" setup>
  const isActive = true;
</script>

<style lang="scss" module>
  /* 1 reference */
  .component {
    border: 1px solid black;
    padding: 16px;
    transition: background-color 0.15s ease-out;
    cursor: pointer;

    /* 0 references when actually 1 */
    &:global(.active) {
      background-color: lightgray;
    }
  }
</style>
```

**Comment by johnsoncodehk** [comment] 2022-05-29 06:08
Thanks for the report, but we do not support complicated css rules, it was out of project scope.

**Comment by johnsoncodehk** [comment] 2022-05-29 06:08
Duplicate of #157

**Closed by johnsoncodehk** 2022-05-29 06:08 UTC
