### ISSUE TITLE
volar doubt

### ISSUE THREAD

**Issue by cgrain1998** [johnsoncodehk/volar#1825] opened 2022-09-06 02:32 UTC
Why does this plugin always report errors in the project after a period of time?

![image](https://user-images.githubusercontent.com/35121432/188534313-725cc2a1-48e1-4453-9f4a-36e12a2362f3.png)
![image](https://user-images.githubusercontent.com/35121432/188534383-7454075d-82f9-4d82-bfc4-825617b26306.png)

I can't see what's causing the problem at all
Uninstalled and reinstalled the plugin, still the same
Uninstalled without this plugin, there will be no error, I am sure the project is ok

help me 

thx!

**Comment by johnsoncodehk** [comment] 2022-09-06 02:51
You can config `"volar.vueserver.textDocumentSync": "full"` in VSCode setting for now.

**Comment by johnsoncodehk** [comment] 2022-09-06 02:51
Duplicate of #1807

**Closed by johnsoncodehk** 2022-09-06 02:51 UTC
