### ISSUE TITLE
Highlight all occurrences of the selected variable both in `script` and `template`

### ISSUE THREAD

**Issue by rodrigocfd** [johnsoncodehk/volar#1381] opened 2022-06-03 01:32 UTC
When you leave the cursor on a variable, it highlights all its occurrences. However, with Volar, the `script` and `template` sections don't communicate, so the highlighted variable will only show either within `script` or within `template`.

In this screenshot, the cursor is over the variable inside `script`. Note how its occurrences inside `template` are **not** highlighted:

![select-script](https://user-images.githubusercontent.com/1283868/171769413-1c06999a-dbb6-4e93-bce6-bd40802bf0b6.png)

Now the cursor is over the variable inside `template`, and the occurrences inside `script` are **not** highlighted:

![select-template](https://user-images.githubusercontent.com/1283868/171769506-3a90b046-2d47-42e2-bf9e-aa0be2b5790b.png)

I don't know whether this is some sort of technical limitation, but the variables should be highlighted everywhere they're used, all at the same time.

**Comment by johnsoncodehk** [comment] 2022-06-04 10:57
Duplicate of #462

**Closed by johnsoncodehk** 2022-06-04 10:57 UTC
