### ISSUE TITLE
Uses {# #} instead of <!-- --> for template comments

### ISSUE THREAD

**Issue by pheeque1** [johnsoncodehk/volar#1352] opened 2022-05-26 08:45 UTC
Issue Type: <b>Bug</b>

When you toggle line comments, the extension uses `{# #}` instead of `<!-- -->` for commenting code in Vue SFC template tags.

Extension version: 0.34.16
VS Code version: Code 1.67.2 (Universal) (c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5, 2022-05-17T18:20:57.384Z)
OS version: Darwin arm64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 5, 4|
|Memory (System)|16.00GB (0.07GB free)|
|Process Argv|--crash-reporter-id 6e4ab4f6-2ff7-4100-b5dc-ce1fc869657c|
|Screen Reader|yes|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
pythonvsnew555:30457759
vscscmwlcmt:30465135
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549

```

</details>

**Comment by johnsoncodehk** [comment] 2022-05-28 15:33
Hi @pheeque1, volar do not provide embedded language comments define, please check if this problem from your other extensions installed.

**Comment by johnsoncodehk** [comment] 2022-05-28 15:33
Duplicate of #388

**Closed by johnsoncodehk** 2022-05-28 15:33 UTC

**Comment by pheeque1** [comment] 2022-05-30 15:57
Well, I checked all existing issues including the linked and my situation is different. The output in the description is from [bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) which correctly identified volar as the culprit. 

When I disable volar, commenting works correctly so maybe a regression makes volar change how comments are defined 🤷🏾 ? 

It's only a minor annoyance and I guess I can live with wrong comment formatting given how invaluable volar is for other things.

**Comment by johnsoncodehk** [comment] 2022-05-30 16:02
This is definitely a misunderstanding. 🤦‍♂️ Try open a .html file and do comment, you should see `{# #} `.

**Comment by pheeque1** [comment] 2022-05-30 17:13
Now I understand better. I trusted bisect a bit too much. I eventually manually narrowed down the offending culprit which wasn't volar 🤦🏾‍♂️

Thanks for the pointer :)

**Comment by blakegearin** [comment] 2023-07-12 20:04
Thought I'd mention this extension is what was causing this occur for me: [Hugo Language and Syntax Support](https://marketplace.visualstudio.com/items?itemName=budparr.language-hugo-vscode)
