### ISSUE TITLE
Vue Language Features (Volar) flickering

### ISSUE THREAD

**Issue by uhtomeek** [johnsoncodehk/volar#2101] opened 2022-11-09 00:41 UTC
I can't save when I got volar installed, it causes my code to flicker as in the video below

https://user-images.githubusercontent.com/40201744/200707451-59c6ce35-c25a-4d43-ba29-9d9d81a09b64.mp4

**Comment by johnsoncodehk** [comment] 2022-11-09 02:32
Duplicate of #2080

**Closed by johnsoncodehk** 2022-11-09 02:32 UTC
