### ISSUE TITLE
Automatically prompt exception

### ISSUE THREAD

**Issue by TuiMao233** [johnsoncodehk/volar#87] opened 2021-03-05 09:17 UTC
what？？
![image](https://user-images.githubusercontent.com/49724027/110094263-961eb400-7dd6-11eb-9db4-ea0b091f361d.png)

**Comment by johnsoncodehk** [comment] 2021-03-05 09:29
Same to #86, I can't reproduce your problem, I need a repro to check.

<img width="591" alt="螢幕截圖 2021-03-05 下午5 27 41" src="https://user-images.githubusercontent.com/16279759/110095670-1b569880-7dd8-11eb-9268-873b1b4c7bf4.png">

**Comment by johnsoncodehk** [comment] 2021-03-05 16:01
Fixed in 0.22.2.

**Closed by johnsoncodehk** 2021-03-05 16:01 UTC
