### ISSUE TITLE
The same variable should have the highlight

### ISSUE THREAD

**Issue by ghost** [johnsoncodehk/volar#4861] opened 2024-09-20 12:18 UTC
### Vue - Official extension or vue-tsc version

2.1.6

### VSCode version

1.93.1

### Vue version

3.4.37

### TypeScript version

5.7.20-dev

### System Info

```shell
System:
    OS: Windows 11 10.0.26100
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
    Memory: 18.31 GB / 23.93 GB
  Binaries:
    Node: 22.8.0 - C:\Program Files\nodejs\node.EXE
    npm: 10.8.2 - C:\Program Files\nodejs\npm.CMD
    pnpm: 9.10.0 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (128.0.2739.79)
```

### package.json dependencies

```json
"dependencies": {
    "vue": "^3.4.37"
  },
  "devDependencies": {
    "@vitejs/plugin-vue": "^5.1.2",
    "typescript": "^5.5.3",
    "vite": "^5.4.1",
    "vue-tsc": "^2.0.29"
  }
```

### Steps to reproduce

1、新建vue项目： `pnpm create vite --template vue-ts my-project`
2、切换到`HelloWorld.vue`文件，光标停留在`count`变量上，所有count变量没有高亮
![QQ20240920-201025](https://github.com/user-attachments/assets/ca4b4e3b-5ff7-4a60-8bdc-6f804f3ae56e)
3、在`main.ts`进行测试，高亮显示
![QQ20240920-201025](https://github.com/user-attachments/assets/775db7bd-a818-47dd-9e52-eb593709c398)

### What is expected?

同一个变量应该具有高亮

### What is actually happening?

同一个变量应该没有高亮

### Any additional comments?

thank's your job！❤

**Comment by KazariEX** [comment] 2024-09-20 13:49
Duplicate of #4850

**Closed as not planned by KazariEX** 2024-09-20 13:49 UTC
Labels: duplicate
