### ISSUE TITLE
Use vue inline style object bind, throw a ts error.

### ISSUE THREAD

**Issue by shadowdreamer** [johnsoncodehk/volar#131] opened 2021-04-09 02:45 UTC
```
//- pug
 div(:style="position")

```

give an error

```
(property) HTMLAttributes.style?: StyleValue | undefined

Type “{ position: string; top: string; }”   is not assignable to type “StyleValue | undefined”
```

is this can be fix by volar?

**Comment by johnsoncodehk** [comment] 2021-04-09 02:51
You should match the type of `:style`, try this:

```ts
import type { CSSProperties } from 'vue';
const position: CSSProperties = {
  position: '...',
  top: '...',
};
```

**Comment by johnsoncodehk** [comment] 2021-04-09 02:52
Duplicate of #30

**Closed** 2021-04-09 02:52 UTC
Labels: duplicate
