### ISSUE TITLE
PascalCase component tags are shown as invalid

### ISSUE THREAD

**Issue by ERROPiX** [johnsoncodehk/volar#587] opened 2021-10-12 20:47 UTC
All component tags formatted with Pascal Case are show with an annoying red color for no reason.

![image](https://user-images.githubusercontent.com/6576868/137026295-7cd61e84-4bf3-4798-8604-c7c66d30c492.png)

Also, changing the `volar.preferredTagNameCase` value has no effect on this, I tried all the values.

**Comment by johnsoncodehk** [comment] 2021-10-13 05:31
Duplicate of #522

**Closed by johnsoncodehk** 2021-10-13 05:31 UTC
