### ISSUE TITLE
Linting is failing on pug although code is parseable

### ISSUE THREAD

**Issue by geoidesic** [johnsoncodehk/volar#1917] opened 2022-09-30 11:13 UTC
![Screenshot 2022-09-30 at 11 55 28](https://user-images.githubusercontent.com/4637995/193257641-539dbaf1-9f49-48be-9310-9bbb168570aa.png)

The error doesn't seem to match the actual content. The attribute name doesn't contain any of the characters that the linting is complaining about:
```
        img(width='250px' no-transition :src=`
              course.thumbnailUrl
                ? course.thumbnailUrl
                : course.thumbnailId
                ? '/api/v1/documentmgt/' + course.thumbnailId
                : '/default.jpg'
            `)
```

Another example:
![Screenshot 2022-09-30 at 12 14 11](https://user-images.githubusercontent.com/4637995/193258002-cb87499e-b197-4f91-8d2e-e2941527c2c8.png)

```
                q-icon(color='primary' :name=`
                      material.type == 'video'
                        ? 'play_circle_filled'
                        : material.type == 'link'
                        ? 'open_in_new'
                        : material.type == 'pdf'
                        ? 'description'
                        : material.type == 'form'
                        ? 'format_list_bulleted'
                        : material.type == 'quiz'
                        ? 'quiz'
                        : ''
                    `)
```

**Comment by geoidesic** [comment] 2022-09-30 11:14
Another example:
![Screenshot 2022-09-30 at 12 14 11](https://user-images.githubusercontent.com/4637995/193258002-cb87499e-b197-4f91-8d2e-e2941527c2c8.png)

```
                q-icon(color='primary' :name=`
                      material.type == 'video'
                        ? 'play_circle_filled'
                        : material.type == 'link'
                        ? 'open_in_new'
                        : material.type == 'pdf'
                        ? 'description'
                        : material.type == 'form'
                        ? 'format_list_bulleted'
                        : material.type == 'quiz'
                        ? 'quiz'
                        : ''
                    `)
```

**Comment by johnsoncodehk** [comment] 2022-10-18 00:31
I can't reproduce this error, I think it's fixed in latest version, please try update to 1.0.8.

**Closed by johnsoncodehk** 2022-10-18 00:31 UTC
