### ISSUE TITLE
Cannot resolve the typing of default export, but named export can.

### ISSUE THREAD

**Issue by miaulightouch** [johnsoncodehk/volar#1524] opened 2022-06-30 03:54 UTC
create vue3 project with typescript support, and add files below

```vue
<!-- TestUnit.vue -->
<script setup lang="ts">
import type { SomeClass2 } from "./SomeClass";
import type SomeClass from "./SomeClass";

const a = (i: any) => console.log(i);
</script>

<template>
  <div @hi="(x: SomeClass) => a(x)" @hello="(x: SomeClass2) => a(x)"></div>
</template>
```

```ts
// SomeClass.ts
export default class SomeClass {
  public someMethod(): void {
    console.log("Hello World");
  }
}

export class SomeClass2 {
  public someMethod(): void {
    console.log("Hello World");
  }
}
```

but only default export class cannot be resolved

![image](https://user-images.githubusercontent.com/5199594/176589180-6677859d-a9f5-4810-b67a-505a991b9f3b.png)

**Comment by johnsoncodehk** [comment] 2022-07-07 05:01
Duplicate of #891

**Closed by johnsoncodehk** 2022-07-07 05:01 UTC
