### ISSUE TITLE
Using self closing component named `Svg` breaks syntax highlighting

### ISSUE THREAD

**Issue by bgoscinski** [johnsoncodehk/volar#1281] opened 2022-05-09 18:55 UTC
Repro:

1. Clone https://github.com/bgoscinski/volar-syntax-highlighting-repro.git
2. Open `src/App.vue` in vscode with Volar installed and uncomment [3rd line](https://github.com/bgoscinski/volar-syntax-highlighting-repro/blob/db5de1af4100287fbecda0495c10d27078873753/src/App.vue#L3)

![sytax-highlight](https://user-images.githubusercontent.com/5730169/167478230-c37cf70e-70d7-4475-a070-d427cec059e9.gif)

**Comment by lackneets** [comment] 2022-05-10 09:46
+1 same problem here
<img width="536" alt="CleanShot 2022-05-10 at 17 45 54@2x" src="https://user-images.githubusercontent.com/3694058/167600405-c015a618-7028-4b5f-857c-92b215e6629c.png">

**Comment by hmt** [comment] 2022-05-16 14:04
it'll also break when svg tags are split across two lines:

```
<svg  ....>
  <some paths>
  <svg
><div ...>
```

**Comment by johnsoncodehk** [comment] 2022-05-22 11:10
Duplicate of #192

**Closed by johnsoncodehk** 2022-05-22 11:10 UTC
