### ISSUE TITLE
Write typescript code in vue3 setup template without any hint

### ISSUE THREAD

**Issue by social-uni** [johnsoncodehk/volar#1356] opened 2022-05-27 07:07 UTC
![image](https://user-images.githubusercontent.com/14007972/170648928-68959474-f140-4b0e-9ce6-bd1fb6bb3c52.png)

Without any hint

The desired results are as follows
![1653635203(1)](https://user-images.githubusercontent.com/14007972/170649123-79c3f25a-3b86-4cc5-b13a-442ca2385048.jpg)

Automatic import is expected
![image](https://user-images.githubusercontent.com/14007972/170649190-56a69ca0-e6a3-46a0-84af-e58cb1fcc2df.png)

**Comment by johnsoncodehk** [comment] 2022-05-28 14:35
Duplicate of #823

**Closed by johnsoncodehk** 2022-05-28 14:35 UTC
