### ISSUE TITLE
Disable components auto import in nuxt applications but leave autocomplete

### ISSUE THREAD

**Issue by xxSkyy** [johnsoncodehk/volar#794] opened 2021-12-16 01:18 UTC
Nuxt and Vite with proper plugins does auto import components with proper names. 
Can there be added autocompletion mode without auto importing component? Actually disabling auto import disables also autocompletion.
Also it'd be nice if it'd auto enable when extension will detect nuxt config file in root directory of project.

**Comment by johnsoncodehk** [comment] 2021-12-16 02:04
You can config `"volar.completion.autoImportComponent": false` in vscode.

**Comment by johnsoncodehk** [comment] 2021-12-16 02:04
Duplicate of #438

**Closed by johnsoncodehk** 2021-12-16 02:04 UTC

**Comment by xxSkyy** [comment] 2021-12-16 02:14
> You can config `"volar.completion.autoImportComponent": false` in vscode.

But then I'm losing whole autocomplete prompt as I said in issue, it's about autocompletion enabled without importing in script

**Comment by johnsoncodehk** [comment] 2021-12-16 03:17
component auto import is not for global component auto-complete, you should define GlobalComponents interface, see https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#using.

**Comment by xxSkyy** [comment] 2021-12-16 04:07
> component auto import is not for global component auto-complete, you should define GlobalComponents interface, see https://github.com/johnsoncodehk/volar/tree/master/extensions/vscode-vue-language-features#using.

I don't mean global component, I mean my own component that in nuxt are kinda global because it's scanned and auto imported if you'll use same name / PascalCase for folder path, same as Vite auto import plugin.
https://nuxtjs.org/docs/configuration-glossary/configuration-components/
So when I have `TheNavbar.vue` component I get auto-complete in nuxt application but when I'll use it's imported in script when it's not needed to, all I needed is only autocomplete. It's pretty useful as having many one-category components like `AppButton.vue` `AppDecoration.vue` `AppTooltip.vue` `AppModal.vue` etc. when I'll write App I'll get list of all components that matches it and I don't even have to look in components directory.

**Comment by johnsoncodehk** [comment] 2021-12-19 12:48
It should works in nuxt project, because nuxt generate GlobalComponents interface automatic.

Please provide a repro case if it's not working.

**Comment by Pryscy** [comment] 2022-06-25 11:06
I don't understand why `"volar.completion.autoImportComponent": false` disables the whole autocompletion, it looks like a bug. Am I missing something ?
