### ISSUE TITLE
In Vue 2, Type Guard is not available in `<template v-if="foo" #bar>` with Volar, but is available with Vetur

### ISSUE THREAD

**Issue by mascii** [johnsoncodehk/volar#1487] opened 2022-06-21 01:21 UTC
Sample repo: https://github.com/mascii/volar-and-vetur-testing-on-vue-2

In the following code, Type Guard is not available in `<template v-if="user" #header>` with Volar, but is available with Vetur:

```vue
<template>
  <div>
    <MyComponent>
      <template v-if="user" #header>
        Hello, {{ user.name }}!
      </template>
      <template v-if="user">
        Hello, {{ user.name }}.
      </template>
    </MyComponent>
  </div>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api';
import MyComponent from './components/MyComponent.vue';

type User = { name: string };

const getUser = (): User | undefined => {
  if (Math.random() < 0.5) {
    return undefined;
  }
  return {
    name: 'Bob',
  };
}

export default defineComponent({
  name: 'App',
  components: {
    MyComponent,
  },
  setup() {
    const user = getUser();

    return {
      user,
    };
  }
});
</script>
```

<img width="1512" alt="template-type-guard-volar" src="https://user-images.githubusercontent.com/13311608/174696656-17648e00-b7bc-4f0a-97bd-2f2bcc4a6c72.png">

<img width="1512" alt="template-type-guard-vetur" src="https://user-images.githubusercontent.com/13311608/174696098-ae6fa2fa-eb86-4810-9c2d-5e4a2297060e.png">

**Comment by johnsoncodehk** [comment] 2022-07-07 07:18
Duplicate of #625

**Closed by johnsoncodehk** 2022-07-07 07:18 UTC
Labels: bug
