### ISSUE TITLE
TypeScript error for `@click` - Type '() => void' is not assignable to type 'undefined'

### ISSUE THREAD

**Issue by ttntm** [johnsoncodehk/volar#464] opened 2021-09-07 15:21 UTC
Updated to VS Code 1.60 (TypeScript 4.4) today and started seeing these TS errors in my SFC's:

```vue
<script setup lang="ts">
  ...
  const onFilterBtnClick = () => windowOpen.value === 0 ? showWindow(3) : showWindow(0)
  ...
</script>

<template>
  ...
    <ButtonFilter :window="windowOpen" @click="onFilterBtnClick" />
  ...
</template>
```

There were no issues when I worked on the project last week.

Full component: https://github.com/ttntm/recept0r-ts/blob/main/src/views/Home.vue

This TS error happens to any `@click` attributes that are attached to components with props defined via TypeScript (as described here: https://v3.vuejs.org/api/sfc-script-setup.html#typescript-only-features):

- `@click` for components with TS props: `(property) click: undefined`
- `@click` for components without TS props: `(property) click: ((...args: any[]) => any) | undefined`

...copying that type definition into the button component's `defineProps` doesn't make any difference; any type for property `click` seems to be ignored.

**Comment by johnsoncodehk** [comment] 2021-09-07 15:32
I can't reproduce this problem, please try update your deps.

**Comment by johnsoncodehk** [comment] 2021-09-07 15:33
Duplicate of #460.

**Closed** 2021-09-07 15:34 UTC

**Comment by ttntm** [comment] 2021-09-07 15:50
Thanks, I didn't find #460 before opening this one, should have looked more carefully.

Resolution:

```vue
  const props = defineProps<{
    ...
    onClick?: () => void
  }>()
```

or

```vue
  interface Props {
    ...
    onClick?: () => void
  }

  const props = withDefaults(defineProps<Props>(), {
    ...
  })
```

**Comment by johnsoncodehk** [comment] 2021-09-07 15:54
No click event should be `(property) click: ((payload: MouseEvent) => void) | undefined` by default, if it not it's a bug.

**Comment by ttntm** [comment] 2021-09-07 16:08
> No click event should be (property) click: ((payload: MouseEvent) => void) | undefined by default, if it not it's a bug.

This is what I get "by default" after running `npm update`:

![Code_kLFkOodNgH](https://user-images.githubusercontent.com/41571384/132376586-35f03744-89f2-4395-adbe-6507c1e2a0e1.png)

vue@3.2.9
vite@2.5.4
vite plugin-vue@1.6.1

**Comment by johnsoncodehk** [comment] 2021-09-07 16:09
Have you try delete package-lock.json / yarn.lock + node_modules and reinstall it?

**Comment by ttntm** [comment] 2021-09-07 16:16
Not yet, will give it another try tomorrow and test on another machine too. 

Will report back with additional info.

Thanks!

**Comment by ttntm** [comment] 2021-09-08 07:15
Good morning, just deleted node_modules and package-lock.json, reinstalled and `@click` types are working correctly again.

Still no idea what broke it, might look into it some more if it ever happens again.

Thanks for your time and tips @johnsoncodehk, really appreciate it!

**Comment by vincerubinetti** [comment] 2022-06-17 23:34
I found that reinstalling node_modules didn't work for me.

Here's something strange I noticed though: I have a custom component that I'm using a `@click.stop` attribute on, with no `=""` or anything, and it's giving me the error. But oddly, if I change the tag name from my custom component to a built-in HTML component, e.g. `<button>`, the error goes away. Another remedy is to just specify a blank attribute (which I guess Vue treats as `undefined`?) like this: `<CustomComponent @click.stop=""/>`

**Comment by johnsoncodehk** [comment] 2022-09-21 17:45
@vincerubinetti fixed by https://github.com/johnsoncodehk/volar/commit/94d1546f57f0bbd101669abe2b119e9b4adc4e94.

**Comment by omarmfs98** [comment] 2022-10-09 16:52
make sure you don't have this extension installed in visual studio code: Vue Language Features (Fly), uninstalling it removed that underline

VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=Vue.volar

**Comment by ldsenow** [comment] 2022-10-11 02:28
This issue appears again on v1.0.3. This version has a few breaking changes e.g. this issue and also kebab-case prop

**Comment by jbaubree** [comment] 2022-10-11 09:02
@ldsenow new issue was created for that https://github.com/johnsoncodehk/volar/issues/1985

**Comment by xieyuheng** [comment] 2022-10-13 03:25
Here is a minimal vue component for you to reproduce this problem:

```
"vue-tsc": "^1.0.7"
```

Error:

```
src/components/Link.vue:8:6 - error TS2322: Type '() => void' is not assignable to type 'MouseEvent'.

8     @click="
       ~~~~~
```

```vue
<script setup lang="ts">
// We can not use <RouterLink> in headlessui:
// - https://github.com/tailwindlabs/headlessui/issues/143
</script>

<template>
  <span
    @click="
      () => {
        if (typeof $attrs.href === 'string') {
          if ($attrs.mode === 'replace') {
            $router.replace($attrs.href)
          } else {
            $router.push($attrs.href)
          }
        }
      }
    "
    ><a class="cursor-pointer"><slot /></a
  ></span>
</template>
```

**Comment by joker77877** [comment] 2022-10-13 08:21
> 

I encountered the same problem in the Nuxt3 project.

**Comment by harjim** [comment] 2022-10-13 08:38
when i run build.

![image](https://user-images.githubusercontent.com/80667818/195546321-67cf4368-25ea-4b43-b8a8-9f0d7afd0adb.png)

"@types/node": "^18.8.5",
"@vitejs/plugin-vue": "^3.1.2",
"typescript": "^4.8.4",
"vite": "^3.1.7",
"vue": "^3.2.40",
"vue-tsc": "^1.0.7"

**Comment by ldsenow** [comment] 2022-10-13 08:47
Downgrade to types/18.8.0 fixed the issue for me

**Comment by harjim** [comment] 2022-10-13 08:51
> Downgrade to types/18.8.0 fixed the issue for me

yeah, I just solved

**Comment by Amixx** [comment] 2022-10-13 13:59
> Downgrade to types/18.8.0 fixed the issue for me

thanks a lot, this resolved this issue for me!

**Comment by Utitofon-Udoekong** [comment] 2022-10-13 22:05
> Downgrade to types/18.8.0 fixed the issue for me

Sorry newbie here. How do I downgrade this in nuxt 3?

**Comment by joker77877** [comment] 2022-10-14 01:38
> > Downgrade to types/18.8.0 fixed the issue for me
> 
> Sorry newbie here. How do I downgrade this in nuxt 3?

npm i @types/node@18.8.0

**Comment by xieyuheng** [comment] 2022-10-14 12:23
This issue will be fixed after we merge: https://github.com/vuejs/core/pull/6855

**Comment by microHoffman** [comment] 2023-01-16 12:05
Any updates on this? I have updated dependencies and I still see this in my ts errors:
```
Type '(e?: MouseEvent) => Promise<void | NavigationFailure>' is not assignable to type '(payload: KeyboardEvent) => void'.
  Types of parameters 'e' and 'payload' are incompatible.
    Type 'KeyboardEvent' is missing the following properties from type 'MouseEvent': button, buttons, clientX, clientY, and 12 more.
```

Template:
```vue
        <router-link
          v-for="(navigationItem, index) of navigationItems"
          :key="index"
          v-slot="{ isActive, navigate }"
          ...>
          <div
              @click="navigate"
              <!-- following line creates the error above -->
              @keypress.enter="navigate">
```

**Comment by rbluethl** [comment] 2023-02-05 21:50
> Downgrade to types/18.8.0 fixed the issue for me

Any news on this? I just downgraded to 18.8.0 which solved it for me for now.
