### ISSUE TITLE
Release 0.40.0+ showing lot of errors (components, events, etc)

### ISSUE THREAD

**Issue by caio-2k** [johnsoncodehk/volar#1795] opened 2022-08-31 13:47 UTC
After update to 0.40.0+ versions my VSCode start to show lot of errors in my custom components, click events and custom events, functions/methods, etc. Im using script setup with typescript. On version 0.39.5- everything works fine, this can be fixed?

![image](https://user-images.githubusercontent.com/59366705/187692172-482b28d2-2ad7-452b-9a17-7ae0ff000f77.png)

![image](https://user-images.githubusercontent.com/59366705/187694208-4c1ce2a9-80e0-4044-bfcf-1e14936effd5.png)

**Comment by caio-2k** [comment] 2022-08-31 19:54
> Can you provide me a minimal reproducible example?

For sure!

1 - Clone this repo that I made: https://github.com/caio-2k/volar-error-report
2 - Run `npm install` and see `App.vue`

**On v0.40.5 I had those issues (the reactive data has been considered as JSX Elements):**

![image](https://user-images.githubusercontent.com/59366705/187769360-d8eccd96-6962-48e3-9789-e659272b0458.png)

**On v0.39.5 this works fine (just an linting error but works anyways):**

![image](https://user-images.githubusercontent.com/59366705/187769796-b1225a9a-4d2f-4536-9cfd-de6adf98ae12.png)

**Comment by xiaoxiangmoe** [comment] 2022-09-01 06:30
Please use

```ts
const datas = reactive({
  roles: [] as Array<string>,
  entities: [] as Array<any>,
});
```

Because newest volar only allow syntax in `tsx`.

You can use [consistent-type-assertions](https://typescript-eslint.io/rules/consistent-type-assertions#assertionstyle) with `assertionStyle: "as"`.

**Comment by xiaoxiangmoe** [comment] 2022-09-01 06:37
duplicate of https://github.com/johnsoncodehk/volar/issues/1706

**Closed by xiaoxiangmoe** 2022-09-01 06:37 UTC
Labels: duplicate
