### ISSUE TITLE
Type '() => Promise<void>' is not assignable to type 'MouseEvent'

### ISSUE THREAD

**Issue by francoism90** [johnsoncodehk/volar#2013] opened 2022-10-13 17:20 UTC
More people are reporting this: https://stackoverflow.com/questions/74037132/how-to-correctly-listen-to-an-event-in-vue-3-using-ts

It seems to be caused by testing, because I only get this when building.

```
src/components/Search.vue:4:6 - error TS2322: Type '() => Promise<void>' is not assignable to type 'Event'.

4     @submit.prevent="submit"
```

**Comment by johnsoncodehk** [comment] 2022-10-13 17:21
Duplicate of #1985

**Closed by johnsoncodehk** 2022-10-13 17:21 UTC
