### ISSUE TITLE
Export named default, not working in template

### ISSUE THREAD

**Issue by jorisvergeer** [johnsoncodehk/volar#2106] opened 2022-11-10 12:43 UTC
I'd like to write components like this:

```
<template>
  <Modal> ... </Modal>
</template>
<script lang="ts">

const MyModal = defineComponent({ ... })

export default MyModal ;

export function showMyModal()
{
  ... //code that uses MyModal 
}

</script>
```

The problem with this is that because i don't use `export default defineComponent({ ... })` directly, then i don't get the typing checks in the template part. 

Shouldn't volar be able to infer the correct defineComponent,  even though in this case it is indirectly exported?

**Comment by johnsoncodehk** [comment] 2022-11-29 10:27
Duplicate of #80

**Closed by johnsoncodehk** 2022-11-29 10:27 UTC
