### ISSUE TITLE
Highlight issue on <script> tag

### ISSUE THREAD

**Issue by leonardssh** [johnsoncodehk/volar#1566] opened 2022-07-12 09:32 UTC
**>** & **<** shouldn't be red.

![image](https://user-images.githubusercontent.com/35312043/178458793-fd2fd6c4-72f4-4a9c-9d26-b286672ca9f3.png)

**Comment by leonardssh** [comment] 2022-07-12 11:59
I've found the issue, apparently that red arrows highlight appears when the `lang="ts"`.

`lang="ts"`
![image](https://user-images.githubusercontent.com/35312043/178484803-fd810cd8-cb0b-4516-aeae-4437c40977fb.png)

`lang="js"`
![image](https://user-images.githubusercontent.com/35312043/178484865-a39b9cc2-9a5f-4af7-afc8-365b36d30f78.png)

`no lang`
![image](https://user-images.githubusercontent.com/35312043/178484905-81573789-a6ac-4672-96f6-4d364162dfb0.png)

**Comment by LoiLock** [comment] 2022-07-13 12:10
Does this work?
```html
<script lang="ts" setup>
</script>
```

**Comment by leonardssh** [comment] 2022-07-13 14:22
> Does this work?
> 
> ```
> <script lang="ts" setup>
> </script>
> ```

Yep, it was the first thing I tried, to no avail.

**Comment by LeanderD** [comment] 2022-07-25 09:48
I have a similar problem and I'm not sure it's this extension that's causing it.

For me it looks like this:
![Screen Shot 2022-07-25 at 11 33 32](https://user-images.githubusercontent.com/12776247/180746590-802c50e5-2ab9-4093-949f-dbfe1e801e4a.png)

And:
![Screen Shot 2022-07-25 at 11 39 28](https://user-images.githubusercontent.com/12776247/180747332-0f2a18c3-5566-4ec7-8443-dc1bcd3a041a.png)

If I remove `lang="ts"` or change it to `lang="js"` the syntax highlighting is correct.

Going back to an older version of this extension isn't fixing it either, disabling VSCode's `bracket pair colorization` does...
(I went back to a version from two months ago. The issue is quite recent and was still there with the older versions)

**Comment by leonardssh** [comment] 2022-07-25 14:45
@LeanderD You've right, the issue doesn't come from the Volar extension, its an issue with vscode bracket pair colorization. Thanks! I think I can close this issue, during its not a valid one.

**Comment by JohnCampionJr** [comment] 2022-08-04 20:26
This has been marked as an extension problem by the VS Code team.  Seems the beginning and ending tags are being returned as two different language types.

https://github.com/microsoft/vscode/issues/156168#issuecomment-1198998741

**Comment by tujianglin** [comment] 2022-08-05 05:55
The question is <script lang="ts”> ; The resulting parentheses have a different color. It has nothing to do with Volar. Does anyone know the solution

**Comment by James-Laidlaw** [comment] 2022-08-05 15:11
@jb-qian found a temporary solution in the other issue thread for this problem (we should probably close one of them by the way)

> open `/Users/${username}/.vscode/extensions/vue.volar-0.39.4-darwin-x64/syntaxes/vue.tmLanguage.json`
> 
> change `"begin": "([a-zA-Z0-9:-]+)\\b(?=[^>]*\\blang\\s*=\\s*(['\"]?)ts\\b\\2)",` to `"begin": "([a-zA-Z0-9:-]+)\\b(?=[^>]*\\blang\\s*=\\s*(['\"]?)\\ts\\b\\2)",` or `"begin": #"([a-zA-Z0-9:-]+)\\b(?=[^>]*\\blang\\s*=\\s*(['\"]?)ts\\b)\\2",`
> 
> reload vscode(v1.70.0)
> 
> it seems that it can be solved temporarily

**Closed** 2022-08-05 20:15 UTC
