### ISSUE TITLE
adding space after colon in tailwind variants

### ISSUE THREAD

**Issue by boussadjra** [johnsoncodehk/volar#1505] opened 2022-06-24 09:24 UTC
In the SFC file style section I've Tailwind CSS classes like : 

```html
<style scoped>
.btn {
   @apply h-max flex justify-center shadow-md hover:shadow items-center  cursor-pointer capitalize
}
</style>
```

when I format the document It adds a space after the `:`  in `hover:shadow` variant and  it will look like `hover: shadow` which will generate a compilation error.

**Env and tools :** 
vscode 1.68.1 windows 11
vite 2.9.7
vue 3.2.33
volar 0.38.1

**Comment by johnsoncodehk** [comment] 2022-07-07 07:19
Duplicate of #1448

**Closed by johnsoncodehk** 2022-07-07 07:19 UTC
