### ISSUE TITLE
JSX element type does not have any construct or call signatures.ts(2604)

### ISSUE THREAD

**Issue by zengkaii** [johnsoncodehk/volar#1407] opened 2022-06-07 04:23 UTC
ts version: 4.5.4
volar version  v0.37.1
![image](https://user-images.githubusercontent.com/38418699/172295503-c4c94605-ba00-475d-8995-a2c5fb5462f7.png)
![image](https://user-images.githubusercontent.com/38418699/172295546-bac500e8-31ff-4161-97f3-604fe4390e44.png)

**Comment by monster898** [comment] 2022-06-07 05:37
Same here, solved this problem after reverting version to v0.36.1.

**Comment by zengkaii** [comment] 2022-06-07 05:50
> Same here, solved this problem after reverting version to v0.36.1.

ok

**Comment by lianyitj** [comment] 2022-06-07 09:47
更新到 v0.37.2 仍然不行

**Comment by johnsoncodehk** [comment] 2022-06-07 09:55
Duplicate of #1405

**Closed by johnsoncodehk** 2022-06-07 09:55 UTC
