### ISSUE TITLE
html tags suddenly have a different color

### ISSUE THREAD

**Issue by LoiLock** [johnsoncodehk/volar#1167] opened 2022-04-11 10:03 UTC
As of recently they look green just like the attributes / properties
<img width="120" alt="image" src="https://user-images.githubusercontent.com/33485182/162715305-1e2ec71e-3a3c-4a62-8571-e4e60899b220.png">

How it used to look
<img width="116" alt="image" src="https://user-images.githubusercontent.com/33485182/162715537-d2dc9be1-6d3f-4c80-aae7-9b1c5b46e053.png">

I can confirm this does not happen using Vetur and is not an issue with my theme as that one hasn't been updated in the last 9 months. Tags appear to be correctly highlighted upon starting vscode, but after a couple of seconds they all turn green.

**Comment by yaegassy** [comment] 2022-04-11 10:04
Duplicate of #1158

**Closed by yaegassy** 2022-04-11 10:04 UTC
