### ISSUE TITLE
custom component with self defined change event  show params type error, this is a error.

### ISSUE THREAD

**Issue by WormGirl** [johnsoncodehk/volar#1007] opened 2022-03-04 06:50 UTC
![image](https://user-images.githubusercontent.com/16078260/156713661-7b9fbf99-b080-4ceb-965e-132098d29196.png)

actruely this event has two params, but  eslint get one params. this is a error.

**Comment by johnsoncodehk** [comment] 2022-03-04 07:00
Duplicate of #1001

**Closed by johnsoncodehk** 2022-03-04 07:00 UTC

**Comment by WormGirl** [comment] 2022-04-11 05:53
This problem appeared again at volar  version `0.34.3`
