### ISSUE TITLE
Intellisense not working with unplugin-vue-components

### ISSUE THREAD

**Issue by zynth17** [johnsoncodehk/volar#1495] opened 2022-06-22 04:50 UTC
i'm using the new version `0.38.1`
right now it has no autocomplete for the props on a component if we use the [unplugin-vue-components](https://github.com/antfu/unplugin-vue-components).
it does work if we import the component.
here is [repro](https://github.com/zynth17/vue-tsc-unplugin-components-bug)

without importing component
![image](https://user-images.githubusercontent.com/45350572/174945730-5f46d0f5-995a-4738-83ea-08d1500a3553.png)

with importing the component
![image](https://user-images.githubusercontent.com/45350572/174945845-fee63bb5-9049-47c8-8baf-1187f0bba9a1.png)

**Comment by Aenopix** [comment] 2022-07-01 20:47
I had this same problem when using pnpm as my package manager.

There's two possible ways you could fix this. I tried only the first one and it works, the other one i think is what vitesse is doing. 

1. Install as a devDependency  the package "@vue/runtime-core"

2. Create a file called .npmrc with contents
```
// .npmrc
shamefully-hoist=true
strict-peer-dependencies=false
```

I understand that this happens with pnpm because of how it installs the packages and the structure of node_modules.

**Comment by zynth17** [comment] 2022-07-02 05:33
> * @vue/runtime-core

thanks! the first workaround works like charm.

**Comment by johnsoncodehk** [comment] 2022-07-07 05:24
Duplicate of #1230

**Closed by johnsoncodehk** 2022-07-07 05:24 UTC
