### ISSUE TITLE
No import intellisense (suggestions) for "@vueuse/core" package

### ISSUE THREAD

**Issue by varmiral** [johnsoncodehk/volar#1738] opened 2022-08-19 22:52 UTC
### package manger

pnpm

### .npmrc

shamefully-hoist=true

### Expected behavior

![image](https://user-images.githubusercontent.com/70450385/185712740-7e0b47ca-135c-4f57-8ae0-322abd5c461a.png)

Unplugin-auto-import is not used. Perhaps the reason is that the package was written in typescript.

**Comment by varmiral** [comment] 2022-08-20 15:24
Auto-import suggestions appear after at least one explicit import in vue. Similar to how typescript prior to ver. 4.0 worked with packages with built-in types. It now has an [includePackageJsonAutoImports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-0.html#smarter-auto-imports) setting that allows to automatically include such packages listed in dependencies.

**Comment by johnsoncodehk** [comment] 2022-09-21 23:01
Duplicate of #963

**Closed by johnsoncodehk** 2022-09-21 23:01 UTC
