### ISSUE TITLE
Volar doesn't work when vscode is first opened, but after disabling it and reloading vscode, it works normally again

### ISSUE THREAD

**Issue by lyJava** [johnsoncodehk/volar#990] opened 2022-02-28 09:50 UTC
This is the picture of the first startup. The volar plug-in does not display the startup time. When I disable it, reload vscode, and it can work normally again. The second picture is that volar works

![Uploading QQ图片20220228172947.png…]()

**Comment by johnsoncodehk** [comment] 2022-03-01 15:00
Duplicate of #976

**Closed by johnsoncodehk** 2022-03-01 15:00 UTC
