### ISSUE TITLE
Bug: Highlighting is missing on the SVG property 'xlink:href'

### ISSUE THREAD

**Issue by popojja** [johnsoncodehk/volar#800] opened 2021-12-17 03:08 UTC
like this:
![image](https://user-images.githubusercontent.com/26264748/146482416-7526ad6e-3182-4b74-9a1e-4ef6dc6d7e27.png)

**Comment by johnsoncodehk** [comment] 2021-12-19 12:19
Duplicate of #776

**Closed by johnsoncodehk** 2021-12-19 12:19 UTC
