### ISSUE TITLE
can not recognize Built-in component  'Component ' in class-component vue file

### ISSUE THREAD

**Issue by wxwzl** [johnsoncodehk/volar#1096] opened 2022-03-22 14:41 UTC
![image](https://user-images.githubusercontent.com/23026803/159509341-83a45e1f-cc8b-464a-a070-930c09c11b11.png)

**Comment by xiaoxiangmoe** [comment] 2022-03-22 15:17
change private to public

**Comment by johnsoncodehk** [comment] 2022-03-22 23:05
Duplicate of #997

**Closed by johnsoncodehk** 2022-03-22 23:05 UTC
