### ISSUE TITLE
Document formatting yields broken results

### ISSUE THREAD

**Issue by WhyNotHugo** [johnsoncodehk/volar#880] opened 2022-01-20 18:58 UTC
For this simple file:

```vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://v3.vuejs.org/api/sfc-script-setup.html#sfc-script-setup
import HelloWorld from './components/HelloWorld.vue'

let x = 7;
x.nope();
</script>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  data() {
    return {
      transitionName: "",
    }
  },
});

</script>

<template>
  <img alt="Vue logo" src="./assets/logo.png" />
  <hr>
  <!-- use a dynamic transition name -->
  <router-view v-slot="{ Component, route }">
    <transition :name="route.meta.transitionName"

mode="out-in"

    >
      <component :is="Component" />
    </transition>
  </router-view>
  <hr>
  <router-link to="/add" class="nav-link">Add</router-link>
  ||
  <router-link to="/tutorials" class="nav-link">Tutorials</router-link>
  <hr>
  <HelloWorld msg="Hello Vue 3 + TypeScript + Vite" />

</template>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}

.fade-enter-active,
.fade-leave-active {
  transition: opacity 0.5s ease;
}


.fade-enter-from,
.fade-leave-to {
  opacity: 0;
}

.slide-left-enter-active,
.slide-left-leave-active,
.slide-right-enter-active,
.slide-right-leave-active {
  transition-duration: 0.5s;
  transition-property: height, opacity, transform;
  transition-timing-function: cubic-bezier(0.55, 0, 0.1, 1);
  /* overflow: hidden; */
}

.slide-left-enter,
.slide-right-leave-active {
  opacity: 0;
  transform: translate(2em, 0);
}

.slide-left-leave-active,
.slide-right-enter {
  opacity: 0;
  transform: translate(-2em, 0);
}

</style>
```

When using the document formatting feature from volar, I get:

```vue
<script setup lang="ts">
// This starter template is using Vue 3 <script setup> SFCs
// Check out https://v3.vuejs.org/api/sfc-script-setup.html#sfc-script-setup
import HelloWorld from './components/HelloWorld.vue'
                        x = 7;
                        ();
                        </script>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
        data() {
                return {
                        transitionName: "",
                }
        },
});

</script>

<template>
        <img alt="Vue logo" src="./assets/logo.png" />
        <hr />
        <!-- use a dynamic transition name -->
        <router-view v-slot="{ Component, route }">
                <transition :name="route.meta.transitionName" mode="out-in">
                        <component :is="Component" />
                </transition>
        </router-view>
        <hr />
        <router-link to="/add" class="nav-link">Add</router-link>||
        <router-link to="/tutorials" class="nav-link">Tutorials</router-link>
        <hr />
        <HelloWorld msg="Hello Vue 3 + TypeScript + Vite" />
</template>

<style>
#app {
        font-family: Avenir, Helvetica, Arial, sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        text-align: center;
        color: #2c3e50;
        margin-top: 60px;
}

.fade-enter-active,
.fade-leave-active {
        transition: opacity 0.5s ease;
}

.fade-enter-from,
.fade-leave-to {
        opacity: 0;
}

.slide-left-enter-active,
.slide-left-leave-active,
.slide-right-enter-active,
.slide-right-leave-active {
        transition-duration: 0.5s;
        transition-property: height, opacity, transform;
        transition-timing-function: cubic-bezier(0.55, 0, 0.1, 1);
        /* overflow: hidden; */
}

.slide-left-enter,
.slide-right-leave-active {
        opacity: 0;
        transform: translate(2em, 0);
}

.slide-left-leave-active,
.slide-right-enter {
        opacity: 0;
        transform: translate(-2em, 0);
}
```

This seems super broken. The typescript part is no longer valid syntax. The HTML and CSS formatted with tabs is very unusual, is that somehow configurable? It doesn't seem to be respecting the buffer's setting to use spaces.

I just tried upgrading to volar 0.30.6, and this is still an issue. I'm using volar via neovim + nvim-lspconfig.

**Comment by johnsoncodehk** [comment] 2022-01-20 19:01
I can't reproduce this problem, could you try in vscode?

**Comment by WhyNotHugo** [comment] 2022-01-20 20:21
> I can't reproduce this problem, could you try in vscode?

I've no idea how to set that up, do you have some quick bootstrap script or something?

**Comment by WhyNotHugo** [comment] 2022-01-20 20:40
Trying to set up a minimal reproduction scenario, it's a bit trickier than expected :sweat_smile:

**Comment by johnsoncodehk** [comment] 2022-01-20 20:45
You can paste your code to App.vue in https://github.com/johnsoncodehk/volar-starter and do format.

**Comment by johnsoncodehk** [comment] 2022-01-28 07:44
This issue will be closed as it cannot be reproduced.

**Closed by johnsoncodehk** 2022-01-28 07:44 UTC
