### ISSUE TITLE
To enable syntax highlighting  for SFC custom block 

### ISSUE THREAD

**Issue by moliu666** [johnsoncodehk/volar#1347] opened 2022-05-25 09:08 UTC
How to  enable syntax highlighting  for SFC custom block 

like [Vetur's Custom Code Blocks](https://vuejs.github.io/vetur/highlighting.html#custom-block)

**Comment by johnsoncodehk** [comment] 2022-05-28 19:06
You can use `lang` attribute to specify any language for custom block like `<foo lang="md">...</foo>`.

**Comment by johnsoncodehk** [comment] 2022-05-28 19:06
Duplicate of #127

**Closed by johnsoncodehk** 2022-05-28 19:06 UTC
