### ISSUE TITLE
Split Editor Script, Template, Style is missing in v1.0.11

### ISSUE THREAD

**Issue by DanielBoettner** [johnsoncodehk/volar#2162] opened 2022-12-01 14:45 UTC
First, thank you for this awesome extension. 🥳 
Underneath my bug (?) report.

Should you need more information regarding this issue, please let me know.

# Problem
After Volar upgraded from version **v1.0.9** to version **v1.0.10**
The green button, allowing to split the current file into script/template (and style?) is missing for me.

# Expected Behavior
The expected behavior is to see the button and be able to split the current vue file into script and template.

![image](https://user-images.githubusercontent.com/21986545/205080158-2ce531a5-b8fd-4280-83e5-431c03c533f9.png)

There are other extensions allowing to split files. But non (AFAIK) split within the same file.
It is super useful to be able to switch files and only have the split in said file and not have a split with several files.

# Quick Fix

Manually downgrading to version **v1.0.9**

**Comment by johnsoncodehk** [comment] 2022-12-01 14:52
Duplicate of #2158

It was intentionally removed and replaced with command to save screen space.

**Closed by johnsoncodehk** 2022-12-01 14:52 UTC

**Comment by DanielBoettner** [comment] 2022-12-01 16:55
Any chance of adding a setting to allow to toggle display of the button.
Might be a personal taste and heavily depending on my extensions/layout/...
But personally I prefer the button over a command/hotkey.

**Comment by johnsoncodehk** [comment] 2022-12-01 17:07
Would you mind to open a new feature request issue to collect feedback?

**Comment by DanielBoettner** [comment] 2022-12-01 17:14
> Due to this being an intentional change, Would you mind to open a new feature request issue to collect feedback?

I wouldn't mind at all. Will get to it right away.
