### ISSUE TITLE
Mutually recursive components break type checking

### ISSUE THREAD

**Issue by MBuchalik** [johnsoncodehk/volar#655] opened 2021-11-02 10:43 UTC
When you create two components that render each other, Volar's type checker will "give up".

# Example

Create two components: `mutual-recursive-a.vue` and `mutual-recursive-b.vue`.

`mutual-recursive-a.vue`:
``` vue
<template>
  <h1>{{ title }}</h1>
  <button @click="showB = true">Show B</button>
  <MutualRecursiveB v-if="showB" />
</template>

<script setup lang="ts">
import { ref } from 'vue';
import MutualRecursiveB from './mutual-recursive-b.vue';

const title = 'Mutual-Recursive A';

const showB = ref(false);
</script>
```

`mutual-recursive-b.vue`:
``` vue
<template>
  <h1>{{ title }}</h1>
  <MutualRecursiveA />
</template>

<script setup lang="ts">
import { defineAsyncComponent } from 'vue';
const MutualRecursiveA = defineAsyncComponent(
  () => import('./mutual-recursive-a.vue'),
);

const title = 'Mutual-Recursive B';
</script>
```

# Expected behavior

These components can successfully be compiled. And they work fine in the browser. Thus, I expected Volar also to have no problems with such components.

# Actual behavior

On Volar `0.28.10`, you get the following:

![grafik](https://user-images.githubusercontent.com/8061217/139831520-707a500a-59e2-447e-88f8-407687585ecb.png)
![grafik](https://user-images.githubusercontent.com/8061217/139831566-0c334dd7-6a8b-4677-b0e0-acb929fd98eb.png)
![grafik](https://user-images.githubusercontent.com/8061217/139831611-83bd7077-a1eb-4437-b382-486993773c8a.png)

---

Is there any way to fix this on my side (e.g. by performing the imports in another way)?

**Comment by johnsoncodehk** [comment] 2021-11-03 02:04
This is TS limitation, you need to avoid it on the implementation level.

In your case you can use single component and recursive itself.

```vue
<template>
	<h1>{{ title }}</h1>
	<button @click="showB = true">Show B</button>
	<template v-if="showB">
		<h1>{{ titleB }}</h1>
		<mutual-recursive-a></mutual-recursive-a>
	</template>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const title = 'Mutual-Recursive A';
const titleB = 'Mutual-Recursive B';

const showB = ref(false);
</script>
```

**Comment by johnsoncodehk** [comment] 2021-11-03 02:05
Duplicate of #644

**Closed by johnsoncodehk** 2021-11-03 02:05 UTC
