### ISSUE TITLE
error on custom emitted event with the same default name

### ISSUE THREAD

**Issue by zynth17** [johnsoncodehk/volar#1026] opened 2022-03-11 03:51 UTC
i'm using [vue-tel-input](https://github.com/iamstevendao/vue-tel-input)
there is a custom event `@input` from the library that has argument `@input (number: String, phoneObject: Object)` based on the documentation. [docs](https://iamstevendao.github.io/vue-tel-input/documentation/events.html).
seem's like in the new version volar generalize the `@input` method with the default args.

i got this error when building my project
![image](https://user-images.githubusercontent.com/45350572/157798553-c392f61b-bd9d-401c-8aa3-e60411f97e9c.png)

this also happen with different emitted event
![image](https://user-images.githubusercontent.com/45350572/157798655-8eecb5f7-d02d-451b-b93b-02d842a8605f.png)

**Comment by barfurth** [comment] 2022-03-11 22:25
The suggested solution from @johnsoncodehk is to downgrade to 0.32.0 to fix this issue. See [his comment on #1001](https://github.com/johnsoncodehk/volar/issues/1001#issuecomment-1062131546).

**Comment by johnsoncodehk** [comment] 2022-03-11 23:06
Duplicate of #1001

**Closed** 2022-03-11 23:06 UTC
