### ISSUE TITLE
With take over mode and disable built-in ts LSP, folding doesn't work in the ts/js file

### ISSUE THREAD

**Issue by imyangyong** [johnsoncodehk/volar#1571] opened 2022-07-13 10:55 UTC
![Snapshot@2x](https://user-images.githubusercontent.com/42476396/178717667-50707fa3-eba5-4cd6-86a8-b974871b69e2.png)

**Comment by imyangyong** [comment] 2022-07-13 10:57
VSCode version 1.69.1

**Comment by wangxdmm** [comment] 2022-07-14 00:04
same issue +1

**Comment by doecs** [comment] 2022-07-16 02:03
same issue +1

**Comment by johnsoncodehk** [comment] 2022-07-16 17:15
Duplicate of #1563

**Closed by johnsoncodehk** 2022-07-16 17:15 UTC
