### ISSUE TITLE
Type-confusion when passing slot in recursive component

### ISSUE THREAD

**Issue by thezzisu** [johnsoncodehk/volar#1432] opened 2022-06-09 15:01 UTC
I've come across a problem. When writing recursive component, and pass down the default slot, I got the `'default' is referenced directly or indirectly in its own type annotation` error.

My environment:
- volar `v0.37.3`
- ts `4.7.2`

POC:
```vue
<!-- poc.vue -->
<template>
  <div>
    <poc v-bind="props">
      <template #default="scoped"> <!-- Type of property 'default' circularly references itself in mapped type '{ [x: string]: any; default: any; }'. -->
        <slot v-bind="scoped"></slot> <!-- 'default' is referenced directly or indirectly in its own type annotation. -->
      </template>
    </poc>
  </div>
</template>

<script setup lang="ts">
const props = defineProps<{
  test: number
}>()
</script>
```
![image](https://user-images.githubusercontent.com/21094314/172878260-bcfbfe4e-6cf0-4491-a265-95835f062ddd.png)

However, since TypeScript cannot deduct cicular type, this issue may need a dirty hack...

Anyway, there is a workaround, by change the slot definition into
```vue
<slot :name="'default'" v-bind="scoped"></slot>
```
which literally 'bypass' this issue.

**Comment by johnsoncodehk** [comment] 2022-06-12 20:18
You can bypass recursive type by `#default="scoped as any"`, see https://github.com/johnsoncodehk/volar/issues/1204#issuecomment-1100596644.

**Comment by johnsoncodehk** [comment] 2022-06-12 20:18
Duplicate of #1204

**Closed by johnsoncodehk** 2022-06-12 20:18 UTC

**Comment by nikosgpet** [comment] 2022-06-22 16:16
Defining the type, doesn't seem to solve the problem for me. 

<img width="1254" alt="CleanShot 2022-06-22 at 18 15 52@2x" src="https://user-images.githubusercontent.com/4588522/175082002-dc297ce0-810b-48f5-9b36-c009cd87a995.png">

**Comment by johnsoncodehk** [comment] 2022-09-21 18:13
@nikosgpet it seems works, but not sure stable.

```
<template #tree-root="data: { item: ITreeGrid }">
  <slot name="tree-root" v-bind="data" />
</template>
```
