### ISSUE TITLE
No error messages in template section

### ISSUE THREAD

**Issue by Leon0402** [johnsoncodehk/volar#1441] opened 2022-06-12 13:29 UTC
I use `https://github.com/johnsoncodehk/volar-starter` to be sure to not have misconfigured anything and installed the normal volar & volar ts vs code extensions. 

In general, there are no error messages about missing imports for components. For instance: 

![image](https://user-images.githubusercontent.com/33933142/173235516-47360375-2454-4616-b1b9-2d9a4c199cb8.png)

No error message about the missing `HelloWorld` import. 

And if I don't use `lang="ts"` there are no error messages at all anymore. See the same example: 

![image](https://user-images.githubusercontent.com/33933142/173235554-1e2fa21e-5dd1-4f3d-ac41-42ed75629c87.png)

No error message about the missing prop.

**Comment by johnsoncodehk** [comment] 2022-06-12 21:01
Duplicate of #844

**Closed by johnsoncodehk** 2022-06-12 21:01 UTC

**Comment by Leon0402** [comment] 2022-06-12 21:09
@johnsoncodehk I don't understand why this is a duplicate? 

In the explanation you mention that the extension is not able to show errors, which are a result of the wrong type. This make sense, because javascript doesn't have these types. 
But in my explample, a prop is just missing and there is no error message for it. What is the explanation for this?

**Comment by johnsoncodehk** [comment] 2022-06-12 21:11
@Leon0402 You should config `checkJs` in tsconfig / jsconfig to enable type-checking for `lang="js"`.

**Comment by Leon0402** [comment] 2022-06-14 19:25
> @Leon0402 You should config `checkJs` in tsconfig / jsconfig to enable type-checking for `lang="js"`.

Thanks this worked! It still doesn't find missing imports in the template section, but this seems to be true for typescript as well. I assume this is a different issue

**Comment by johnsoncodehk** [comment] 2022-06-15 01:55
@Leon0402 if you're using `@vue/composition-api`, see https://github.com/johnsoncodehk/volar/issues/1350.

**Comment by AdrianFahrbach** [comment] 2024-06-26 16:48
I think I got the same issue:
![screenshot 2024-06-26 at 18 46 01@2x](https://github.com/vuejs/language-tools/assets/45072099/5ecd13f4-e0c2-4adb-a0a8-f33c53ab3f8a)
Shouldn't `test` show an error here since it is not defined anywhere? I'm only using the [Vue - Official](https://marketplace.visualstudio.com/items?itemName=Vue.volar) plugin.
