### ISSUE TITLE
保存时prettier自动格式化文件一直在格式化/原格式之间抽搐

### ISSUE THREAD

**Issue by saatana97** [johnsoncodehk/volar#2089] opened 2022-11-03 03:39 UTC
Type: <b>Bug</b>

使用vs的二分扩展法排查问题，发现是本插件

Extension version: 1.0.9
VS Code version: Code 1.73.0 (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:34:06.111Z)
OS version: Windows_NT x64 10.0.22000
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-12400 (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.68GB free)|
|Process Argv|--crash-reporter-id 61da0b4a-9337-42c5-95fc-7a1fb7f153d2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848cf:30577861
nodejswelcome1cf:30587006
fc301958:30595537
2e4cg342:30596373

```

</details>

**Comment by MCheery** [comment] 2022-11-04 12:18
#2080 这里有临时的解决方式

**Comment by saatana97** [comment] 2022-11-05 08:21
> 

我也发现关了这玩意就好了，坐等修复

**Comment by johnsoncodehk** [comment] 2022-11-08 09:53
Duplicate of #2080

**Closed by johnsoncodehk** 2022-11-08 09:53 UTC
