### ISSUE TITLE
Intellisense for props does not work in the template

### ISSUE THREAD

**Issue by HWJ-Code** [johnsoncodehk/volar#1191] opened 2022-04-14 09:34 UTC
Volar
![image](https://user-images.githubusercontent.com/69111271/163356712-b8c01f1b-6fc9-4d92-82a1-960a70d56ace.png)
Vetur
![image](https://user-images.githubusercontent.com/69111271/163356883-115f7c73-b85b-4a7e-bbcb-694220858491.png)

**Comment by MurmeltierS** [comment] 2022-04-14 16:37
Also it seems like no components are getting resolved.

**Comment by johnsoncodehk** [comment] 2022-04-20 01:28
Duplicate of #770

**Closed by johnsoncodehk** 2022-04-20 01:28 UTC
