### ISSUE TITLE
Cannot see comments when defining an prop with default options

### ISSUE THREAD

**Issue by asdjtx** [johnsoncodehk/volar#1434] opened 2022-06-09 19:51 UTC
```vue
<!-- Child.vue -->
<template>
  <div>Child</div>
</template>

<script setup lang="ts">
const props = defineProps({
  /** 注释 */
  count: {
    type: Number,
    default: 10
  }
})
</script>
```

```vue
<!-- Parent.vue -->
<template>
  <child :count="1"></child>
</template>

<script setup lang="ts">
import child from './Child.vue'
</script>
```

When the mouse is over, cannot see the comment, and cannot jump to the definition by `ctrl+ left` clicking

![image](https://user-images.githubusercontent.com/44046607/172929230-6dd156b1-5658-4969-8530-e688adab148d.png)

After deleting the default option, can see the definition information and display the jump

```vue
<!-- Child.vue  -->
<template>
  <div>Child</div>
</template>

<script setup lang="ts">
const props = defineProps({
  /** 注释 */
  count: {
    type: Number,
    // default: 10
  }
})
</script>
```
![image](https://user-images.githubusercontent.com/44046607/172930593-868a4161-d9f5-47c7-9581-282ce2733efe.png)

Use <script> object props has the same problem，but use <script setup> withDefaults() does not
This is a feature or what should I set ?

The operating environment is as follows
```text
VSCode：1.66.2
Vue：3.2.31
Volar：0.34.14
TS：4.6.3(takeover)
```

**Comment by johnsoncodehk** [comment] 2022-06-09 21:28
Duplicate of #1261

**Closed by johnsoncodehk** 2022-06-09 21:28 UTC

**Comment by hasan-almujtaba** [comment] 2022-11-26 15:04
I have updated the vue version to 3.2.45 but JSDOC still not showing.
Here is my component props:

```js
const props = withDefaults(
  defineProps<{
    /**
     * The variant to use.
     * @default filled
     */
    variant?: Variant
    /**
     * The color of the component.
     * @default primary
     */
    colorScheme?: ColorScheme
    /**
     * Loading state of the component
     * @default false
     */
    loading?: boolean
  }>(),
  {
    variant: 'filled',
    colorScheme: 'primary',
    loading: false,
  }
)
```

JSDOC comment missing in here
![image](https://user-images.githubusercontent.com/52339597/204095474-4b976c24-7603-49e1-bd65-9dff07f6a32a.png)
