### ISSUE TITLE
regression: shorthand property in template (v0.34.2)

### ISSUE THREAD

**Issue by cexbrayat** [johnsoncodehk/volar#1159] opened 2022-04-10 12:31 UTC
Bumping from 0.33.9 to 0.34.2, we get these kinds of error in some templates:

```vue
<p>{{ t('live.start', { startInstant }) }}</p>
```

```
src/views/Live.vue:18:29 - error TS18004: No value exists in scope for the shorthand property 'startInstant'. Either declare one or provide an initializer.

18     <p>{{ t('live.start', { startInstant }) }}</p>
```

This was previously compiling fine. It can be worked around by using `startInstant: startInstant`.

**Comment by johnsoncodehk** [comment] 2022-04-10 12:32
Duplicate of #1156

**Closed by johnsoncodehk** 2022-04-10 12:32 UTC

**Comment by cexbrayat** [comment] 2022-04-10 12:34
Sorry @johnsoncodehk , I missed this one 🙏
