### ISSUE TITLE
Cannot find name ts(2304) 

### ISSUE THREAD

**Issue by LLinVIP** [johnsoncodehk/volar#1148] opened 2022-04-06 14:56 UTC
Hello brliant developer and thanks for youe dedicated work on Volar plugin!
![image](https://user-images.githubusercontent.com/68938689/162000930-66cd746e-46ba-4fba-b88c-93c0531b77f7.png)
Now I use Volar version 0.33.10 and there is a bug:`Cannot find name '...' .ts(2304)` errors are displayed on all variables returned in the setup function.
I have viewed issues about `ts(2304)` and try to add in *.d.ts,but it seems make no effect.
```
declare module "@vue/runtime-dom" {
  import type { DefineComponent } from "vue";
  const component: DefineComponent<{}, {}, any>;
  export default component;
}
```
It confused me for a long time. I try to install old verisons, but it still occured.
And I noticed a situation is that when I create this program, it'ok. After I change formatter tool to "Prettier", this problrm seems to occur. I tried to switch back, there is no effect.
"@vue/runtime-dom": "3.2.31",
"vue": "3.2.31".
Thanks for your work!😁

**Comment by johnsoncodehk** [comment] 2022-04-07 05:27
Hi @LLinVIP, I can't reproduce this problem, can you reproduce it in https://github.com/johnsoncodehk/volar-starter?

**Comment by LLinVIP** [comment] 2022-04-07 11:54
Thanks for reply!
Unfortunately I can't reproduce this problem in the project you gave.
But I created a pure uni-app project(use vue3.2, vie2.9.1, TypeScript4.6.3, and Auto-Import-Plugin). And there is a phenomena is that:
When I want to use `getCurrentInstance()`,

![image](https://user-images.githubusercontent.com/68938689/162191794-a0a71482-e652-4852-b5e3-1df1affb66a4.png)

editor prompts me `Property 'proxy' does not exist on type 'ComponentInternalInstance | null'. ,(ts2339)`, and now editor can infer type of variable properly.
I know, based on experience, I add `declare module "@vue/runtime-core"` in *.d.ts, after that, ts2339 error disappeared, but editor can't infer type like this:

![image](https://user-images.githubusercontent.com/68938689/162192299-2bf56815-9708-4801-8835-8f9a6e3c72b5.png)

and error occured in *.d.ts like this `Module '"vue"' has no exported member 'DefineComponent'.(ts2305)`:

![image](https://user-images.githubusercontent.com/68938689/162192490-6ccbedc7-a83e-4a8c-aff3-958fe573ae09.png)


It is confused, thanks for help.😄

**Comment by Zizaco** [comment] 2022-04-10 13:57
I have the very same bug.
![image](https://user-images.githubusercontent.com/777635/162622305-5b442a18-0f1e-477c-8010-f7915c44a74d.png)

`Cannot find name '...' .ts(2304)` errors on all variables returned by the setup function.

**Comment by Kylyi** [comment] 2022-04-10 21:58
I have similar problem that started recently. It might be related.

![image](https://user-images.githubusercontent.com/19700450/162641620-bf49c0bf-2ebf-4f82-97cd-a276e10f17e7.png)

**Comment by benkroeger** [comment] 2022-04-10 22:38
btw. this seems to be a `vue-tsc` issue.
running 

```sh
vue-tsc --noEmit
```

results in the same errors.

However, I was not able to reproduce with the [volar-starter]( https://github.com/johnsoncodehk/volar-starter) repo either.

**Comment by benkroeger** [comment] 2022-04-10 22:45
Also, the type hints inside the template work fine while the error is reported on template level:

![image](https://user-images.githubusercontent.com/7782055/162643081-63e5b975-cc91-4d8b-89c6-03a8c060d239.png)

I'm on TS@4.6.3, vite@2.9.1, vue@3.2.31., vue-tsc@0.34.3

**Comment by johnsoncodehk** [comment] 2022-04-11 05:49
@Kylyi, @benkroeger these should be different issues, is should be fixed in 0.34.4.

**Comment by johnsoncodehk** [comment] 2022-04-11 05:50
@LLinVIP, @Zizaco could you provide minimal reproduction?

**Comment by Zizaco** [comment] 2022-04-13 11:16
@johnsoncodehk I just fixed the problem by updating vscode.
It seemed to be a mismatch between volar and vscode versions.

**Closed** 2022-04-20 01:21 UTC
Labels: need more info / repro
