### ISSUE TITLE
`<template v-for="(item, index) in items" :key="index"` gives "'index' is declared but its value is never read"

### ISSUE THREAD

**Issue by bartenra** [johnsoncodehk/volar#898] opened 2022-01-26 09:13 UTC
```vue
<script setup>
const items = [1, 2, 3, 4]
</script>

<template>
  <template v-for="(item, index) in items" :key="index">
    <div>
      {{ item }}
    </div>
  </template>
</template>
```

As far as I know, this is perfectly valid code. However, I get an "'index' is declared but its value is never read" error.

**Comment by johnsoncodehk** [comment] 2022-01-26 09:15
Duplicate of #329

**Closed by johnsoncodehk** 2022-01-26 09:15 UTC
