### ISSUE TITLE
slotProps Unknown

### ISSUE THREAD

**Issue by LynxWall** [johnsoncodehk/volar#1551] opened 2022-07-10 22:05 UTC
After upgrading Vue Language Features (Volar) to version 0.38.3 all slotProps are now **unknown** causing errors in code.
Reverting to 0.38.2 fixes the issue.

**Comment by johnsoncodehk** [comment] 2022-07-11 02:20
Duplicate of #1541

**Closed by johnsoncodehk** 2022-07-11 02:20 UTC
