### ISSUE TITLE
UI library event types unknown after v1.0.9

### ISSUE THREAD

**Issue by Basaingeal** [johnsoncodehk/volar#2070] opened 2022-10-27 18:05 UTC
I'm not sure the specifics of what would be causing this issue. I use Quasar Framework, and after v1.0.9, there are `value has an implicitly 'any' type` errors that weren't there before. This seems to be because the type of the property is now unknown.

![image](https://user-images.githubusercontent.com/36519219/198364728-025dcdaa-28bc-495d-b426-685279622bae.png)

This is the type definition of the event. I'm not very clear myself how this get translated to type the `update:model-value` event, but it was working in v1.0.8, and not in v1.0.9.

![image](https://user-images.githubusercontent.com/36519219/198365076-625ceabd-7c7d-46f3-b1a6-703527986ea2.png)

Using 1.0.8, it knows the type of the property.
![image](https://user-images.githubusercontent.com/36519219/198365396-91d1b735-fae1-46cc-8e2d-c80c9b1efeea.png)

**Comment by Aicmortal** [comment] 2022-10-28 10:13
me too

**Comment by Aicmortal** [comment] 2022-11-17 07:15
@Basaingeal Hello,Have you solved the problem?

**Comment by Basaingeal** [comment] 2022-11-17 15:00
No. I am waiting for a response from a contributer. Right now, I have my library and extension pinned to `v1.0.8`.

**Comment by Aicmortal** [comment] 2022-11-19 12:33
Well, I'll have to stick to 1.0.8 then

**Comment by johnsoncodehk** [comment] 2022-11-29 11:30
I can't reproduce this problem, please provide repro case.
<img width="710" alt="螢幕截圖 2022-11-29 19 30 08" src="https://user-images.githubusercontent.com/16279759/204517845-b86d42a5-537a-487c-9244-00fd45a9c148.png">

**Comment by Basaingeal** [comment] 2022-11-29 15:00
This appears to be resolved in `v1.0.10`

I'll can still make a repro of the issue with `v1.0.9` in case you want to see what was going on in `v1.0.9`

**Comment by Aicmortal** [comment] 2022-11-30 04:05
This issue occurs with components imported by the unplugin-vue-components plugin, but seems to have been fixed in version 1.0.10.

**Comment by johnsoncodehk** [comment] 2022-12-01 11:02
It should be fixed by https://github.com/johnsoncodehk/volar/commit/9ae9323c69f71fcc3dba8641781cff86263716fe.

**Closed by johnsoncodehk** 2022-12-01 11:02 UTC
Labels: need more info / repro
