### ISSUE TITLE
Auto imported components are highlighted in red instead of green.

### ISSUE THREAD

**Issue by StefanGhiban** [johnsoncodehk/volar#1066] opened 2022-03-17 20:53 UTC
Hi! I have disabled vetur to not have any conflicts with volar and the green highlighting on the auto imported components is gone.
The code keeps working correctly, but the auto imported components appear in red. I am using the unplugin-vue-components from @antfu in a vite setup. If I activate vetur back, the highlighting becomes green again, but I do not want to keep it active in order to avoid conflicts.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/47953165/158893204-342d3eba-ac6f-438b-b02c-af178580f4cb.png">

**Comment by xiaoxiangmoe** [comment] 2022-03-18 04:03
Can you provide me a minimal reproduction?

**Comment by StefanGhiban** [comment] 2022-03-18 07:00
@xiaoxiangmoe
1. I created a component in the components folder.
2. I have added the component to the App.vue root page of the app.
3. Due to having auto importing components plugin for vite, I do not have to explicitly import the component in order to work.
4. The component shows up in the browser and everything works fine, except the component in the template is highlighted in red. When I write the component, volar gives me the option to import that component. The component stays red unles I explicitly import that component in a page with: import Component from './components/Component'

**Comment by ivanRemotely** [comment] 2022-03-18 14:54
Hey there! I'm getting the same issue. I'm using latest Vite/Vue/Typescript, and importing components using the following code:

```ts
const componentsPlugin: Plugin = {
  install: (app) => {
    const components = import.meta.globEager('./*.vue');

    for (const key in components) {
      const component = components[key].default
      app.component(component.name, component);
    }
  },
};
```

**Comment by johnsoncodehk** [comment] 2022-03-20 17:36
See https://github.com/antfu/unplugin-vue-components#typescript

Duplicate of #522

**Closed by johnsoncodehk** 2022-03-20 17:36 UTC

**Comment by StefanGhiban** [comment] 2022-03-20 19:38
@johnsoncodehk The solution from issue #522  doesnt work for me. "editor.semanticHighlighting.enabled": true doesn't change aything for me. Also, the typescript section of the unplugin vue components doesnt apply to me because I am not using typescript.

**Comment by chrislee973** [comment] 2022-04-04 05:35
@StefanGhiban 
Try setting your config to generate the d.ts file: https://github.com/antfu/unplugin-vue-components#typescript. Even though you're using js you need to do this step.

**Comment by ga676005** [comment] 2022-05-16 03:07
This doesn't work for me
tsconfig.json
```json
{
  "include": [
    "./components.d.ts"
  ],
}
```
