### ISSUE TITLE
Duplicate Suggestions Intellisense

### ISSUE THREAD

**Issue by devcaco** [johnsoncodehk/volar#1939] opened 2022-10-07 04:08 UTC
When enabling the Volar extension (Vue Language Features (Volar) - I get duplicated intellisense entries. (See Attached Pictures) - Couldn't find a settings to disable intellisense for this extension. 

![Screen Shot 2022-10-07 at 12 07 10 AM](https://user-images.githubusercontent.com/41708561/194465923-7467da46-ce33-4fdf-8172-d52ea6b006a8.jpg)
![Screen Shot 2022-10-07 at 12 07 01 AM](https://user-images.githubusercontent.com/41708561/194465925-cde6eb1e-3bcd-4871-af41-760d327b7e2c.jpg)
![Screen Shot 2022-10-07 at 12 06 44 AM](https://user-images.githubusercontent.com/41708561/194465926-cff9b1f0-d8ac-4468-9a40-00932d95a5cd.jpg)

**Comment by johnsoncodehk** [comment] 2022-10-08 15:31
Duplicate of #1852

**Closed by johnsoncodehk** 2022-10-08 15:31 UTC
