### ISSUE TITLE
Using vue-tsc with <script setup> causes `@babel/types` errors to be emitted

### ISSUE THREAD

**Issue by leonzalion** [johnsoncodehk/volar#1236] opened 2022-04-25 16:58 UTC
app.vue
```vue
<script setup lang='ts'>
const props = defineProps<{ prop: number }>()
</script>
```

tsconfig.json
```json
{
	"compilerOptions": {
		"types": [
			"vue/ref-macros"
		]
	}
}
```

Running `vue-tsc --declaration --emitDeclarationOnly app.vue` produces the following output in the terminal:
```
node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/typings/babel-parser.d.ts:14:23 - error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.

14 ): ParseResult<import("@babel/types").File>;
                         ~~~~~~~~~~~~~~

node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/typings/babel-parser.d.ts:22:23 - error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.

22 ): ParseResult<import("@babel/types").Expression>;
                         ~~~~~~~~~~~~~~

node_modules/.pnpm/@vue+compiler-core@3.2.33/node_modules/@vue/compiler-core/dist/compiler-core.d.ts:1:57 - error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.

1 import type { BlockStatement as BlockStatement_2 } from '@babel/types';
                                                          ~~~~~~~~~~~~~~

node_modules/.pnpm/@vue+compiler-core@3.2.33/node_modules/@vue/compiler-core/dist/compiler-core.d.ts:2:45 - error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.

2 import type { Function as Function_2 } from '@babel/types';
                                              ~~~~~~~~~~~~~~

node_modules/.pnpm/@vue+compiler-core@3.2.33/node_modules/@vue/compiler-core/dist/compiler-core.d.ts:4:33 - error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.

4 import type { Identifier } from '@babel/types';
                                  ~~~~~~~~~~~~~~

node_modules/.pnpm/@vue+compiler-core@3.2.33/node_modules/@vue/compiler-core/dist/compiler-core.d.ts:5:37 - error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.

5 import type { Node as Node_3 } from '@babel/types';
                                      ~~~~~~~~~~~~~~

node_modules/.pnpm/@vue+compiler-core@3.2.33/node_modules/@vue/compiler-core/dist/compiler-core.d.ts:6:37 - error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.

6 import type { ObjectProperty } from '@babel/types';
                                      ~~~~~~~~~~~~~~

node_modules/.pnpm/@vue+compiler-core@3.2.33/node_modules/@vue/compiler-core/dist/compiler-core.d.ts:8:30 - error TS2307: Cannot find module '@babel/types' or its corresponding type declarations.

8 import type { Program } from '@babel/types';
                               ~~~~~~~~~~~~~~


Found 8 errors in 2 files.

Errors  Files
     2  node_modules/.pnpm/@babel+parser@7.17.9/node_modules/@babel/parser/typings/babel-parser.d.ts:14
     6  node_modules/.pnpm/@vue+compiler-core@3.2.33/node_modules/@vue/compiler-core/dist/compiler-core.d.ts:1
```

The .d.ts file still seems to get generated correctly.

The issue can be fixed by adding `@babel/types` to the project's `devDependencies`, but that doesn't seem like an optimal solution.

**Repro:** https://github.com/leonzalion/vue-tsc-bug

**Comment by johnsoncodehk** [comment] 2022-04-25 17:10
Duplicate of #1114

**Closed by johnsoncodehk** 2022-04-25 17:10 UTC
