### ISSUE TITLE
vue-tsc: conditions on named slots are not narrowing down types

### ISSUE THREAD

**Issue by fieteboerner** [johnsoncodehk/volar#2120] opened 2022-11-16 08:53 UTC
## Version

`vue-tsc@1.0.9`

## Link to minimal reproduction

https://github.com/fieteboerner/vue-tsc-demo
https://github.com/fieteboerner/vue-tsc-demo/blob/main/src/App.vue <-- error reproduced in here

### Steps to reproduce

```bash
git clone https://github.com/fieteboerner/vue-tsc-demo
npm install # node 18
npm run type-check
```

```vue
<HelloWorld>
    <template v-if="response" #foo> 
        <div v-for="line in response.data" :key="line"> <!-- <--- here is the error -->
            {{ line }}
        </div>
    </template>
</HelloWorld>
```

## What is expected?
- no errors at all
- this means that the v-if conditions on named slots (\<template\>-Tags) should be enough to narrow down types as in the example  

## What is actually happening?

- type errors are occurring, so it is necessary to add additional/redundant conditions in the template to pass the type-check

## Any additional comments?

- at the beginning I thought it is not working because there is a vue limitation or a vue logic that does not provide v-ifs at a slot-template
- but on the other hand everything is working fine in the default slot
- all described cases are working fine in the runtime, so it would be great the typecheck is not making the code or flow more complicated
- the longer I am thinking about this issue, the more it make kind of sense, because the inside of a slot is technically a body of  separate function. But on the other hand these are vue internals and not obvious by writing templates. So in my opinion if there is no technical reason, the DX would be by far better, if conditions on a slot-template-tag would be treated the same as at a normal template-tag

**Comment by johnsoncodehk** [comment] 2022-11-29 11:01
Duplicate of #625

**Closed by johnsoncodehk** 2022-11-29 11:01 UTC
