### ISSUE TITLE
代码的颜色突然部分变白了(Sudden loss of code color highlighting)

### ISSUE THREAD

**Issue by WhiteCoffee9834** [johnsoncodehk/volar#885] opened 2022-01-22 06:26 UTC
![Snipaste_2022-01-22_14-22-59](https://user-images.githubusercontent.com/72718918/150627652-54a9947a-146c-4d48-9358-de0c83d77aac.png)

Extension version `v0.31.0`

项目正常运行,工作区没有报错 

目前就这一个文件是这个情况 

其他文件正常 

The project is running normally, no errors are reported in the workspace

The problem occurs with this one file

Other files are displayed normally

---

找出原因了,是因为在使用冒号属性的后面没有加引号导致的

以前这么做并不会导致代码失去高亮,可能开发者把代码校验做的更加严格了?

I found the reason, because I did not use quotation marks after the custom property

This did not cause the code to lose highlighting before, maybe the developers made the code checksum more strict?

**Comment by johnsoncodehk** [comment] 2022-01-22 07:02
Duplicate of #761

**Closed by johnsoncodehk** 2022-01-22 07:02 UTC
