### ISSUE TITLE
emmet Suggested that error

### ISSUE THREAD

**Issue by xiaowenlai** [johnsoncodehk/volar#1064] opened 2022-03-17 14:18 UTC
![test](https://user-images.githubusercontent.com/57058087/158932743-19b748e8-14e6-4ea5-9dd3-abdaae12581b.gif)

Version: 0.33.2

Emmet recommended in the label, version 0.32.1 normal

**Comment by johnsoncodehk** [comment] 2022-03-20 17:29
Duplicate of #1039

**Closed by johnsoncodehk** 2022-03-20 17:29 UTC
