### ISSUE TITLE
Emmet suggests html tags on Style block and does not have css autocomplete

### ISSUE THREAD

**Issue by sandercoffee** [johnsoncodehk/volar#1244] opened 2022-04-28 08:10 UTC
### When trying to write tag name in style block, emmet suggests html tags
![image](https://user-images.githubusercontent.com/60913938/165706849-feaee83f-639e-4780-af3d-cc131eaabc0e.png)
![image](https://user-images.githubusercontent.com/60913938/165706888-932b79cf-4a26-4942-9f79-9c39bf412abd.png)

### Expected suggestion (only tag name)

![image](https://user-images.githubusercontent.com/60913938/165705006-9ca88b67-5783-4c14-9458-0974e936ee92.png)

------

### Not enough, css autocomplete doesn't work
![image](https://user-images.githubusercontent.com/60913938/165707075-4c0fbad0-1f9f-4964-bfb8-92d2b6dc0542.png)

### Expected suggestion (vetur)
![image](https://user-images.githubusercontent.com/60913938/165706105-1119026f-519f-4bcc-a9fa-01c9de51d192.png)

------

Am i forgetting something?
The nuxt 3 documentation recommends switching from vetur to this library, but it still doesn't come close to vetur's features...

thx

**Comment by Daydreamer-riri** [comment] 2022-04-28 08:47
I also encountered the same problem

**Comment by johnsoncodehk** [comment] 2022-04-29 04:09
Duplicate of #480

**Closed by johnsoncodehk** 2022-04-29 04:09 UTC

**Comment by Daydreamer-riri** [comment] 2022-04-29 04:20
> Thanks for the report, but this is expected. We don't have built-in auto-complete support for stylus, so final volar rollback to root vue document completion. Vetur implement it itself (https://github.com/vuejs/vetur/blob/master/server/src/modes/style/stylus/completion-item.ts).
> 
> You can reference to Vetur and implement by Volar langauge service plugin API youself (#1027). You can also send a PR of your plugin implement to https://github.com/johnsoncodehk/volar-plugins.

But I ran into similar problems with LESS and CSS

![image](https://user-images.githubusercontent.com/70067449/165884813-2f4fb571-0f35-49b6-b5b7-7c6698a592f1.png)

**Comment by johnsoncodehk** [comment] 2022-04-29 04:46
@Daydreamer-riri This is a different problem, fixed by https://github.com/johnsoncodehk/volar/commit/0fe0f179e6b6596543635eaa5e123588bd32bac5.

For stylus it still should show emmet result because there no available embedded result.

**Comment by Daydreamer-riri** [comment] 2022-04-29 05:58
![image](https://user-images.githubusercontent.com/70067449/165891540-183dd1ec-042c-46ab-9e45-f1158ccb905b.png)
![image](https://user-images.githubusercontent.com/70067449/165891599-54aac88e-5f68-45fe-872f-2c96c5515a84.png)
Two files under the same project have different effects

**Comment by Daydreamer-riri** [comment] 2022-04-29 06:01
And script
![image](https://user-images.githubusercontent.com/70067449/165892005-c8f3663a-b863-4099-8595-bdfb47251c3c.png)
![image](https://user-images.githubusercontent.com/70067449/165892041-07f824d5-5528-4fb9-885f-684f6d93ded1.png)

**Comment by Daydreamer-riri** [comment] 2022-04-29 06:24
What can I do?  maybe I can only change back to Vetur

**Comment by Daydreamer-riri** [comment] 2022-04-30 01:53
> @Daydreamer-riri this is upstream `@vue/compiler-sfc` error tolerance problem, AST parse is failed with incomplete SFC content.

@johnsoncodehk hello, are you still there? 
 vetur is working fine, but I really wish I could use valor

**Comment by johnsoncodehk** [comment] 2022-05-02 17:45
@Daydreamer-riri vetur is not use `@vue/compiler-sfc` to parse SFC, volar use `@vue/compiler-sfc` because it's vue3 first. You could open a feature request to vue repo for improve error tolerance.
