### ISSUE TITLE
会使代码提示重复

### ISSUE THREAD

**Issue by Cansiny0320** [johnsoncodehk/volar#1075] opened 2022-03-19 10:42 UTC
Issue Type: <b>Bug</b>

代码提示出现两次

Extension version: 0.33.2
VS Code version: Code 1.65.2 (c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1, 2022-03-10T14:33:49.188Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 11, 8|
|Memory (System)|32.00GB (3.77GB free)|
|Process Argv|--crash-reporter-id 8a945534-dff8-48f4-87f1-ec56205ffe69|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vsclayoutctrt:30451275
dsvsc009:30452663
pythonvsnew555:30450902
vscscmwlcmt:30438805
vscgsvid1:30447480
pynewfile477:30450038

```

</details>

**Comment by xiaoxiangmoe** [comment] 2022-03-19 15:06
Duplicate of https://github.com/johnsoncodehk/volar/issues/1063

**Closed by xiaoxiangmoe** 2022-03-19 15:06 UTC
Labels: duplicate
