### ISSUE TITLE
vue-tsc --noEmit => error TS2304: Cannot find name 'data' for `slot-scope="{data}"`

### ISSUE THREAD

**Issue by Yogoort** [johnsoncodehk/volar#1157] opened 2022-04-10 10:22 UTC
Hi!

### Pre-story:

I'm trying to make npm package with Vue components and with typescript definition files. 

It was my pervious version of implementation 
`vue-cli-service build --target lib ./src/index.ts && tsc -p tsconfig.declarations.json`

tsconfig.declarations.json:
```
{
    "extends": "./tsconfig.json",
    "compilerOptions": {
        "emitDeclarationOnly": false,
        "outDir": "dist",
        "declaration": true,
        "typeRoots": [
            "./node_modules/@types",
            "types"
        ],
    },
    "include": [
        "src/**/*.ts",
        "src/**/*.tsx",
        "src/**/*.vue"
    ],
    "exclude": [
        "node_modules",        
        "tests/**/*.ts",
        "tests/**/*.tsx"
    ]
}
```
package.json
```
"vue": "^2.6.12",
"vue-class-component": "^7.2.6",
"vue-property-decorator": "^9.1.2",
"vue-loader": "^15.9.7",
"vue-template-compiler": "^2.6.12",
"vue-tsc": "^0.33.9"
```

But it does not work correctly, cause it makes two builds and leads to issues that I want to avoid.

So, I found this library and checked it for my package.

### Issue:

`vue-tsc --noEmit` 

**result:** 
![image](https://user-images.githubusercontent.com/39881107/162613524-59ec91b7-3ce6-40f6-b4ba-3e0f30902e68.png)

**reason:**
![image](https://user-images.githubusercontent.com/39881107/162613631-6a8f5dfc-f113-4737-8874-47a0229a51fb.png)

It does not work in any other way with `slot-scope="{data}"` or `slot-scope="{data: data}"`

If you have any ideas or suggestions - please help.
Thank you!

**Comment by johnsoncodehk** [comment] 2022-04-10 12:16
`slot-scope` is not supported, please use `v-slot` instead of.

**Comment by johnsoncodehk** [comment] 2022-04-10 12:16
Duplicate of #881

**Closed by johnsoncodehk** 2022-04-10 12:16 UTC
