### ISSUE TITLE
Nuxt 3 - Error: Cannot find name 'xxx' for autoimported functions from `imports.d.ts` after 0.38.3 (2022/7/7) update

### ISSUE THREAD

**Issue by ivan-mihalic** [johnsoncodehk/volar#1544] opened 2022-07-08 10:59 UTC
VS Code shows error for autoimported functions Nuxt 3 like `ref`, `computed`, `useState`, `useHead`, etc... after Volar update 0.38.3 (2022/7/7).
Code works but errors are shown.
Has something change in settings or is it a bug?
thx

<img width="768" alt="CleanShot 2022-07-08 at 12 57 41@2x" src="https://user-images.githubusercontent.com/15858573/177979496-58a2e25c-4723-4912-a1b5-f85d3ee3f84c.png">

**Comment by eddy-bob** [comment] 2022-07-10 22:39
i have the same issue

**Comment by IIFelix** [comment] 2022-07-13 18:54
As far as i know using include in your tsconfig.json will overwrite the "include" option from nuxt's tsconfig.
this is intentional https://www.typescriptlang.org/tsconfig#extends

**Comment by IIFelix** [comment] 2022-07-13 19:00
Autoimports are working for me with Volar 0.38.5.
You can try to delete your .nuxt directory and run "npm run dev" to rebuild your nuxt.d.ts files - maybe that will fix it.

**Comment by evilnemesis** [comment] 2022-07-14 05:44
Hi @Lyokolux,
I don't know what happened, but if I try now it is working correctly no matter what version I have.
I tried the newest version (0.38.5) and the one I had the issue. Both are working correctly. 🤷🏻‍♂️ 
I don't know why it didn't work a week ago. In my team a I have colleague which has the same issue as I.
I will try him if he still has the issue. 

I will leave a comment here after that

Thank you guys

**Comment by Lyokolux** [comment] 2022-07-14 06:29
> Autoimports are working for me with Volar 0.38.5. You can try to delete your .nuxt directory and run "npm run dev" to rebuild your nuxt.d.ts files - maybe that will fix it.

I tried it and it didn't work.
Deleting my includes in tsconfig.json have done the job for me.

**Comment by IIFelix** [comment] 2022-07-20 14:31
I'm closing this one - feel free to open again if issue occurs again.

**Closed by IIFelix** 2022-07-20 14:31 UTC

**Comment by awacode21** [comment] 2023-08-06 11:21
I have the same issue, but i don't have any include configuration on my side:

```
{
  // https://nuxt.com/docs/guide/concepts/typescript
  "extends": "./.nuxt/tsconfig.json"
}
```

i just created new nuxt 3 project, and without any further configuration i have the problem

@IIFelix

**Comment by thedevsbuddy** [comment] 2023-10-26 16:39
I had `Vetur` extension installed when I uninstalled it it stopped showing these errors. 

Please use  `Vue Language Features (Volar)` extension for Vue in VS Code instead of `Vetur`.

**Comment by XiaoQihang** [comment] 2023-11-09 01:10
> I had `Vetur` extension installed when I uninstalled it, it stopped showing these errors.
> 
> Please use `Vue Language Features (Volar)` extension for Vue in VS Code instead of `Vetur`.

Your method worked, I succeeded.

**Comment by boscan-alexandru** [comment] 2023-11-09 18:55
> I had `Vetur` extension installed when I uninstalled it, it stopped showing these errors.
> 
> Please use `Vue Language Features (Volar)` extension for Vue in VS Code instead of `Vetur`.

Yes! It worked and for me solved a lot of not found errors when using nuxt 3

**Comment by yuwankmr** [comment] 2023-12-28 13:03
If you already installed Volar but still the issue is there then try this:

1. CTRL + SHIFT + P in VS Code
2. Volar: Restart Vue Server

**Comment by iqbalwahyudipratama** [comment] 2024-01-22 14:54
> If you already installed Volar but still the issue is there then try this:
> 
> 1. CTRL + SHIFT + P in VS Code
> 2. Volar: Restart Vue Server

Woww, it worked

**Comment by Ezenwankwo** [comment] 2024-03-24 13:31
Restarting vs code worked for me
