### ISSUE TITLE
Typescript errors when iterating over objects inside <template>

### ISSUE THREAD

**Issue by Baloche** [johnsoncodehk/volar#104] opened 2021-03-18 10:01 UTC
👋 Hi!

When iterating over an object keys and values in a `v-for` loop, the following error appears :
<img width="968" alt="Capture d’écran 2021-03-16 à 18 21 33" src="https://user-images.githubusercontent.com/8208027/111607405-804abf00-87d8-11eb-835d-59760ce3cf6c.png">

According to vue documentation, we are supposed to be able to iterate over objects.
When I use vetur instead of volar, this error does not pop.

**Comment by johnsoncodehk** [comment] 2021-03-18 10:46
This is by designed, I narrowed down the `v-for` behavior to make type checking more accurate, see: https://github.com/johnsoncodehk/vue-tsc/issues/3

**Comment by johnsoncodehk** [comment] 2021-03-18 11:35
I found that `for...in` can better to handle it, and it was fixed in 0.22.17. Sorry for make the confusion.

**Closed by johnsoncodehk** 2021-03-18 11:35 UTC
Labels: question
