### ISSUE TITLE
Component red

### ISSUE THREAD

**Issue by SelfMade2001** [johnsoncodehk/volar#1213] opened 2022-04-18 11:19 UTC
Some **components appear red** without reason. I have just started a new laravel 9 jetstream inertia vue 3 project and want to use it without typescript. I have uninstalled Vetur and installed Volar (without the 2 additional typescript extensions)

The problem seems to disappear if I change `<script setup>` to `<script setup lang="ts">` but then other errors occur because **I do not use typescript** and do  not want to use typescript in this project. I have already reloaded vs code and restarted my computer.

The problem should be reproducible by installing laravel jetstream and selecting the inertia stack. Then look for example at resources/js/Pages/PrivacyPolicy.vue  The "JetAuthenticationCardLogo" should not be displayed red, because it contains no error.

![volar problem](https://user-images.githubusercontent.com/68068047/163800833-0208172d-96ca-497c-9814-e64fc4c5960a.jpg)

**Comment by prestonholt** [comment] 2022-04-18 15:19
I also have this issue after upgrading from 0.33.10 to latest (0.34.7). Using latest VSCode and Node 16.14.2

**Comment by johnsoncodehk** [comment] 2022-04-20 01:55
Duplicate of #1192

**Closed by johnsoncodehk** 2022-04-20 01:55 UTC
