### ISSUE TITLE
wrong error notification on @click @submit

### ISSUE THREAD

**Issue by heart** [johnsoncodehk/volar#2040] opened 2022-10-21 03:50 UTC
wrong error notification on @click @submit

![](https://i.ibb.co/L8r7vSf/Screen-Shot-2565-10-21-at-10-47-04.png)

![](https://i.ibb.co/Kwxbdk5/Screen-Shot-2565-10-21-at-10-46-52.png)

**Comment by johnsoncodehk** [comment] 2022-10-21 03:50
Duplicate of #1985

**Closed by johnsoncodehk** 2022-10-21 03:50 UTC
