### ISSUE TITLE
Usage not detected when imported interfaces is referred in templates only

### ISSUE THREAD

**Issue by olemarius** [johnsoncodehk/volar#1280] opened 2022-05-09 14:34 UTC
Volar v0.34.11 
VSCode 1.67.0

TS error:
```vue
<script lang="ts" setup>
  import type { Profile } from '@/services/api/models'; // 'Profile' is declared but never used. ts(6196)
  ....
</script>
<template>
  <div v-for="profile in profiles as Profile[]">
</template>
```

Works:
```vue
<script lang="ts" setup>
  import type { Profile } from '@/services/api/models'; // 'Profile' is declared but never used. ts(6196)
  const profiles = ref<Profile[] | undefined>();
</script>
<template>
  <div v-for="profile in profiles as Profile[]">
  ...
  </div>
</template>
```

**Comment by johnsoncodehk** [comment] 2022-07-16 16:04
Duplicate of #891

**Closed by johnsoncodehk** 2022-07-16 16:04 UTC
