### ISSUE TITLE
</svg> tag formatted over two lines breaks syntax highlighting in whole file

### ISSUE THREAD

**Issue by 2-5** [johnsoncodehk/volar#1623] opened 2022-07-23 00:21 UTC
This was reported multiple times in the past, but there is no open bug and the last one was marked as fixed.

![2022-07-23_031454](https://user-images.githubusercontent.com/3753822/180582590-e1374da1-2252-424d-b010-95c03cc3ba24.png)

If the closing `</svg>` doesn't span two lines the syntax highlighting is fine. Maybe there is a regular expression used somewhere which doesn't have multi-line option enabled.

![2022-07-23_031754](https://user-images.githubusercontent.com/3753822/180582656-5b69bf62-7446-4030-bad6-826ab5b7c84f.png)

**Comment by johnsoncodehk** [comment] 2022-07-23 11:40
This is upstream issue and it can reproduce in .html, see https://github.com/johnsoncodehk/volar/issues/192#issuecomment-844277081.

**Comment by johnsoncodehk** [comment] 2022-07-23 11:40
Duplicate of #192

**Closed by johnsoncodehk** 2022-07-23 11:40 UTC
