### ISSUE TITLE
Can't type dynamic slot when using strict mode for typescript

### ISSUE THREAD

**Issue by kalvenschraut** [johnsoncodehk/volar#2266] opened 2022-12-30 06:51 UTC
[reproduction](https://github.com/RTVision/volar-dynamic-slot-with-strict-example)

Basically the issue is that with strict mode, typescript complains that string | number (type from keyof $slots) can't index the slots object that is inferred from the component you added it to. Not sure how to fix this specifically, if volar has to make a change or if there is a way I can get typescript to not error  here.

**Comment by johnsoncodehk** [comment] 2022-12-30 07:54
Just had a look, this appears to be a duplicate of #625.

**Comment by kalvenschraut** [comment] 2022-12-30 14:11
Doesn't appear obvious to me that it is, but if you say so.

Is there a way to ignore/get around this type error? one only ones I have left before I can turn on strict mode

**Comment by kalvenschraut** [comment] 2022-12-30 14:35
Tried something like the below, but receiving a different error.

![image](https://user-images.githubusercontent.com/30308012/210081608-3b7f8ef9-502b-4da3-9c55-f3a7fe3f0e9a.png)

**Comment by kalvenschraut** [comment] 2022-12-30 14:38
Weird the error just went away after awhile, vue-tsc doesn't error so I guess this works.

**Closed** 2023-01-04 19:48 UTC
Labels: bug
