### ISSUE TITLE
Syntax highlighting breaks when using self-closing tags

### ISSUE THREAD

**Issue by LoiLock** [johnsoncodehk/volar#985] opened 2022-02-25 11:57 UTC
**With self-closing tags**
![image](https://user-images.githubusercontent.com/33485182/155711232-918b570f-a724-41fe-b1e1-a765ef1db8c6.png)

**Without self-closing tags**
![image](https://user-images.githubusercontent.com/33485182/155711261-b2379f0d-315e-47b0-9a26-2fdb74c2ea99.png)

Using self-closing tags (on custom components) seems to break syntax highlighting

**Comment by johnsoncodehk** [comment] 2022-03-01 14:50
Duplicate of #192

**Closed by johnsoncodehk** 2022-03-01 14:50 UTC

**Comment by LoiLock** [comment] 2022-03-02 14:20
This isn't a duplicate of #192. I seem to have fixed it by using lowercase kebab-case for the component name in the template. So the issue is still there.

**Comment by MarekPetr** [comment] 2022-04-11 09:36
I can confirm, that the bug is still there. At least it does not work for us. Volar version v0.34.4. In extreme cases, it also breaks syntax highlighting for the rest of the file.
![image](https://user-images.githubusercontent.com/28509917/162710859-ce7370f0-667a-459c-8891-b57b61b3672f.png)
